### ISSUE TITLE
Klarna Issue Version 3.0.2.0 and alpha

### ISSUE THREAD

**Issue by capte** [opencart/opencart#7081] opened 2018-12-07 06:42 UTC
**What version of OpenCart are you reporting this for?**
Opencart 3.0.2.0 and Alpha

**Describe the bug**
Klarna Checkout activated with test settings in the backend.
Klarna Checkout not displayed in the frontend even though it's activated.

What section does it affect?

**To Reproduce**
1- Go to checkout after module is activated and it simply won't display.
Note: every other payment options seems to work correctly.

**Expected behavior**
Connect to Klarna and display klarna in the checkout section

**Screenshots / Screen recordings**
Printed the results in different array's

[0] to [6] ... Is all the modules that are installed 

```
Array
(
    [0] =&gt; Array
        (
            [extension_id] =&gt; 1
            [type] =&gt; payment
            [code] =&gt; cod
        )

    [1] =&gt; Array
        (
            [extension_id] =&gt; 17
            [type] =&gt; payment
            [code] =&gt; free_checkout
        )

    [2] =&gt; Array
        (
            [extension_id] =&gt; 48
            [type] =&gt; payment
            [code] =&gt; klarna_checkout
        )

    [3] =&gt; Array
        (
            [extension_id] =&gt; 45
            [type] =&gt; payment
            [code] =&gt; cheque
        )

    [4] =&gt; Array
        (
            [extension_id] =&gt; 49
            [type] =&gt; payment
            [code] =&gt; pp_standard
        )

    [5] =&gt; Array
        (
            [extension_id] =&gt; 50
            [type] =&gt; payment
            [code] =&gt; klarna_account
        )

    [6] =&gt; Array
        (
            [extension_id] =&gt; 51
            [type] =&gt; payment
            [code] =&gt; klarna_invoice
        )

)
Array
(
    [firstname] =&gt; Dominic
    [lastname] =&gt; cormier
    [company] =&gt; 
    [address_1] =&gt; 12 olso
    [address_2] =&gt; 
    [postcode] =&gt; 0512
    [city] =&gt; oslo
    [country_id] =&gt; 160
    [zone_id] =&gt; 2440
    [country] =&gt; Norway
    [iso_code_2] =&gt; NO
    [iso_code_3] =&gt; NOR
    [address_format] =&gt; 
    [custom_field] =&gt; Array
        (
        )

    [zone] =&gt; Oslo
    [zone_code] =&gt; OL
)
<b>244.2</b>test : payment_cod_status
cod
this load model : Array
(
    [code] =&gt; cod
    [title] =&gt; Cash On Delivery
    [terms] =&gt; 
    [sort_order] =&gt; 5
)
<br>else:Array
(
    [code] =&gt; cod
    [title] =&gt; Cash On Delivery
    [terms] =&gt; 
    [sort_order] =&gt; 5
)

<br>test : payment_klarna_checkout_status
klarna_checkout
this load model : Array
(
)
<br>test : payment_cheque_status
cheque
this load model : Array
(
    [code] =&gt; cheque
    [title] =&gt; Cheque / Money Order
    [terms] =&gt; 
    [sort_order] =&gt; 
)
<br>else:Array
(
    [code] =&gt; cheque
    [title] =&gt; Cheque / Money Order
    [terms] =&gt; 
    [sort_order] =&gt; 
)
test : payment_pp_standard_status
pp_standard
this load model : Array
(
    [code] =&gt; pp_standard
    [title] =&gt; PayPal
    [terms] =&gt; 
    [sort_order] =&gt; 
)
<br>else:Array
(
    [code] =&gt; pp_standard
    [title] =&gt; PayPal
    [terms] =&gt; 
    [sort_order] =&gt; 
)
test : payment_klarna_account_status
klarna_account (Returns empty)
test : payment_klarna_invoice_status
klarna_invoice (Returns empty)
```

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
Both

 - Operating system
xampp and cpanel (centos7)
 - PHP version
7

**Comment by capte** [comment] 2018-12-14 00:08
Tested with the fix before posting this. I have the same issue in the alpha. The klarna module simply won't show up at checkout.

**Comment by navbeacon** [comment] 2018-12-27 08:44
Same issue on my installation, ref [this forum post](http://forum.opencart.com/viewtopic.php?f=198&t=208998).

**Comment by navbeacon** [comment] 2018-12-29 20:49
After some digging, I see that the Klarna module is returning an empty array, and this issue was discussed a couple of years ago back in #4981. This then seems to be the intended behaviour, but I can't find any definitive answers.

catalog\model\extension\payment\klarna_checkout.php:
`public function getMethod($address, $total) {`
`// Not shown in the payment method list`
`return array();`
`}`
@danielkerr sorry to dig this up, but does this mean that the built in Klarna Checkout module is not supported at this time?

**Comment by danielkerr** [comment] 2020-04-07 13:33
externsion removed out of the core and will be in the opencart marketplace soon.

**Closed by danielkerr** 2020-04-07 13:33 UTC

**Comment by shivankagrawal** [comment] 2025-03-27 06:53
@danielkerr Can you please give me marketplace URL to download this extension ? I need this for Opencart V 3040.
