### ISSUE TITLE
Review - Submit Button is now working on Mobile, Pad.

### ISSUE THREAD

**Issue by ldrosyadi** [opencart/opencart#2752] opened 2015-03-11 11:09 UTC
OC 2.0.1.1. has problem with review product. we cant leave reaview because the submit button is not working on mobile view. 

how to solve it?

**Comment by veksen** [comment] 2015-03-11 14:22
In catalog/view/product/product.tpl line 109, change `<div class="buttons">` to `<div class="buttons clearfix">`.

I also suggest that you add a `<hr class="visible-xs">` after the closing of div.buttons, making the whole thing look like :

    <div class="buttons clearfix">
      <div class="pull-right">
        <button type="button" id="button-review" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-primary"><?php echo $button_continue; ?></button>
      </div>
    </div>
    <hr class="visible-xs">

**Comment by ldrosyadi** [comment] 2015-03-11 15:10
thank a lot for the helping. the second problem is. after we submit the review the form is not clear/ restart automaticly. But the review is recieved by admin.

it is still stranger. can you help me solved it sir:?

**Comment by veksen** [comment] 2015-03-11 18:10
Couldn't reproduce the form not clearing on submit, sorry.

**Closed** 2015-03-16 00:00 UTC
