### ISSUE TITLE
Incorrect price with tax, if the user registered by clicking on the menu OC 3.0.3.1

### ISSUE THREAD

**Issue by infografik** [opencart/opencart#7263] opened 2019-03-11 18:11 UTC
Shop setting: show prices with tax.
At registration, the user does not provide the address.
$this->tax->calculate($result['price'], $result['tax_class_id'], $this->config->get('config_tax')); gives you a price without tax, if the user without the address is logged in.

**Comment by condor2** [comment] 2019-03-25 16:50
I think the bug is for logged customer. I have tested and show price without taxes for login customer with or without customer address.

**Comment by robin555** [comment] 2019-03-26 22:54
It's not a setting problem. I have tried everything.
The problem is the same if the customer logout and login again. All prices are without tax until the customer create an adress.
My problem is almost the same: https://forum.opencart.com/viewtopic.php?f=201&t=210689

**Comment by straightlight** [comment] 2019-07-16 14:06
Has this address issue also been tested on v3.0.3.2 and master branch?

**Comment by jeffreyeng-opencart** [comment] 2019-10-23 10:14
@infografik & @robin555: Has these resolved yet?

**Comment by jeffreyeng-opencart** [comment] 2019-10-29 03:44
Since I don't see any response, I will close this issue.

**Closed by jeffreyeng-opencart** 2019-10-29 03:44 UTC

**Comment by ADDCreative** [comment] 2019-11-04 12:40
Possibly the same issue? https://github.com/opencart/opencart/pull/7594

**Comment by jeffreyeng-opencart** [comment] 2019-11-05 03:58
@ADDCreative: I have to check and see if it is the same or not.
