### ISSUE TITLE
OC 2.2.0.0 Not able to edit order status - Mixed content https issue

### ISSUE THREAD

**Issue by masahrpro** [opencart/opencart#5104] opened 2016-12-27 16:13 UTC
Hey guys & girls!

I have a really nasty issue here with a client website.

After enabling SSL, and forcing the whole site to use SSL the client is not able to edit order status anymore.
First, we got error_undefined, that I traced back to a "httpss://" issue and we solved it from a fix on a forum post by adding a line to admin/controller/sale/order.php
`$data['store_url'] = $this->request->server['HTTPS'] ?str_replace("http", "https", $order_info['store_url']) : $order_info['store_url'];
			 $data['store_url'] = str_replace("httpss://", "https://", $data['store_url']);`

But now, I get this one: 

1. "Mixed Content: The page at 'https://mysite.com/admin/index.php?route=sale/order/info&token=MdywOIefEctlI8QiAcPRkkClCK9sdQIJ&order_id=134' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mysite.com/index.php?route=api/login'. This request has been blocked; the content must be served over HTTPS."
2. "jquery-2.1.1.min.js:4 XMLHttpRequest cannot load http://mysite.com/index.php?route=api/login . Failed to start loading."

config.php & admin/config.php have been forced from http --> https but still same issue.

Any help with this issue is greatly appreciated. I think I am going crrrazy with this bug, and my client is not very happy either.

OC 2.2.0.0.
php 5.5 (tried 5.4 & 5.3 too...)

HELP ME!!!

**Comment by arnisjuraga** [comment] 2016-12-27 18:49
This is because Opencart has problems with global SSL settings. Version to version it depends on some source code "problems". 

But error itself means - that even though, you have enabled SSL - there are still content, which has Opencart generated `http://` links :(
#4347

If you can upgrade to newer opencart - try that (be aware - the upgrade can break the site! Especially, if you hvae custom modules/themes! Do it only on test site and create a full backup before!).

If you cannot upgrade or have issues with upgrade, try this:

1. Edit files 
`admin/view/template/sale/order_info.tpl`
`admin/view/template/sale/order_list.tpl`
`admin/view/template/sale/order_form.tpl`

2. replace 
`<?php echo $store_url; ?>index.php?route=api` 
with
`/index.php?route=api`

**Comment by masahrpro** [comment] 2016-12-27 20:13
@arnisjuraga Thanks for the suggestions. We tried modifying the files, but unfortunately it had no effect.

I am new to OC 2.2.0.0 and a few remarkable things I just don't understand.
There is f.e.x. one weird feature, If I change the link pointing to whatever, it has absolutely no effect. 
We even removed all code in php file in admin/controller/sale/order.php and everything was still loading up in the admin panel. What am I missing here? Why does the edits have null effect?

Cleared cache and tried also in incognito mode, server has no memcache enabled either...
I feel so lost right now.

**Comment by arnisjuraga** [comment] 2016-12-27 20:32
@masahrpro ok, anyway - this is not a bug for Opencart, especially - if you are using custom theme. 
Please, try Community Forum, or give me a PM mail.

**Comment by masahrpro** [comment] 2016-12-27 20:35
Sure, will send PM. 
Same issue comes after OpenCart softaculous fresh install. So I firmly believe it is about Opencart.

**Comment by masahrpro** [comment] 2016-12-27 20:38
@arnisjuraga email sent to info@c.....

**Comment by arnisjuraga** [comment] 2016-12-28 23:35
Yes, Opencart 2.x every version has some issues with SSL implementation. So, just, please, close this issues for now, as it's have been more or less fixed in latest OC versions, and 2.2.0.0. is out of scope of this issue tracker.

**Comment by lapint** [comment] 2017-04-19 15:43
@masahrpro Hey do you have multiple stores setup? `		$data['stores'][] = array(
			'store_id' => 0,
			'name'     => $this->language->get('text_default'),
			'href'     => HTTP_CATALOG
		);

		$results = $this->model_setting_store->getStores();

		foreach ($results as $result) {
			$data['stores'][] = array(
				'store_id' => $result['store_id'],
				'name'     => $result['name'],
				'href'     => $result['url']
			);
		}`

That section shows that if you have multiple stores, it will use the result['url'] value which is entirely different from the values set in the config.php files. If you look at the settings page, you will see your website listed as http://www.mysite.com and not https.

**Comment by danielkerr** [comment] 2017-05-17 12:15
this is fixed in the dev branch

**Closed by danielkerr** 2017-05-17 12:15 UTC

**Comment by BarbaraEster** [comment] 2018-08-29 14:57
Hello guys! your have solution for this problem? i have this problem too. for upgrade not is possible, and i have problem with error indefined in order and edit order :/ i try all and nothing of solutions. we few some idea?
