### ISSUE TITLE
Login and Pay With Amazon module not working

### ISSUE THREAD

**Issue by shrakuma** [opencart/opencart#2994] opened 2015-05-07 20:43 UTC
I have made the necessary setup to get the Login and Pay With Amazon button settings , but when the button is clicked the page doesn't take me to the widgets page . Instead it shows me the same amazon payments button page

**Comment by Mewporg** [comment] 2015-05-09 01:33
The same problem on oc 2.0.2 and i contact amazon payment they told me.

Hi

I was taking a look at the issue and i saw that the Pay With Amazon plug-in itself is not working correctly in Open cart. We will be reaching out to the Open cart developers and informing them about this issue so that they can fix the bug ASAP.


Thank you for selling with Amazon,

shravan K
Amazon.com Seller Support

**Comment by Mewporg** [comment] 2015-05-11 16:57
Last update from Amazon support :

Greetings again,

Sorry for the inconvenience. We are currently working with the Open Cart developers to resolve any issues. I will provide an update as soon as I can. Please let me know if you have any additional questions.


Thank you for selling with Amazon,

Samir K.
Amazon.com Seller Support

**Comment by chris-wm** [comment] 2015-05-12 09:03
@shrakuma @Mewporg,
Hi, we have not received any feedback from Amazon about this issue, can you please provide a detailed description of the problem and I will investigate,
kind regards

**Comment by Mewporg** [comment] 2015-05-12 14:42
Hi,
i appreciate your help, Amazon guys access my website and create accounts and they found there's a problem on pay with amazon (US).

i will take it step by step:

1- login with amazon working without any problem and opencart create user from the customer.

2- The problem on checkout page as you know we create a layout (pay with amazon) this button don't make anything when the customer click on it to pay make the page refresh only without any actions happened.

suggestion: I think it will be better if pay with amazon added on the Payment Method (checkout page) so the visitor may choose it if they didn't see login with amazon button.

**Comment by Mewporg** [comment] 2015-05-12 14:54
I think shrakuma is (shravan K) Amazon customer service and this why he told me we contact opencart team, i appreciate amazon guys help too.

**Comment by chris-wm** [comment] 2015-05-12 15:25
@Mewporg 
Would you be able to provide me with a link to your site so that I can view the problem please?
kind regards

**Comment by Mewporg** [comment] 2015-05-12 16:18
Hello,
i will send you message with site link and details to access the admin panel to check the problem.

**Comment by Mewporg** [comment] 2015-05-12 16:24
How i can give you access details in private i don't see option for that on github ?

**Comment by Mewporg** [comment] 2015-05-12 16:30
website link: https://www.nasey.com/?route=common/home

add any product to the cart and go to checkout page :)

**Comment by chris-wm** [comment] 2015-05-12 16:30
@Mewporg 
Can you send the details to james@opencart.com and he will forward them on to me when he receives them,
kind regards

**Comment by Mewporg** [comment] 2015-05-12 16:34
ok done, i send the message please let him check it and forward it to you.

**Comment by Mewporg** [comment] 2015-05-12 23:39
Did you recieved my message, please confirm!

**Comment by chris-wm** [comment] 2015-05-13 08:10
@Mewporg 
Hi,
I can confirm that he has sent me the email with your details, I will have a look at the issue and get back to you as soon as I can,
kind regards

**Comment by jamesallsup** [comment] 2015-05-18 14:29
Fixed with commit:

https://github.com/opencart/opencart/commit/832707f0adc5695e1feb4ec40762eb2fbd493ba4

**Closed by jamesallsup** 2015-05-18 14:29 UTC

**Comment by shrakuma** [comment] 2015-05-18 18:54
Hi

Is the update pushed to the opencart release?. How will the upgrade to the module be installed on the admin page

**Comment by jamesallsup** [comment] 2015-05-18 19:57
It will be available on the next release (or the current master branch - which is pre-release). The patch link you see above shows the lines you can replace on any previous version.

You only need to replace any instances of "amazon_login_state_cache" with "amazon_Login_state_cache" - notice the CAPITAL "L" on the login word

You could also just over write the file contents of: 

/catalog/controller/module/amazon_login.php

With: 

https://raw.githubusercontent.com/opencart/opencart/832707f0adc5695e1feb4ec40762eb2fbd493ba4/upload/catalog/controller/module/amazon_login.php

@chris-wm please confirm but there only seems to be the single file changed

**Comment by ngrices** [comment] 2015-05-18 22:06
@jamesallsup Is there a published release schedule?

**Comment by jamesallsup** [comment] 2015-05-19 08:15
@ngrices We aim to have the release done later today and then available for public download in 1 week to allow for developers to test against the new release.

**Comment by chrisfrenchindy** [comment] 2016-02-29 18:19
I'm receiving an error logging message with the Login with Amazon button. And for some reason, when I try to use it in sandbox mode, the login to my Amazon account fails everytime. Attached a screenshot of the error logging messages (there is not error message, just the label appear).

![screenshot 2016-02-29 at 1 16 42 pm](https://cloud.githubusercontent.com/assets/17553016/13404230/ba156668-dee6-11e5-9917-1c704d068ea0.png)

**Comment by fewleh** [comment] 2016-05-19 11:44
Chrisfrenchindy, did you ever get to the bottom of that issue? I have the same.

**Comment by chris-wm** [comment] 2016-05-19 14:13
@chrisfrenchindy @fewleh Hi, these are actually just labels in case there is any debug code. If there is an actual issue from Amazon then the debug code will appear below the respective label. For obvious reasons these only display in Sandbox mode and they do not signify that there is an issue with your installation unless code appears below them,
regards

**Comment by robteeshirtguy** [comment] 2016-07-21 15:18
HI everyone how can i fix this im not getting the login wih amazon button showing up all i get the the debug error code:
debug error message
showing nothing else i turned my theme off and it still does this on the defalt them and i turn all modules off and modification off and cleared catch opencart version 2.0.3.1

**Comment by chris-wm** [comment] 2016-07-22 14:17
@robteeshirtguy Hi, there are some possible causes for this: the module must be displayed on a page using HTTPS, the merchant details do not match the market place, the modules have not been added to the layout. If all of these are done correctly on your system then please raise a ticket on our [support site](https://help.welfordmedia.co.uk) and we can have a look,
regards
