### ISSUE TITLE
Paypal Payflow Pro declining in test mode

### ISSUE THREAD

**Issue by AndrewECooper** [opencart/opencart#5875] opened 2017-08-15 12:59 UTC
Hi.  I've enabled Payflow Pro in OpenCart and set it to test mode.  After going through the check out process, I get an alert saying "Warning: This transaction has been declined. Please try again.".  I've double checked all the information and it is accurate.  

Here's my issue.  There's no log or record that I can find that tells me why the card has been declined.  How do I troubleshoot the issue with no information.  Surely there should be something in the Admin section that tells me what specifically went wrong.  

Also, what is a Card Valid From Date?  The card doesn't have this information and I've never needed this to checkout before.

Andrew

![error](https://user-images.githubusercontent.com/1143458/29317213-da22f37a-8198-11e7-89b8-27ee413d7c4e.png)

**Comment by AndrewECooper** [comment] 2017-08-15 13:27
I've since realized that Paypal has specific card numbers that need to be used in Test Mode.  Chalk that up to my inexperience with working with payment gateways.  However, now that I'm using the required card number I'm still getting an error.  "Warning: A general problem has occurred with the transaction. Please try again."

I find this error rather unhelpful and I still can't find a log or anything with more details.

**Comment by jamesallsup** [comment] 2018-01-04 04:18
Commit comments: 

Payflow Pro gateway is now legacy but docs are still maintained at PayPal. Module was built years ago, long before my time.

As per issue #5875 - start date was being passed yet it is not even part of the PayPal NVPs so is most likely the cause of a constant fail transaction. Unable to obtain test info for this system as it is older but these updates can also port backwards if needed (depending how far back the mistake goes and who did it).

The pp payflow iframe controller also contained multiple incorrect config references (referencing the pp pro iframe module) - so again this would not have worked as expected either.

Both modules should now be resolved with unable to test without credentials. Please re-open with log info if continues. PayPal technical support will also be able to offer advice as to the cause of transactions not going through - as it could also be related to the account setup/config.

Close #5875

**Closed** 2018-01-04 04:17 UTC
