### ISSUE TITLE
What is missing? Page does not load full layout

### ISSUE THREAD

**Issue by MMFFCC** [opencart/opencart#7178] opened 2019-02-14 04:13 UTC
Hi guys,

I am not a developer, am still trying to learn how to build sites.

MY two sites were infected and damaged when I made the horrible mistake of hosting them at godaddy.

After a long battle I was able to put them online, but something is missing, the layout is just not there.

Please take a look and let me know?

Tks

www.cestasdenatal.net (this one also does not load the admin)

www.sacarolhas.com.br

**Comment by underr-ua** [comment] 2019-02-14 10:17
Hi @MMFFCC,
there is [OpenCart Community Forum](https://forum.opencart.com/) for these purposes.

**Comment by MMFFCC** [comment] 2019-02-14 19:40
ok, tks for letting me know.

but it seems to me you are saying I did something wrong.

And yet, we are right here on a page that reads opencart (https://github.com/opencart), so what exactly was my mistake?

tks again

**Comment by underr-ua** [comment] 2019-02-14 20:11
This is a normal practice - to use an issue tracker for bug report. But until you have confidence it’s a bug of OpenCart, it’s a question, not a bug report. Ask in forum, and if it seems bug after discussion, file a bug report to issue tracker.

**Comment by straightlight** [comment] 2019-07-16 14:13
Closure notes: Forum question. Closing commit.

**Closed by straightlight** 2019-07-16 14:13 UTC
