### ISSUE TITLE
Opencart Minimum order checkout

### ISSUE THREAD

**Issue by bhargavmehta** [opencart/opencart#3089] opened 2015-06-07 11:28 UTC
Hi,
I want to set minimum order amount in my cart for checkout . How can this be done ?
Also If there is no in built functionality then it should be added as this is an important functionality.
Thanks

**Comment by milimar** [comment] 2015-06-07 14:02
Go to Catalog - product, click to edit the product you want to set a min. order amount, click on the Data tab and find the option Minimum Quantity. Hope this help, but you should know that this is not a place for asking for help, this is a bug tracker. Next time ask questions on the forum of OC 

http://forum.opencart.com/

Greetings

**Comment by bhargavmehta** [comment] 2015-06-07 14:27
I was asking for minimum cart order total.
I want to set the minimum total for cart which should be allowed for checkout.
In magento that is given Out of the box functionality. Thats why I am thinking that it will be here too.

**Comment by mhcwebdesign** [comment] 2015-06-07 16:52
This is not a bug report, rather a feature request, expect Daniel to close this issue soon.

**Closed** 2015-06-13 19:13 UTC
