### ISSUE TITLE
Extensions > Order Totals > Sub-Total > Sort order not working!

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#9472] opened 2021-03-22 10:02 UTC
Platform:
OpenCart v3.0.3.2

Navigation:
Extensions > Extensions > Order Totals > Sub-Total > Sort order

Description:
Sort order for Sub-Total not working! It doesn't display. It not show the sort order number.

DEMO:
https://demo.opencart.com/admin/index.php?route=marketplace/extension

Thank you!

**Comment by mhcwebdesign** [comment] 2021-03-22 10:34
What sort order exactly is broken, for what order total? I am unable to reproduce your error.

**Comment by faca5** [comment] 2021-03-22 10:37
Please check DEMO.

Sort order not appear on the list. You can put 1,2, 3 etc.. for Sub-Total. Never appear.

**Comment by danijelGombac** [comment] 2021-03-22 10:49
Open admin/view/template/extension/total/sub_total.twig

and change "sub_total_sort_order" to "total_sub_total_sort_order"

**Comment by mhcwebdesign** [comment] 2021-03-22 10:56
Thanks, yes, @danijelGombac is right. I noticed the same bug in later OC 3.0.x releases, too. But it is now fixed in the OC 3.0.x maintenance branch and the OC4 master branch.

**Closed** 2021-03-22 10:58 UTC
