### ISSUE TITLE
Cannot remove postal code requirement for certain countries

### ISSUE THREAD

**Issue by igbanam** [opencart/opencart#4683] opened 2016-07-19 15:21 UTC
I installed version 2.2.0; and I saw in a tutorial  that to remove the requirement for postal code is in System -> Localization -> Countries. 

After turning the Postal Code requirement off, I realized the postal code still stays required when an unregistered customer tries to register through the checkout process. If the registration is attempted through the link on the toolbar, this requirement is appropriately not required; however, this is the only page which it obeys that rule.

**Comment by CoverUp** [comment] 2016-07-19 17:23
nice catch, i have fixed the problem, but i cant make a pull request, because now all templates are using twig, so is 2.3 version for now on. So i got to first check if the problem has been inherited or not in order to make the fixes in the new version... that's mean that i have to upgrade from 2.2 to 2.3 in first place.
Anyway, the solution to the problem is
catalog/view/theme/default/template/checkout/register.tpl
lines 457 to 464
replace with
success: function(json) {
			if (json['postcode_required'] == '1') {
				$('#collapse-payment-address input[name=\'postcode\']').parent().addClass('required');
			} else {
				$('#collapse-payment-address input[name=\'postcode\']').parent().removeClass('required');
			}
html = '<option value=""><?php echo $text_select; ?></option>';

regards

**Comment by CoverUp** [comment] 2016-07-19 17:36
ok problem still persist on 2.3 so it fixed on https://github.com/opencart/opencart/pull/4684

**Comment by danielkerr** [comment] 2016-07-20 04:18
u can commit to the master still.

**Comment by CoverUp** [comment] 2016-07-20 05:12
I have committed on master and now on dev too, I was surprised that the master use twig templates too

**Comment by igravity** [comment] 2016-07-20 09:41
Oh this is good! Thanks

:dancer:

**Comment by danielkerr** [comment] 2016-07-21 08:55
twig got accidentally added to the master. should be removed now.

**Comment by CoverUp** [comment] 2016-07-21 21:29
ok now is pulled again to the non-twig version

**Comment by danielkerr** [comment] 2017-05-06 12:37
already fixed in dev branch

**Closed by danielkerr** 2017-05-06 12:37 UTC
