### ISSUE TITLE
getting http error 500 while product add

### ISSUE THREAD

**Issue by kg0925** [opencart/opencart#7161] opened 2019-01-27 10:14 UTC
**What version of OpenCart are you reporting this for?**
3.0.3.1

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
when ever i try to add product. fill out all product details on product form and hit save button it gives http 500 error.  

**To Reproduce**
1. Go to catelog in opencart admin click on products 
2. Click on add new product
3. fill out all product info and hit save button 
4. See error http 500  

**Expected behavior**
it should redirect to products page after saved rather than giving http 500 error

**Server / Test environment (please complete the following information):**
 - hosted on A2hosting
 - Operating system  linux
 - PHP version  7.0
 - Apache version  2.4.37
- Browser(s) tested with chrome
 - Version 71

**Comment by kg0925** [comment] 2019-01-27 11:49
ad blocker is already disabled on my website. without ad blocker it's
showing http 500 error

**Comment by danielkerr** [comment] 2019-01-27 13:57
ok email your login details to support@opencart.zendesk.com ill get my support guy to have a look

**Comment by danielkerr** [comment] 2019-01-27 13:59
actual;ly i just thought what it w ould be. if you have error reporting turned off and their is an error in the background it would just do a 500. check if error reporting is turned off and turn it on. then try again. check the error log to see what errors are coming up.

**Comment by kg0925** [comment] 2019-01-27 16:57
error logs are already enabled in opencart settings. i have shared login
details to support@opencart.zendesk.com  please have look in to.

**Comment by kg0925** [comment] 2019-01-28 04:55
hello, actually you may be right it's error for error logs. in opencart
settings error logs are already enabled. but there is no error at system >
maintenance > error logs.  usually i get 2-3 errors every day related
caching in error logs while i had OC 3.0.2.0. but since I installed latest
version there is no error shown. that means it's not logging the errors to
text file. i manually check error_log text file in public_html folder of my
website. i found 2 error there

[24-Jan-2019 18:38:40 UTC] PHP Fatal error:  Class 'mysqli' not found in
/home/myusername/public_html/system/library/db/mysqli.php on line 7
[24-Jan-2019 18:38:40 UTC] PHP Fatal error:  Class 'mysqli' not found in
/home/myusername/public_html/system/library/db/mysqli.php on line 7

i have installed OC 3.0.3.1 at 24th jan and error date is also 24th. till
that date http 500 error comes while saving products. product getting added
successfully to database but after hit on save button. it gives http 500
error.

**Comment by osworx** [comment] 2019-01-28 15:31
Seems to be that here: https://github.com/opencart/opencart/issues/7133

**Comment by danielkerr** [comment] 2019-01-29 07:30
pretty big issue. 

uninstall the google advertising. will do an update.

**Comment by kg0925** [comment] 2019-01-29 07:38
google advertising making this issue??  how much time it will take to
resolve this issue. if it will take so long then i would like to downgrade
opencart to 3.0.2.0 version again.

**Comment by danielkerr** [comment] 2019-01-29 08:12
its a simple fix.

https://github.com/Arthom/opencart/commit/0f4f4b0289de909a0750dc1f12e420e9b617c6b9b9

osworx has posted what you need to do to fix your store.

https://github.com/opencart/opencart/issues/7133#issuecomment-458217940

**Comment by danielkerr** [comment] 2019-01-29 13:10
ok will do an update before friday.

**Comment by kg0925** [comment] 2019-01-30 15:45
i just got this error while product add

Fatal error: Uncaught Exception: Error: Duplicate entry '0' for key
'PRIMARY'<br />Error No: 1062<br />INSERT INTO
`fd_product_advertise_google` (`product_id`, `store_id`,
`google_product_category`) SELECT p.product_id, p2s.store_id, (SELECT
c2gpc.google_product_category FROM `fd_product_to_category` p2c LEFT JOIN
`fd_category_path` cp ON (p2c.category_id = cp.category_id) LEFT JOIN
`fd_category_to_google_product_category` c2gpc ON (c2gpc.category_id =
cp.path_id AND c2gpc.store_id = 0) WHERE p2c.product_id = p.product_id AND
c2gpc.google_product_category IS NOT NULL ORDER BY cp.level DESC LIMIT 0,1)
as `google_product_category` FROM `fd_product` p LEFT JOIN
`fd_product_to_store` p2s ON (p2s.product_id = p.product_id AND
p2s.store_id = 0) LEFT JOIN `fd_product_advertise_google` pag ON
(pag.product_id = p.product_id AND pag.store_id=p2s.store_id) WHERE
pag.product_id IS NULL AND p2s.store_id IS NOT NULL AND p.product_id IN
(4296) in /home/fashio42/public_html/system/library/db/mysqli.php:40 Stack
trace: #0 /home/fashio42/p in
/home/fashio42/public_html/system/library/db/mysqli.php on line 40

**Comment by osworx** [comment] 2019-01-30 16:01
@kg0925 Sorry, but are you able to read (the comments above)?
Before posting the same again .. !?
Simply follow this here: https://github.com/opencart/opencart/issues/7161#issuecomment-458446135

**Comment by ankit9808** [comment] 2019-01-31 16:06
Duplicate of #

**Comment by ankit9808** [comment] 2019-01-31 16:06
just run the below SQL query and everything will be fine.

> `ALTER TABLE `oc_product_advertise_google` CHANGE `product_advertise_google_id` `product_advertise_google_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;`

This query will Modify the oc_product_advertise_google Table and add  AUTO_INCREMENT property to this table which solves the issue of duplicate row.

**Comment by Mike-the-one** [comment] 2019-02-18 11:02
Since the product is added successfully without fixing this, I have added 60+ products without fixing the db, I fixed the problem now, so uninstall google advertising and reinstall it should re-add all the products back to this table?  Do I need to fix other things?

**Comment by webkul-dilip** [comment] 2020-12-29 05:14
Please close this issue, The issue was related to other module and issue does not found in the maintenance-branch 3.0.x branch.

**Closed** 2020-12-29 05:27 UTC
Labels: maintenance-branch 3.0.x.x
