### ISSUE TITLE
Options get overwritten with the first default when reloading edit product page

### ISSUE THREAD

**Issue by stitch** [opencart/opencart#8196] opened 2020-08-09 13:26 UTC
**What version of OpenCart are you reporting this for?**
Version 3.0.3.2
Change log shows nothing about any updates regarding my issue, so updating was not needed.

**Describe the bug**
Options get overwritten with the first value when using the back button and reloading a page. This effectively overwrites all options in the product (invisibly when you're editing some other data). Then clicking save will overwrite product options with the values that you did not edit, but where filled in by the system (the first value of the list).

**To Reproduce**
1: Click the blue pen on the edit page, to start editing a product.
2: Go to the product options.
3: Set the option values to something you like: small, medium, large for example.
4: Click the save icon at the top of the page
5: Hit the back button in the browser, to continue editing (i'm not going to search though pages to find the product to edit another detail, of course: saving should never leave the product page!)
6: Hit control + R to reload to page, so you're sure your data is up to date and not some cached value from your previous edits.
7: Go to the options page.
8: See that the option sections on the left have possibly switched place, and that all the size options are set to the first option (small).
9: Hit save, because you didn't see that the options have changed, as you're working another detail.
10: Discover that the options have been adjusted without your interaction in your shop.
11: Receive several complaints and impossible orders (=more complaints)

**Expected behavior**
1: Using the back button and reloading a product page to edit it should just work. It should retrieve the options as they are. Not silently overwriting them.
2: Do not go to the product list after saving. There are so many options, and i want to have 50 tabs open with products to edit.

**Screenshots / Screen recordings**
In the movie you'll see the cursor go to the back button. After the previous page shows, i'm hitting contol+r to make sure i've got the latest data. At that point, all options are basically gone, values are reset and so forth.

https://5717.ch/public/opencart_override_options.mov

**Server / Test environment (please complete the following information):**
 - Production system
 - Firefox browser
 - Mac OS

**Additional context**
Working with options is generally cumbersome. Why is there no possibility to copy options from another product? Why is there no possibility to have a predefined shared set of options?
Working with products is also cumbersome: after saving i want to continue editing. I don't want to go to the product list to search for the product again to edit another detail.
Product link suggestions are also terrible, as matching happens on the start of the name of a product, not on a wildcard (i can understand performance issues on larger shops).

PS: i'm sorry, i'm coming off as cranky. This is the first experience with opencart, and was generally expecting not to run into bugs of this type. I mean: the product is 10+ years old and the browser back button / reloading pages is basic stuff. I wanted to focus on getting my designs in a store, not spending a couple of hours reporting this bug. I'm reporting it because i genuinely believe that this is a nice product and many hours have been spent on making it work great! I don't want anyone else experience the same problems!

**Comment by ADDCreative** [comment] 2020-08-09 17:32
I think this is caused by a firefox feature. I couldn't recreate in Chrome or Firefox 68.11.0esr, only Firefox 80.0b5. It seems that Firefox preserves the selected form elements on a refresh (F5), but not a hard refresh (Control+F5).

The problem arises when the product page is reloaded, the options are in a different order. Firefox will then set select options from its cache not accounting for the different order.

The was a comment here that sorted the options that may help as long as all you options have unique sort orders.
https://github.com/opencart/opencart/pull/7941

**Comment by WebkulOpencart** [comment] 2020-12-28 05:48
This issue is not related to the OpenCart so closing the same.

**Closed by WebkulOpencart** 2020-12-28 05:48 UTC
Labels: maintenance-branch 3.0.x.x
