### ISSUE TITLE
OC4 - PHP8 url.php

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#9399] opened 2021-03-02 19:39 UTC
TypeError: Opencart\System\Library\Url::addRewrite(): Argument #1 ($rewrite) must be of type string, Opencart\Catalog\Controller\Startup\SeoUrl given, called in\catalog\controller\startup\seo_url.php on line 7 in \system\library\url.php on line 36

https://github.com/opencart/opencart/blob/557d9e810f4f3a9774f028df5ac3022ddf90aa03/upload/catalog/controller/startup/seo_url.php#L7

https://github.com/opencart/opencart/blob/557d9e810f4f3a9774f028df5ac3022ddf90aa03/upload/system/library/url.php#L36

**Comment by TheCartpenter** [comment] 2021-03-03 13:32
```public function addRewrite(string $rewrite): void { ```

to:

```public function addRewrite(string $rewrite): string {```

Does that solve the issue?

**Comment by stalker780** [comment] 2021-03-03 13:36
No. Don't you see by quoted code lines? Problem is not in returned type.

**Comment by TheCartpenter** [comment] 2021-03-03 13:39
Then, the issue is with $this being parametered as this is an object and not a string.

**Comment by TheCartpenter** [comment] 2021-03-03 13:41
Perhaps:

```public function addRewrite(string $rewrite): void {```

to:

```public function addRewrite(object $rewrite): object {```

**Comment by mhcwebdesign** [comment] 2021-03-15 12:39
Or perhaps this:

`public function addRewrite(Opencart\System\Engine\Controller $rewrite): void {`

**Comment by mhcwebdesign** [comment] 2021-03-21 15:36
Changed the argument type to Opencart\System\Engine\Controller, see above. Please test it again before closing this issue. 

Works fine on my own Linux test server.

**Comment by SaifAlSubhi** [comment] 2021-03-21 16:15
@mhcwebdesign
I put "Use SEO URLs" back to "Yes" in admin setting and this subject error is fixed now.

**Comment by stalker780** [comment] 2021-03-21 22:57
> 
> 
> Or perhaps this:
> 
> `public function addRewrite(Opencart\System\Engine\Controller $rewrite): void {`

This issue is fine in latest master. I think it can be closed now.

Now waiting for these seo_url fixes #9468, #9469

**Comment by danielkerr** [comment] 2021-03-22 08:32
you can do string|null

**Closed** 2021-11-06 11:15 UTC
Labels: master-branch
