### ISSUE TITLE
[Any Version Of OpenCart] G2APay Module Is Not Working (Redirects To Payment Faliure)

### ISSUE THREAD

**Issue by Galliger** [opencart/opencart#6125] opened 2017-10-22 06:11 UTC
Hello I recently setup G2APay on my opencart and configured it by entering my API key and email, I have double checked that they are correct and I know that they are.

But no matter what I do when I go to checkout a product I just get redirected to http://www.example.com/products/index.php?route=extension/payment/failure

**1. As soon as I press confirm order here it will redirect me to page not found**
![1](https://user-images.githubusercontent.com/32995189/31858796-55214c4a-b6f8-11e7-88a3-6774f1e9f1cc.PNG)

**2. This is the page it redirects me to, when I want it to open G2APay and let the user purchase the product, what is wrong with it?**
![2](https://user-images.githubusercontent.com/32995189/31858775-f86a280a-b6f7-11e7-848d-75522acb25d3.PNG)

I am currently using opencart 2.3.0.2 so I can use other extensions built for that version, but I have tried the latest version off the website and I have the exact same issue!

Something is wrong with OpenCart as I have configured it correctly!

EDIT:
**Here is my configuration for the G2A extension with any private information hidden:**
![capture](https://user-images.githubusercontent.com/32995189/31858829-0873d9d4-b6f9-11e7-8b19-187b417273f6.PNG)

EDIT2:
Here is my log file that I have tested purchasing a product on (I have hidden private information):
```
2017-10-20 3:08:42 - Origin: Action::execute
2017-10-20 3:08:42 - 7.63
2017-10-20 3:08:42 - Origin: Action::execute
2017-10-20 3:08:42 - Array
(
    [0] => stdClass Object
        (
            [sku] => 51
            [name] => HIDDEN
            [amount] => 7.63
            [qty] => 7
            [id] => 51
            [price] => 1.0900
            [url] => http://HIDDEN/products/index.php?route=product/product&amp;product_id=51
        )

)

2017-10-20 3:08:42 - Origin: Action::execute
2017-10-20 3:08:42 - Array
(
    [api_hash] => 50e948HIDDENa9608dc
    [hash] => 962c3HIDDENe5f5768HIDDEN24c091240921HIDDEN75ea7aa
    [order_id] => 20
    [amount] => 7.63
    [currency] => USD
    [email] => test@test.com
    [url_failure] => http://HIDDEN/products/index.php?route=checkout/failure
    [url_ok] => http://HIDDEN/products/index.php?route=extension/payment/g2apay/success
    [items] => [{"sku":"51","name":"HIDDEN","amount":7.630000000000001,"qty":"7","id":"51","price":"1.0900","url":"http:\/\/HIDDEN\/products\/index.php?route=product\/product&amp;product_id=51"}]
)
```

**I really hope that this problem gets sorted soon as I would very much like to use G2A in my opencart store!**

**Comment by Galliger** [comment] 2017-10-22 06:21
EDIT2:
Here is my log file that I have tested purchasing a product on (I have hidden private information):
```
2017-10-20 3:08:42 - Origin: Action::execute
2017-10-20 3:08:42 - 7.63
2017-10-20 3:08:42 - Origin: Action::execute
2017-10-20 3:08:42 - Array
(
    [0] => stdClass Object
        (
            [sku] => 51
            [name] => Old School Runescape Gold (1m)
            [amount] => 7.63
            [qty] => 7
            [id] => 51
            [price] => 1.0900
            [url] => http://HIDDEN/products/index.php?route=product/product&amp;product_id=51
        )

)

2017-10-20 3:08:42 - Origin: Action::execute
2017-10-20 3:08:42 - Array
(
    [api_hash] => 50e948HIDDENa9608dc
    [hash] => 962c3HIDDENe5f5768HIDDEN24c091240921HIDDEN75ea7aa
    [order_id] => 20
    [amount] => 7.63
    [currency] => USD
    [email] => test@test.com
    [url_failure] => http://HIDDEN/products/index.php?route=checkout/failure
    [url_ok] => http://HIDDEN/products/index.php?route=extension/payment/g2apay/success
    [items] => [{"sku":"51","name":"HIDDEN","amount":7.630000000000001,"qty":"7","id":"51","price":"1.0900","url":"http:\/\/HIDDEN\/products\/index.php?route=product\/product&amp;product_id=51"}]
)
```

**Comment by straightlight** [comment] 2017-10-22 19:50
Followed are recent updates to the G2APay payment module on the admin-end:

-
 https://github.com/opencart/opencart/blob/master/upload/admin/controller/extension/payment/g2apay.php
-
 https://github.com/opencart/opencart/blob/master/upload/admin/view/template/extension/payment/g2apay.twig
-
 https://github.com/opencart/opencart/blob/master/upload/admin/view/template/extension/payment/g2apay_order.twig

You may have to uninstall the payment module before making these changes and then reinstall. It woul be recommended to take screenshots of your current G2APay module form under the admin.

**Comment by Galliger** [comment] 2017-10-22 20:00
How do I fix the problem exactly, like I say I have used the latest version of OpenCart and the payment module does not work and simply redirects me to http://www.example.com/products/index.php?route=extension/payment/failure

How exactly do I fix the problem so the G2A module works and allows the user to pay?

**Comment by straightlight** [comment] 2017-10-22 20:02
The latest version of Opencart ZIP file was published prior to the modification dates of the links that have been provided above. As for the instructions ... they are ... right at the bottom of my last post above ...

**Comment by Galliger** [comment] 2017-10-22 20:11
I will reinstall with these changes from GitHub and let you know if it's now working!

**Comment by Galliger** [comment] 2017-10-22 20:27
![2](https://user-images.githubusercontent.com/32995189/31865978-ca7b1ce2-b76f-11e7-9f15-820268bea101.PNG)

![capture](https://user-images.githubusercontent.com/32995189/31865958-85ce7d50-b76f-11e7-8a24-acba12026b01.PNG)
Still not working? I had tried it on the latest version before but it didn't work?

I litrelly just made a fresh install from the latest version that you sent me on GitHub and set it up on my local server, but as soon as I select G2A it just takes me to the page not found section?

**Comment by straightlight** [comment] 2017-10-22 20:42
Bug confirmed. Please try this solution here to rectify the problem: https://forum.opencart.com/viewtopic.php?f=201&t=198902

**Comment by Galliger** [comment] 2017-10-22 21:06
![capture](https://user-images.githubusercontent.com/32995189/31866268-12410d70-b775-11e7-9452-f70d0c2d85ea.PNG)
It still doesn't redirect me to pay and nothing at all seems to have changed after adding this fix that you made? I really need to get this working and would be so grateful if you could get it working!

**Comment by Galliger** [comment] 2017-10-22 21:12
Why won't this redirect users to the G2A page in order to make payment (And I don't see how the bug fix you gave me would have fixed that, it looks like it would have just gave me a different error message?)

Could you please help me out here! Why is G2APay not redirecting to the payment page upon order?

**Comment by straightlight** [comment] 2017-10-22 21:27
The failure() method was missing in that controller file in order to properly work. It won't redirect to the G2APay due to a failed payment. If you look at the URL on your browser, it targets the extension/payment/failure/ which is an invalid link but the failure method was also missing for merchants who would like to forward the customers back to checkout upon failed payments.

However, I have also updated the post on the forum for an additional step to be applied. Customers failing the payment should rather be redirected to the checkout/failure route. This has now been fixed.

**Comment by Galliger** [comment] 2017-10-22 21:29
Why have I failed the payment though I do not understand buddy, why is it not redirecting me to G2APay in order for me to make a payment.

I enabled debugging as I put it in my original post but it does not say why the payment failed?

Why will it not redirect me?

**Comment by straightlight** [comment] 2017-10-22 21:38
The debug you are using is only from inside the store. It does not provide the G2APay response upon payment activities. However, since your enquiry above is not about an official bug yet, please post in the topic I created in order to troubleshoot this issue further until noticing if this is an actual bug.

**Comment by Galliger** [comment] 2017-10-22 21:41
![capture](https://user-images.githubusercontent.com/32995189/31866596-01734cec-b77a-11e7-94e0-2bb69f4f8720.PNG)
What you did fixed the page not found error sir!

But it's still not redirecting me to the payment?

**Comment by straightlight** [comment] 2017-10-22 21:43
The page not found error was originating from Opencart itself which the link has now been pointing to the right direction upon failures. However, what you are reporting has now been coded yet in order to track the response data from G2APay activities when sending a payment which is not yet considered a bug but further troubleshooting. This section on Github is not meant for troubleshooting issues in details but simply to report a more accurate bug.

**Comment by Galliger** [comment] 2017-10-22 21:55
Are you telling me that there is no way for it to redirect to the G2APay website to make a payment?

That has not been coded in?

**Comment by straightlight** [comment] 2017-10-22 21:56
It just did. I provided the instructions on the addressed topic. Please follow these instructions.

**Comment by Galliger** [comment] 2017-10-22 22:05
What I am wanting it to do is go to the G2APay page so a user can then make the payment.

This is the bug I am reporting, it will not go to the G2APay page for the user to make a payment?

Why is this?

**Comment by straightlight** [comment] 2017-10-22 22:07
Please test these instructions in order to obtain an accurate solution to this problem.

**Comment by Galliger** [comment] 2017-10-22 22:08
Which instructions are you referring to friend?

**Comment by straightlight** [comment] 2017-10-22 22:13
https://forum.opencart.com/viewtopic.php?f=201&t=198902

**Comment by Galliger** [comment] 2017-10-22 22:47
It will not create any debug file with the additional options you gave me?

In fact it made no debug file at all? (Yes, I enabled it in the settings)

**Comment by Galliger** [comment] 2017-10-22 22:49
```
2017-10-22 22:41:46 - Response data: 1
2017-10-22 22:41:46 - Origin: Action::execute
2017-10-22 22:41:46 - 240.00
2017-10-22 22:41:46 - Origin: Action::execute
2017-10-22 22:41:46 - Array
(
    [0] => stdClass Object
        (
            [sku] => 30
            [name] => Canon EOS 5D
            [amount] => 240
            [qty] => 3
            [id] => 30
            [price] => 80.0000
            [url] => http://localhost/index.php?route=product/product&amp;product_id=30
        )

)

2017-10-22 22:41:46 - Origin: Action::execute
2017-10-22 22:41:46 - Array
(
    [api_hash] => HIDDEN
    [hash] => b6f3677742a3de85ea2990c789b9522cb531f58076bbe813a875187b9d137d74
    [order_id] => 9
    [amount] => 240.00
    [currency] => USD
    [email] => test@test.com
    [url_failure] => http://localhost/index.php?route=checkout/failure
    [url_ok] => http://localhost/index.php?route=extension/payment/g2apay/success
    [items] => [{"sku":"30","name":"Canon EOS 5D","amount":240,"qty":"3","id":"30","price":"80.0000","url":"http:\/\/localhost\/index.php?route=product\/product&amp;product_id=30"}]
)

2017-10-22 22:42:22 - Response data: 1
2017-10-22 22:42:22 - Origin: Action::execute
2017-10-22 22:42:22 - 240.00
2017-10-22 22:42:22 - Origin: Action::execute
2017-10-22 22:42:22 - Array
(
    [0] => stdClass Object
        (
            [sku] => 30
            [name] => Canon EOS 5D
            [amount] => 240
            [qty] => 3
            [id] => 30
            [price] => 80.0000
            [url] => http://localhost/index.php?route=product/product&amp;product_id=30
        )

)

2017-10-22 22:42:22 - Origin: Action::execute
2017-10-22 22:42:22 - Array
(
    [api_hash] => HIDDEN
    [hash] => 04225f1e53bc2a9214efb41d928c0d171396eeb10bc9fde76180420156596402
    [order_id] => 10
    [amount] => 240.00
    [currency] => USD
    [email] => test@test.com
    [url_failure] => http://localhost/index.php?route=checkout/failure
    [url_ok] => http://localhost/index.php?route=extension/payment/g2apay/success
    [items] => [{"sku":"30","name":"Canon EOS 5D","amount":240,"qty":"3","id":"30","price":"80.0000","url":"http:\/\/localhost\/index.php?route=product\/product&amp;product_id=30"}]
)

2017-10-22 22:44:55 - Response data: 1
2017-10-22 22:44:55 - Origin: Action::execute
2017-10-22 22:44:55 - 240.00
2017-10-22 22:44:55 - Origin: Action::execute
2017-10-22 22:44:55 - Array
(
    [0] => stdClass Object
        (
            [sku] => 30
            [name] => Canon EOS 5D
            [amount] => 240
            [qty] => 3
            [id] => 30
            [price] => 80.0000
            [url] => http://localhost/index.php?route=product/product&amp;product_id=30
        )

)

2017-10-22 22:44:55 - Origin: Action::execute
2017-10-22 22:44:55 - Array
(
    [api_hash] => HIDDEN
    [hash] => HIDDEN
    [order_id] => 11
    [amount] => 240.00
    [currency] => USD
    [email] => test@test.com
    [url_failure] => http://localhost/index.php?route=checkout/failure
    [url_ok] => http://localhost/index.php?route=extension/payment/g2apay/success
    [items] => [{"sku":"30","name":"Canon EOS 5D","amount":240,"qty":"3","id":"30","price":"80.0000","url":"http:\/\/localhost\/index.php?route=product\/product&amp;product_id=30"}]
)


```

**Comment by Galliger** [comment] 2017-10-22 22:50
I added this debug code to get server data from G2A, but my log file has not changed?

**Comment by straightlight** [comment] 2017-10-22 23:15
The issue is on your end regarding the 'amount' and the 'price' field. They are unbalanced. The debug above with my code above is working perfectly.

**Comment by straightlight** [comment] 2017-10-22 23:20
In the mean time, localhost surely won't work ... is it a renamed URL or the actual URL?

**Comment by straightlight** [comment] 2017-10-22 23:24
Another issue i just noticed from the debug above is that the status and token field aren't there which is why the payment cannot be completed ...

**Comment by Galliger** [comment] 2017-10-22 23:28
Why aren't the status and token fields there?

**Comment by Galliger** [comment] 2017-10-22 23:28
I just want it to work? Why will it not redirect to the G2APay website and start the payment

**Comment by Galliger** [comment] 2017-10-22 23:29
How do I get the status and token field to appear?

**Comment by straightlight** [comment] 2017-10-22 23:34
For now, the solution is still on pending mode. As soon as a fix will be found, it will be posted either on the forum or on Github.

**Comment by Galliger** [comment] 2017-10-22 23:36
Why won't it generate the token for the product and then redirect the customer to the G2APay page?

**Is there any way you could make a quick fix for this? Instead of me having to wait a while! (It would be great to get this sorted ASAP)**

**Comment by straightlight** [comment] 2017-10-22 23:44
Depending. If you are truly not using a localhost address to make a payment, then we'll just have to wait for a solution on this one.

**Comment by straightlight** [comment] 2017-10-23 02:43
From the error logs, this is what I have captured in the mean time to clarify the cause: PHP Notice: Trying to get property of non-object in catalog/controller/extension/payment/g2apay.php on line 108 (which is the status property that is missing as well as the token).

**Comment by Galliger** [comment] 2017-10-23 03:29
Is there any way to fix it? How long does it take for this to be fixed?

**Comment by Galliger** [comment] 2017-10-23 03:42
Why exactly isn't the token being created?

**Comment by Galliger** [comment] 2017-10-23 04:04
I have tried this on many different versions of OpenCart and it doesn't seem to work on any of them?
https://forum.opencart.com/viewtopic.php?f=185&t=173101&p=656053&hilit=G2A#p656053

If I check that forum topic someone managed to get it to work on OpenCart 2.2 but after installing that and removing any fees. it still did not work at all and just went to page not found?

I really need to get G2A working and I am really hoping someone can help me!

**Comment by danielkerr** [comment] 2018-01-04 17:25
try the master version. the fix is already added. it will be in the next release. also gtapay was working at some poiunt otherwise it would not be in the core.

**Closed** 2018-01-04 17:24 UTC

**Comment by gluzio** [comment] 2018-11-15 15:39
Hi,

I get the same error on a fresh install:

Select G2A pay:
![image](https://user-images.githubusercontent.com/496735/48563453-50c7d700-e8ec-11e8-84ca-aad8b64c4f37.png)

Then when I hit confirm it errors:
![image](https://user-images.githubusercontent.com/496735/48563501-6c32e200-e8ec-11e8-8e47-5fb0b3816c75.png)

The page requested cannot be found!

Did you ever fix this issue?

Does G2A pay work?

Thanks.

**Comment by Ilianleboss** [comment] 2020-03-20 16:07
Le bug a été résolu ? ou pas car j'ai toujours ce bug!

**Comment by straightlight** [comment] 2020-03-20 16:13
Please post only in English on this namespace. As Daniel addressed on the above, the issue has already been fixed on the Master Branch.
