### ISSUE TITLE
“storage" folder have 777 permissions, but "shopping cart is empty"

### ISSUE THREAD

**Issue by ooshipin** [opencart/opencart#6492] opened 2018-03-27 11:27 UTC
OC version 3.1.0.0b ( OC master )
PHP version 7.0   + SQL
Problem:   " shopping cart is empty"
---------------------------------------------------------------------------
when  add 1 item to the shopping cart, got the notice: Success: You have added xxxxxx to your shopping cart!, but when I go to shopping cart page, there is nothing. (Your shopping cart is empty!)
------------------------------------------------------------------------------------
# ** the "storage" folder have 777 rights (all permissions), the detail path is "/home/ooshipi2/storage9/"**

**Comment by ooshipin** [comment] 2018-03-27 11:53
the Permissions is as below



![snap23](https://user-images.githubusercontent.com/37803368/37965557-0f8a4ddc-31f8-11e8-8e88-bb66b6df3e90.jpg)

**Comment by straightlight** [comment] 2018-03-27 12:17
Although, ensure to have followed these instructions: https://forum.opencart.com/viewtopic.php?f=176&p=718325#p717782 .

**Comment by ooshipin** [comment] 2018-03-27 13:14
Thanks for your reply
As you said, i reinstallation the OC-master (OC 3.1.0.0.b), and choose the manual set " storage" folder, the move the " storage" to "'/home/ooshipi2/storage/", and updated the config files , but it's still same problem...just like the below pictures.

![snap27](https://user-images.githubusercontent.com/37803368/37969464-650a52d8-3203-11e8-89f7-677287194378.jpg)

**Comment by straightlight** [comment] 2018-03-27 13:17
Did you also followed the instructions for the .htaccess file and clearing your OC cache by following this post: https://forum.opencart.com/viewtopic.php?f=176&p=718325#p718325 ?

**Comment by ooshipin** [comment] 2018-03-27 13:17
let's go on, then i did as below as you said in other "posts"..
-----------------------------------------------------------
Remove the entire line in your .htaccess where it says: ^system/storage . 
Set recursive permission settings to your storage folder. 
Clear all OC cache from your admin - > dashboard and from your admin - > extensions - > modifications - > refresh button.

but it still doesn't work....

**Comment by straightlight** [comment] 2018-03-27 13:19
Then, it's a server cache issue. Not an OC issue, so far. Please create a new topic on the forum for further testings.

**Comment by straightlight** [comment] 2018-03-27 13:29
See by replacing the system/library/cache folder from v3.0.3.0b to v3.0.2.0 files would help by also re-clearing your OC cache from the OC admin afterwards.

**Comment by ooshipin** [comment] 2018-03-27 13:30
Also i find no matter what i input in the "Qty", it also can submit successfully...

![snap28](https://user-images.githubusercontent.com/37803368/37970409-fe56a6d8-3205-11e8-89a1-50c8ca5a3300.jpg)

**Comment by ooshipin** [comment] 2018-03-27 13:35
Have tried , but doesn't work, maybe i should wait for your next version....
---------------------------------------------
See by replacing the system/library/cache folder from v3.0.3.0b to v3.0.2.0 files would help by also re-clearing your OC cache from the OC admin afterwards.

**Comment by ooshipin** [comment] 2018-03-27 13:36
But i really don't think it's only server cache issue, because i have checked the posts by other people, they also have the similar problem.....
------------
https://github.com/opencart/opencart/issues/6236

**Comment by straightlight** [comment] 2018-03-27 13:37
Contact site support on opencart.com or send me a PM on the forum for further investigation if no other solution can be posted on the topic.

**Comment by straightlight** [comment] 2018-03-27 13:45
Also just noticed the 3.0.3.0b release no longer uses the domain ownership to use the storage folder outside of the public_html folder. After replacing those files in the cache folder, what if you replace the storage folder inside the system folder and re-edit your config.php and admin/config.php files as well as re-adding the removed line from the .htaccess and re-clearing the cache from the OC admin, are you then able to properly use the cache?

**Comment by ooshipin** [comment] 2018-03-27 14:20
reinstall again ...change the "storage folder" to "/home/ooshipi2/public_html/storage/"... and reset the config.php files,    clear the cache..... but it still doesn't matter..

may i know when you will release the new version?

thanks for your help

**Comment by straightlight** [comment] 2018-03-27 16:05
While I may not be the creator of Opencart, there are no definite date for the next release. Although, pleae post these types of question on the forum. Github issues tab is only for development / bug reporting subjects.

**Comment by lucasjkr** [comment] 2018-03-27 16:24
@ooshipin - the problem is you're trying to use beta software (the b at the end of the version). It will never get fixed in the version you're using - beta's are released specifically for people to find bugs in, not run production websites on. As you said, it has been fixed in the current release. Better to use that and wait a little for Amazon Pay support.

Also, shopping carts aren't stored in the storage directory... They're in the database.

**Comment by danielkerr** [comment] 2018-03-28 00:32
All files and foldrs need to be chmod 777

**Closed** 2018-03-28 00:32 UTC
