### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by Edward0625** [opencart/opencart#10270] opened 2021-11-20 07:17 UTC
**What version of OpenCart are you reporting this for?**
Version 3.0.3.8
**Describe the bug**
With fresh installation in product page, category page and information page has a issue with jquery.
What section does it affect?
Categories, Products, Information
**To Reproduce**
1. Go to 'Produscts page'
2. Click on 'Edit' and open browser console

**Expected behavior**

**Screenshots / Screen recordings**
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery-2.1.1.min.js:4
ajax @ jquery-2.1.1.min.js:4
n._evalUrl @ jquery-2.1.1.min.js:4
domManip @ jquery-2.1.1.min.js:3
append @ jquery-2.1.1.min.js:3
(névtelen) @ opencart.js:7
each @ jquery-2.1.1.min.js:2
each @ jquery-2.1.1.min.js:2
(névtelen) @ opencart.js:3
j @ jquery-2.1.1.min.js:2
fireWith @ jquery-2.1.1.min.js:2
ready @ jquery-2.1.1.min.js:2
I @ jquery-2.1.1.min.js:2
jquery-2.1.1.min.js:4 GET https://beta.angyalicipok.hu/admin/view/javascript/summernote/lang/summernote-en-US,en_US.UTF-8,en_US,en-gb,english-EN-US,EN_US.UTF-8,EN_US,EN-GB,ENGLISH.min.js?_=1637392543878 404
send @ jquery-2.1.1.min.js:4
ajax @ jquery-2.1.1.min.js:4
n._evalUrl @ jquery-2.1.1.min.js:4
domManip @ jquery-2.1.1.min.js:3
append @ jquery-2.1.1.min.js:3
(névtelen) @ opencart.js:7
each @ jquery-2.1.1.min.js:2
each @ jquery-2.1.1.min.js:2
(névtelen) @ opencart.js:3
j @ jquery-2.1.1.min.js:2
fireWith @ jquery-2.1.1.min.js:2
ready @ jquery-2.1.1.min.js:2
I @ jquery-2.1.1.min.js:2
VM3239:1 Uncaught SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at Function.globalEval (jquery-2.1.1.min.js:2)
    at text script (jquery-2.1.1.min.js:4)
    at vc (jquery-2.1.1.min.js:4)
    at x (jquery-2.1.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.1.1.min.js:4)
    at Object.send (jquery-2.1.1.min.js:4)
    at Function.ajax (jquery-2.1.1.min.js:4)
    at Function.n._evalUrl (jquery-2.1.1.min.js:4)
    at n.fn.init.domManip (jquery-2.1.1.min.js:3)
globalEval @ jquery-2.1.1.min.js:2
text script @ jquery-2.1.1.min.js:4
vc @ jquery-2.1.1.min.js:4
x @ jquery-2.1.1.min.js:4
(névtelen) @ jquery-2.1.1.min.js:4
send @ jquery-2.1.1.min.js:4
ajax @ jquery-2.1.1.min.js:4
n._evalUrl @ jquery-2.1.1.min.js:4
domManip @ jquery-2.1.1.min.js:3
append @ jquery-2.1.1.min.js:3
(névtelen) @ opencart.js:7
each @ jquery-2.1.1.min.js:2
each @ jquery-2.1.1.min.js:2
(névtelen) @ opencart.js:3
j @ jquery-2.1.1.min.js:2
fireWith @ jquery-2.1.1.min.js:2
ready @ jquery-2.1.1.min.js:2
I @ jquery-2.1.1.min.js:2
load (aszinkron)
send @ jquery-2.1.1.min.js:4
ajax @ jquery-2.1.1.min.js:4
n._evalUrl @ jquery-2.1.1.min.js:4
domManip @ jquery-2.1.1.min.js:3
append @ jquery-2.1.1.min.js:3
(névtelen) @ opencart.js:7
each @ jquery-2.1.1.min.js:2
each @ jquery-2.1.1.min.js:2
(névtelen) @ opencart.js:3
j @ jquery-2.1.1.min.js:2
fireWith @ jquery-2.1.1.min.js:2
ready @ jquery-2.1.1.min.js:2
I @ jquery-2.1.1.min.js:2
jquery-2.1.1.min.js:2 [Violation] 'DOMContentLoaded' handler took 167ms

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by ADDCreative** [comment] 2021-11-20 11:32
Possible duplicate of https://github.com/opencart/opencart/issues/9635 and https://github.com/opencart/opencart/issues/10259.

**Comment by oobayi** [comment] 2021-11-24 15:46
I downloaded 3.0.3.8 from opencart.com. I found the same problem as you. The default is English and no other language is added

**Comment by webkul-dilip** [comment] 2021-11-25 05:50
https://github.com/opencart/opencart/pull/10275 we have fixed the issue now

**Comment by Opencart-Webkul** [comment] 2021-12-03 05:09
Merged PR https://github.com/opencart/opencart/pull/10275

**Closed by Opencart-Webkul** 2021-12-03 05:09 UTC
