### ISSUE TITLE
catalog/model/tools/image.php

### ISSUE THREAD

**Issue by carlospo** [opencart/opencart#10445] opened 2022-02-28 19:27 UTC
**What version of OpenCart are you reporting this for?** 3.2

**Describe the bug**
image not load on render

**To Reproduce**
1. Provider create in directory of publication site, with link symbol of a linux, 
2. Image broken
3. the function "realpath" not equal a DIR_IMAGE of config.php
4. Solution description real path in DIR_IMAGE, 
it took hours of research and testing to find this problem

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment] 2022-02-28 19:49
OC Forum request.

**Comment by ADDCreative** [comment] 2022-03-01 09:48
Duplicate of https://github.com/opencart/opencart/issues/7080.

**Comment by mhcwebdesign** [comment] 2022-03-01 12:05
Please post on the OpenCart forum, with sufficient details on how to reproduce this error.
BTW.: There is no version 3.2 of OpenCart.

**Closed by mhcwebdesign** 2022-03-01 12:05 UTC
