### ISSUE TITLE
Paypal Error: Expected an order id to be passed

### ISSUE THREAD

**Issue by bluegeeks1988** [opencart/opencart#7934] opened 2020-05-10 19:32 UTC
Think this is a new bug. I am using OpenCart 3.0.3.3 and when we go to checkout with paypal we get this message:
 
Request is not well-formed, syntactically incorrect, or violates schema. and inside the console we get error like: Error: Expected an order id to be passed any idea what this is and how to fix? been trying to find information online about it and on paypal issues it says: 

400 BAD REQUEST  - INVALID REQUEST

Thanks

**Comment by straightlight** [comment] 2020-05-12 14:59
This issue seem to be addressed more and more. Might be a major incident with this extension. So far, it seem to be related on the ways tokens are being assigned to PayPal as per this post on StackOverFlow: https://stackoverflow.com/questions/57197907/paypal-expected-an-order-id-to-be-passed .

**Comment by bluegeeks1988** [comment] 2020-05-13 21:30
Hi Guys, 

Thought would let you know my findings it seems to be ok and working for Items that can be shipping. But items which are Downloadable which do not require shipping it gives an error on.

I have a developer looking into it so if he fixes i show my findings but this is costing me some money as i needed it done :(

**Comment by dmitriyzhuk** [comment] 2020-05-14 07:04
Hi, could you please contact our support at https://dreamvention.ee/support and provide some more details on this issue. we need to see the requests sent to be able to resolve it. thank you

waiting for your ticket. please attach the link to this thread when you create it.!

**Comment by dmitriyzhuk** [comment] 2020-05-14 07:07
Also please try to install from the master https://github.com/Dreamvention/paypal branch and let me know if the issue still stays.

**Comment by bluegeeks1988** [comment] 2020-05-14 08:13
Ok, i have sent Support request but not heard back.

**Comment by bluegeeks1988** [comment] 2020-05-14 08:19
Hi so i have installed the version on link you sent and now i get a different error:

Cannot deserialize instance of `com.paypal.api.platform.checkout.orders.v2.model.ShippingDetail` out of START_ARRAY token line: 1, column: 126

**Comment by bluegeeks1988** [comment] 2020-05-14 08:47
Ticket id: 21621 for response if you could that be great.

**Comment by danielkerr** [comment] 2020-05-14 15:42
ok found this is a non issue and fixed after a reinstall of the extension.

**Comment by bluegeeks1988** [comment] 2020-05-14 16:48
Hi Daniel,

Was that also doing a download product not shipping product?

**Comment by bluegeeks1988** [comment] 2020-05-14 17:26
As i have uninstalled, reinstalled from opencart.com as it shows was updated today 14/05/2020 but i get this when checking out for: Downloadable products which do not require shipping:

 Cannot deserialize instance of `com.paypal.api.platform.checkout.orders.v2.model.ShippingDetail` out of START_ARRAY token line: 1, column: 126

**Comment by dmitriyzhuk** [comment] 2020-05-14 17:42
Oh, ok, one moment. We will run it with downloadable products ...

**Comment by bluegeeks1988** [comment] 2020-05-14 18:05
Thanks.

**Comment by bluegeeks1988** [comment] 2020-05-14 18:25
Also so you are aware, i installed fresh copy of OC 3.0.3.3 and got same error :) just incase you wondered :).

Thanks

**Comment by bluegeeks1988** [comment] 2020-05-14 18:59
Any idea on the problem as i see you thumbs up 👍 as its so made its like it expects shipping to be selectable.

**Comment by Bored-opencarter** [comment] 2020-05-14 20:43
Having exact same issue, also with products that do not get posted.  Sometimes payment goes through and sometimes get this error.

**Comment by bluegeeks1988** [comment] 2020-05-14 20:49
Glad i not the only one :)

**Comment by Bored-opencarter** [comment] 2020-05-14 21:15
is your error intermittent as well?

**Comment by bluegeeks1988** [comment] 2020-05-14 21:18
> is your error intermittent as well?

My error is all time I not been able to do a successful transaction with a downloadable product the one issue I had was: "Request is not well-formed, syntactically incorrect, or violates schema." and in the developer console tells me about the Expected order id to be passed, and then an update or change was done now I get: com.paypal.api.platform.checkout.orders.v2.model.ShippingDetail out of START_ARRAY token line: 1, column: 122 now not 126 which states above.

Also tried it on a fresh install of OC incase was my migration from old cart to new, but it happens on the fresh install as well. But I can do a purchase for shipping items. just not Downloadable ones which do not require shipping

**Comment by bluegeeks1988** [comment] 2020-05-15 10:58
Hi @dmitriyzhuk , 

Any update on a fix :). as its been a few days :)

Thanks
Aaron

**Comment by straightlight** [comment] 2020-05-15 11:04
> Also please try to install from the master https://github.com/Dreamvention/paypal branch and let me know if the issue still stays.

In catalog/controller/extension/payment/paypal.php file,

these lines are hardcoded:

```'description' => 'Your order ' . $order_info['order_id'],```

sprintf with $this->language->get should be used since, both, Opencart and PayPal do use multi-languages.

**Comment by bluegeeks1988** [comment] 2020-05-15 11:46
I have tried the latest paypal master from git and it seems to be working :) but as suggested it be gould to use the sprintf :) so multi language can be used :).

Thanks
Aaron

**Comment by straightlight** [comment] 2020-05-15 12:03
> I have tried the latest paypal master from git and it seems to be working :) but as suggested it be good to use the sprintf :) so multi language can be used :).
> 
> Thanks
> Aaron

Ok, I have now updated the topic on the forum: https://forum.opencart.com/viewtopic.php?f=202&t=217796&p=787023#p787023 and set to solved.

**Comment by danielkerr** [comment] 2020-05-15 12:04
Ok re opened until we confirmed it's fixed

**Comment by dmitriyzhuk** [comment] 2020-05-15 17:21
Ok, we updated it and tested with downloadable products. all went through. please give it a try to confirm.

**Comment by bluegeeks1988** [comment] 2020-05-15 18:18
Yes after the change you made this afternoon it worked for me unless you have done more edits since?

**Comment by goldengit** [comment] 2020-05-15 19:08
I just updated to the latest plugin release 1.1.4 and I am getting the error  "If the currency supports decimals, only two decimal place precision is supported."  at the bottom left when I click on paypal button - this happens for any products in cart- any idea?

**Comment by bluegeeks1988** [comment] 2020-05-16 02:10
Just one thing it may be nothing, but inside your paypal Setup what have you got as your currnecy? USD? or soemthing else?

**Comment by Bored-opencarter** [comment] 2020-05-16 07:33
Mine is GBP

**Comment by bluegeeks1988** [comment] 2020-05-16 09:56
> 
> Mine is GBP
> […](#)
> On Sat, 16 May 2020 at 03:11, bluegeeks1988 ***@***.***> wrote: Just one thing it may be nothing, but inside your paypal Setup what have you got as your currnecy? USD? or soemthing else? — You are receiving this because you commented. Reply to this email directly, view it on GitHub <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopencart%2Fopencart%2Fissues%2F7934%23issuecomment-629573687&data=02%7C01%7C%7Ce26329ac4f6040bd5c7508d7f93e645a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637251918667828355&sdata=tZ5Yr%2Bu6E0s0CBWEiYtWib2ogAp3hY1R%2Bk2GgnuP2j0%3D&reserved=0>, or unsubscribe <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPSXLBPCMBPFAU364BTXOLTRRXY3TANCNFSM4M5L3TXA&data=02%7C01%7C%7Ce26329ac4f6040bd5c7508d7f93e645a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637251918667838346&sdata=WvDPch%2Bjv7Fp9UYUXEZSyURz%2BlqAXLA%2BDtcKHUYR1uM%3D&reserved=0> .

Hi, did you install then reinstall :) with new download from here: https://github.com/Dreamvention/paypal as this version works for me.

**Comment by straightlight** [comment] 2020-05-16 10:32
@Bored-opencarter and @goldengit: Are you both sure you're using the extension update rather than the one installed from the core this time if using Opencart v3.0.33 release? Also, did you tried Dreamvention's master branch version or did you downloaded the extension version from the Marketplace?

Also, did you cleared the sass and developers cache as well as refreshed the modifications in the OC admin after updating the extension payment module?

**Comment by goldengit** [comment] 2020-05-17 05:37
@straightlight - downloaded latest from  dreamvention master branch - I have not cleared sass and dev cache  and did not refresh modifications in the OC admin - let me try these things and report back

**Comment by straightlight** [comment] 2020-05-17 10:31
Another issue addressed from the OC forum regarding multi-languages: https://forum.opencart.com/viewtopic.php?f=202&t=217916&p=787650#p787638 .

**Comment by dmitriyzhuk** [comment] 2020-05-17 11:01
@straightlight this is not for OpenCart but for Paypal Internal reference. This shouldn't be multilanguage 

`
'description' => 'Your order ' . $order_info['order_id'],
`

Please follow the code to see that it is used to initiate $paypal.

Guys, If you are experiencing an issue, please create a support ticket at https://dreamvention.ee/support and share you access credentials so that we could view the issue. 

The issue that @bluegeeks1988 reported has been fixed in the v1.1.4. and updated on master. 
if after update you still face any issues, please create a support ticket https://dreamvention.ee/support 

this is the fastest way to get help. thank you!

**Comment by straightlight** [comment] 2020-05-17 11:34
@dmitriyzhuk: Who would of thought that ```your order``` was a mandatory term for PayPal to accept in order to send the API request successfully ... it even tricked me ...

Good to know, however.

**Comment by danielkerr** [comment] 2020-05-17 14:06
ill do a new release monday with the fix in.

**Comment by bluegeeks1988** [comment] 2020-05-17 14:09
Fantastic Guys, great work :) took few days to get there but we got there,
And thanks @danielkerr good to know a fix will be sorted. for multi-language.

**Comment by goldengit** [comment] 2020-05-18 19:20
@straightlight  - just tested again getting same error about order id not being passed  after clearing saas and mod cache - where do I find Dev cache in OC admin console?

**Comment by bluegeeks1988** [comment] 2020-05-18 20:36
Hi @goldengit,

Would you like me to take a look for you :) to see if I can fix the problem?

As I know its rotten when things like this do not work I am free all night and tomorrow so PM, if you would like me to take a look email, is: aaron@london-hosting.com and of course I not charging its FREE just so you know.

Thanks
Aaron

**Comment by straightlight** [comment] 2020-05-18 22:02
> @straightlight - just tested again getting same error about order id not being passed after clearing saas and mod cache - where do I find Dev cache in OC admin console?

Here: https://forum.opencart.com/viewtopic.php?f=134&t=215776#p718325

**Comment by goldengit** [comment] 2020-05-18 22:12
Hi Aaron that would be great! really appreciate the help:) sending you email now..

**Comment by bluegeeks1988** [comment] 2020-05-18 22:12
Ok great.

**Comment by bluegeeks1988** [comment] 2020-05-19 00:01
Hi Guys,

So i been looking at an issue @goldengit has been having so after I cleared cache the: Expected order id issue went away, but if you try to checkout using say USD Currency you get an error message:

 If the currency supports decimals, only two decimal place precision is supported.

But if you change this to be GBP / Pound Sterling, it allows you to checkout no problem at all.

Thanks
Aaron

**Comment by straightlight** [comment] 2020-05-19 00:06
Good to know, it seem that forcing the currency code to USD for PayPal can no longer be prioritized for all payments. May be PayPal did took initiative, this time, to process each payments based on regional locations where the currency code needs to follow along as compared to previous PayPal extension payment modules Opencart used to handle.

**Comment by bluegeeks1988** [comment] 2020-05-19 00:25
Think i found the issue - Its to do with Tax :). so basically on the Flate Rate shipping it was set to Taxable Goods and the price was coming out at like $0.78 which means it will fail because the error we are receiving it needs to be greater than 0 as this is what it says on Paypal Developer:

CANNOT_BE_ZERO_OR_NEGATIVE
It must be greater than zero. If the currency supports decimals, only two decimal place precision is supported.
Specify a different value and try the request again.

**Comment by haitranvua** [comment] 2020-05-19 03:43
> Think i found the issue - Its to do with Tax :). so basically on the Flat Rate shipping it was set to Taxable Goods and the price was coming out at like $0.78 which means it will fail because the error we are receiving it needs to be greater than 0 as this is what it says on Paypal Developer:
> 
> CANNOT_BE_ZERO_OR_NEGATIVE
> It must be greater than zero. If the currency supports decimals, only two decimal place precision is supported.
> Specify a different value and try the request again.

I try to change Flat Rate tax class to none but the error still display

**Comment by bluegeeks1988** [comment] 2020-05-19 07:22
in your cart, do you have any items which show on checkout that start with $0. etc? i.e Shipping.

Also in your Paypal configuration where it has "Total" to determine how much the cart need to reach before it activates Paypal set this to: something like 1.00 instead of 0.01.

**Comment by bluegeeks1988** [comment] 2020-05-19 07:48
@haitranvua - if you need some assistance I can take a quick for you? send an email to aaron@london-hosting.com Thanks Aaron

**Comment by bluegeeks1988** [comment] 2020-05-19 21:40
Hi so we have come across an error, any price that is in the thousands gives an error and this is the explanation I sent across to the developers :) to try and get some help in this:

There is still an issue :) if the price is in the 1000.00's as you know when opencart gets into the thousands it adds command so looks like 1,000.00 and this is for UK, US and any other country etc the error it displays is:

 The value of a field does not conform to the expected format. and on Paypal API it states this:

INVALID_PARAMETER_SYNTAX
The value of a field does not conform to the expected format.
Verify that the pattern is supported and try the request again.

so what I thought I would do to try and fake it was go into the admin and catalog language files and remove: the thousand point to just blank so it would display as: 1000.00 but still through an error, so then I looked inside the erorr_log and this is the file and line numbers its erroring on is:

2020-05-19 21:33:43 - PHP Notice:  A non well formed numeric value encountered in /var/www/html/opencart/catalog/controller/extension/payment/paypal.php on line 186
2020-05-19 21:33:43 - PHP Notice:  A non well formed numeric value encountered in /var/www/html/opencart/catalog/controller/extension/payment/paypal.php on line 191
2020-05-19 21:33:43 - PHP Notice:  A non well formed numeric value encountered in /var/www/html/opencart/catalog/controller/extension/payment/paypal.php on line 191
2020-05-19 21:33:43 - PHP Notice:  A non well formed numeric value encountered in /var/www/html/opencart/catalog/controller/extension/payment/paypal.php on line 203

and the code for these are:

186: $item_total += $product_price * $product['quantity'];

191: $tax_total = $total - $sub_total;

203: $rebate = $item_total + $tax_total + $shipping_total - $order_total;

**Comment by bluegeeks1988** [comment] 2020-05-20 00:16
Hey, I got a question about this as I may get a solution.

So Inside file: catalog/controller/extension/payment/paypal.php it used number_format -  which I have been reading and it only supports: "Note: This function supports one, two, or four parameters (not three)."

So I not sure if I did it correctly or not as I, not a complete programmer as still learning but I changed all the number_format to "round" and Paypal started to work with numbers in the 1000's? maybe someone can tell me if this is ok or if there is another format to use i.e maybe count?

Thanks
Aaron

**Comment by ADDCreative** [comment] 2020-05-20 12:41
number_format will add a thousands separator and return a string. You certainly don't want to be using it on value before it's used in a calculation. The added thousands separator could also cause problems if PayPal expects just a string representation of a float.

You probably don't want to use round either, unless PayPal only accepts 2 decimal places even for currencies they have a different number of decimal places.

The correct way would be to do currency->format with the fourth parameter set to false.
```$this->currency->format($value_to_be_rounded, $currency_code, $currency_value, false)```
or
```$this->currency->format($value_to_be_rounded, $currency_code, 1.0, false)```
depending on whether any conversion needed to be done at the same time.

If there were still minor rounding issues when casting the float to a string, then number_format should be use, but made use the correct decimal places for the currency and not to use the thousands separator.

This would be needed to be done on any value before being loaded into the $order_info array but after any calculations.

It's a bit frightening that whoever writing the module has not released this and is trying to fix this by changing the PHP precision and adding formatting or rounding in random places. Which will probably never solve the issues. I assume it also wasn't fully tested before adding to the core.

**Comment by bluegeeks1988** [comment] 2020-05-20 12:58
:). i have received a solution from developer: try changing number_format to be:

number_format($this->currency->format($product['price'], $currency_code, $currency_value, false), 2,'.',''); not tried it yet but i will later today.

**Comment by ADDCreative** [comment] 2020-05-20 13:02
Doing a number format stright after the currency->format, but before the calculation would be pointless.

**Comment by bluegeeks1988** [comment] 2020-05-20 13:04
Ok :) just letting you know, support sent me this :).

**Comment by chinwag** [comment] 2020-05-20 20:24
Notice: Undefined index: iso_code_2 in /home2/austria1/public_html/---domain---/catalog/model/extension/shipping/mcgeozone.php on line 63
Notice: Undefined index: zone_id in /home2/austria1/public_html/---domain---/catalog/model/extension/shipping/mcgeozone.php on line 101

Happens when language switched from Default, i.e. en-gb, and on the individual product page, the Add to Cart button is clicked then the PayPal button is clicked underneath Add to Cart. Initiates PayPal payment, log in to PayPal, then takes me back to the my website ofr Weight information to be calculated, i.e. index.php?route=extension/module/paypal_smart_button/confirmOrder

All works OK if language is default (en-gb). Ticket #21676

**Comment by dmitriyzhuk** [comment] 2020-05-21 11:03
@ADDCreative only if it returns a string, but we are passing False in $format field and are returning an $amount 

```php
public function format($number, $currency, $value = '', $format = true) {
		$symbol_left = $this->currencies[$currency]['symbol_left'];
		$symbol_right = $this->currencies[$currency]['symbol_right'];
		$decimal_place = $this->currencies[$currency]['decimal_place'];

		if (!$value) {
			$value = $this->currencies[$currency]['value'];
		}

		$amount = $value ? (float)$number * $value : (float)$number;
		
		$amount = round($amount, (int)$decimal_place);
		
		if (!$format) {
			return $amount; // <---- this is a float, but PAYPAL wants to have a float with only two digits after the point. so number_format solves this issue without modifying the library code.
		}

		$string = '';

		if ($symbol_left) {
			$string .= $symbol_left;
		}

		$string .= number_format($amount, (int)$decimal_place, $this->language->get('decimal_point'), $this->language->get('thousand_point'));

		if ($symbol_right) {
			$string .= $symbol_right;
		}

		return $string;
	}
```

**Comment by dmitriyzhuk** [comment] 2020-05-21 11:09
please update with latest version https://github.com/Dreamvention/paypal/releases/ (v1.1.5)

**Comment by ADDCreative** [comment] 2020-05-21 21:03
@dmitriyzhuk Your latest release is a better, but you still haven't understood the point I was making that you have been rounding/formatting in the wrong place. Anyway currency->format rounds to the correct decimal places ```$amount = round($amount, (int)$decimal_place);``` which when cast to to a string will be correct. You also shouldn't need to change the precision. You just need to round/format in the correct place after all calculations.

You are still performing arithmetic after the number format. Which means ```$handling_total``` is now a float. Which you then use without rounding/formatting.
https://github.com/Dreamvention/paypal/blob/v1.1.5/catalog/controller/extension/payment/paypal.php#L209

You have not accounted for (or tested) currencies with different decimal places. If you set the currency to Japanese yen. You will get the error. 
> Currency does not support decimals. Please refer to https://developer.paypal.com/docs/integration/direct/rest/currency-codes/ for more information.

Because as that link tells you.
> 1 This currency does not support decimals. If you pass a decimal amount, an error occurs.

If you don't trust PHP to correctly format a rounded float and you are going to use number_format, you need to use the decimal places for that currency, not just assume it's 2. And best to leave the number_format to the very last step. Such as.

```php
$product_price = $this->currency->format($product['price'], $currency_code, $currency_value, false);

$item_info[] = array(
	'name' => $product['name'],
	'sku' => $product['model'],
	'url' => $this->url->link('product/product', 'product_id=' . $product['product_id'], true),
	'quantity' => $product['quantity'],
	'unit_amount' => array(
		'currency_code' => $currency_code,
		'value' => number_format($product_price, $the_correct_decimal, '.', '')
	)
);
```

**Comment by danielkerr** [comment] 2020-05-22 12:17
ok latest commit here:

https://github.com/opencart/opencart/commit/f0255e79b98fafe41d4b4cdd6b83b24b9fdfcd76

**Comment by straightlight** [comment] 2020-05-27 11:54
Has the reported issues been resolved since the last commit modification addressed on the above?

**Comment by bluegeeks1988** [comment] 2020-05-27 11:59
I have not had any issues myself :).

**Comment by goldengit** [comment] 2020-05-28 04:18
Just updated to latest plugin version, tested and works great thank you!

**Comment by straightlight** [comment] 2020-05-29 12:15
Ok, this commit will now be closed. Issue has been resolved. Thank you for your feedback.

**Closed by straightlight** 2020-05-29 12:15 UTC

**Comment by shadinamrouti** [comment] 2020-06-12 23:18
> ok latest commit here:
> 
> [f0255e7](https://github.com/opencart/opencart/commit/f0255e79b98fafe41d4b4cdd6b83b24b9fdfcd76)

I tested the commit and it fixed the problem. Thank you!
