### ISSUE TITLE
Warning: Cannot modify header information - headers already sent by (output started at /var/www/capulanasngila.com/shop/admin/controller/startup/error.php:34) in /var/www/capulanasngila.com/shop/system/library/response.php on line 36

### ISSUE THREAD

**Issue by tjapro** [opencart/opencart#9139] opened 2021-01-18 12:05 UTC
**What version of OpenCart are you reporting this for?**
3.0.3.6

**Describe the bug**
I always get that warning when save anything in admin settings:
```Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../admin/controller/startup/error.php:34) in /var/www/.../system/library/response.php on line 36```
Then I need to edit the url and introduce again the admin credencials....

**To Reproduce**
1. Go to admin settings.
2. Change something.
3. Save it.

**Expected behavior**
No warnings and the admin page to be shown.

**Screenshots / Screen recordings**

**Server / Test environment (please complete the following information):**
VPS
CentOS 7
PHP 7.4.0
Nginx 1.16.1
Chrome
Version 87.0.4280.88

**Additional context**

**Comment by mhcwebdesign** [comment] 2021-01-18 12:27
I am unable to reproduce your issue, it's not an OpenCart bug but more likely something else is going on here. At the very least please provide some more information, e.g. server's and OpenCart's error logs, and OpenCart OCmod log.

**Comment by tjapro** [comment] 2021-01-18 12:55
OpenCart's erro:
```
2021-01-18 12:43:18 - PHP Warning:  Division by zero in /var/www/.../admin/model/localisation/currency.php on line 141
2021-01-18 12:43:18 - PHP Warning:  A non-numeric value encountered in /var/www/.../admin/model/localisation/currency.php o$
2021-01-18 12:43:18 - PHP Warning:  Division by zero in /var/www/.../admin/model/localisation/currency.php on line 141
2021-01-18 12:43:18 - PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/.../admin/controller/startup/error.php:34) in /var/www/.../system/library/response.php on line 36
```

OCmod log:
```
2021-01-18 12:31:45 - MOD: Modification Default

FILE: system/engine/action.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 69

FILE: system/engine/loader.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 77
LINE: 151
LINE: 168

FILE: system/library/config.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 59

FILE: system/library/language.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 67
LINE: 73

FILE: system/library/template/template.php
REGEX: ~(require|include)(_once)?\(([^)]+)~
LINE: 18

FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!
----------------------------------------------------------------
```

**Comment by tjapro** [comment] 2021-01-18 12:56
And just a question: is it secure to use the last files in maintance branch to production mode?

**Comment by tjapro** [comment] 2021-01-18 12:58
And that error appears in every save settings I've made.

**Comment by mhcwebdesign** [comment] 2021-01-18 13:15
First of all, use a fixed system/modification.xml from

https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/modification.xml

and refresh your OCmod modifications. Then try again editing your settings.

**Comment by tjapro** [comment] 2021-01-18 13:58
I tried the following:
- Login as admin
- Change use SSl to no use it.
- Save it.
- Same roll of Warnings (the non-numeric value and the cannot modify header information).

**Comment by tjapro** [comment] 2021-01-18 13:59
And I'm still with the demo data

**Comment by ADDCreative** [comment] 2021-01-18 14:55
Duplicate of https://github.com/opencart/opencart/issues/8866. Try the changes here. https://github.com/opencart/opencart/pull/8870/files Or switch off the the currency rates refresh.

**Comment by tjapro** [comment] 2021-01-18 14:57
I'll try.

**Closed** 2021-01-18 15:34 UTC

**Comment by tjapro** [comment] 2021-01-18 23:56
@ADDCreative, thanks for the help. With that updated file the warnings were gone!
