### ISSUE TITLE
[v3.0.2.0 - Issue] - Incorrect Cart heading Use Gift Certificate 

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6119] opened 2017-10-19 13:18 UTC
A user reported an issue with the cart heading when Using Gift Certificate: https://forum.opencart.com/viewtopic.php?f=202&t=198804#p699462

**Comment by AlexChanHK** [comment] 2017-11-27 09:46
Duplicate of #6138
Can be closed.

**Closed** 2017-11-28 06:12 UTC
