### ISSUE TITLE
Twig_Error_Loader: Template is not defined

### ISSUE THREAD

**Issue by osysltd** [opencart/opencart#7443] opened 2019-05-19 14:58 UTC
Dear Devs,
Thanks for the great product, very much appreciated!

With the recent updates in master branch of OpenCart, using includes in twig templates
```
<div class="tab-pane{{ (lastActiveTab == 'tab-kassa' ? ' active' : '') }}" id="tab-kassa">
   {% include 'extension/payment/yandex_money/kassa.twig' %}
</div>
```
 I get the following error

``` 
Twig_Error_Loader: Template "extension/payment/yandex_money/kassa.twig" is not defined in "extension/payment/yandex_money.twig" at line 46. in C:\OSPanel\domains\oshp\storage\vendor\twig\twig\lib\Twig\Loader\Array.php on line 65
```

Please could you help to figure out the workaround or solution?

**Comment by straightlight** [comment] 2019-05-19 17:02
Those TWIG files are not among the master branch files, however. These are caused by incompatibility between the conventional name of stable releases versus the master branch on GitHub. In other words, your extensions may not be compatible with the GitHub version of OC.

**Comment by osysltd** [comment] 2019-05-20 09:33
How to use inculdes in TWIG templates properly then?

**Comment by straightlight** [comment] 2019-07-16 13:47
For now, you could try this solution: https://github.com/opencart/opencart/pull/7153#issuecomment-500143157 . Closing commit.

**Closed by straightlight** 2019-07-16 13:47 UTC

**Comment by monwar4242a** [comment] 2023-01-19 03:04
i cannot solve this problem please help me

( ! ) Fatal error: Uncaught Twig\Error\LoaderError: Template "extension/soconfig/options_mobile.twig" is not defined in "extension/soconfig/somobile.twig" at line 62. in C:\wamp64\www\opencart\upload\system\storage\vendor\twig\twig\src\Loader\ArrayLoader.php on line 70
--

**Comment by mhcwebdesign** [comment] 2023-01-19 12:40
@ monwar4242a : There is no need to hijack on old github thread for this different issue. Your issue has nothing to do with OpenCart, the problem is with your poor-quality web theme. Please re-post on the OpenCart forum, or better, contact the extension author.
