### ISSUE TITLE
Restore quietly ignores Backup SQL containing Windows linefeeds

### ISSUE THREAD

**Issue by briuri** [opencart/opencart#13717] opened 2024-02-24 18:11 UTC
This bug occurs on both the master branch and 3.0.x.x branch.

`opencart/upload/admin/controller/tool/backup.php`
(Master branch: Line 300, 3.0.x.x branch: Line 102)

* The Restore code looks for lines that end with a semicolon and Unix/Mac line feed (";\n") before sending the SQL queries to the DB adaptor.
* If the Restore code encounters Windows linefeeds (";\r\n"), queries are always skipped, but the process still ends with a misleading SUCCESS! message. 

Normally, this isn't a problem because Backup (with OpenCart running on a Linux server) generates SQL with the correct linefeeds. However, there are plenty of chances for the linefeeds to accidentally get converted during Windows development. (In my case, simply moving the SQL files into an IntelliJ IDEA project converted from \n to \r\n until I realized what was going on and forced the IDE to keep the correct linefeed).

My local patch to handle either kind of line feed is below (based on 3.0.x.x branch) :
```
                if ($start && substr($line, -2) == ";\n") {
                    $this->db->query(substr($sql, 0, strlen($sql) -2));

                    $start = false;
                }
+                // Handle Windows line feeds, in case export SQL file was edited in Windows
+                if ($start && substr($line, -3) == ";\r\n") {
+                    $this->db->query(substr($sql, 0, strlen($sql) -3));
+
+                    $start = false;
+                }
```

**Comment by mhcwebdesign** [comment] 2024-02-25 16:17
Question: When you run the backup on a Windows machine (I don't have  a Windows box on hand, so can't test it with Windows), not a Linux box, does it produce ";\n" or ";\r\n" line endings?

**Comment by mhcwebdesign** [comment] 2024-02-25 17:53
> `\r` is included with Windows.

I know. But does the OpenCart backup generate the file with ";\r\n" or ";\n" line endings when run on e.g. a WAMP server?

**Comment by TheCartpenter** [comment] 2024-02-25 18:08
> > `\r` is included with Windows.
> 
> I know. But does the OpenCart backup generate the file with ";\r\n" or ";\n" line endings when run on e.g. a WAMP server?

This has been asked before. It has nothing to do whether it's used with WAMP server or not. The fact a platform is rather ran on a Windows virtual or Windows IIS environment, ```\r``` is still generated by default which is why it must be declared as for the same reason not to ignore the: ```might be defined``` outputs from PHPStan since Windows will still require, either, variables or a carriage return.

**Comment by TheCartpenter** [comment] 2024-02-25 18:23
Furthermore, more examples whereas ```\r``` is already used in the core:

- admin/controller/sale/order.php
- admin/view/template/sale/order_info.twig
- catalog/controller/account/address.php
- catalog/controller/account/order.php
- catalog/controller/account/subscription.php
- catalog/controller/mail/order.php

**Comment by mhcwebdesign** [comment] 2024-02-25 18:28
OK, thanks for the clarifications. Will amend 3.0.x.x accordingly for the backup/restore.

**Comment by mhcwebdesign** [comment] 2024-02-26 11:05
Now fixed for the 3.0.x.x branch: https://github.com/opencart/opencart/pull/13734

**Comment by danielkerr** [comment] 2024-02-26 22:45
im running wamp and its fine.

**Comment by danielkerr** [comment] 2024-02-26 22:45
could it be ur opening it in notepad? and not an IDE?

**Comment by danielkerr** [comment] 2024-02-26 22:49
![image](https://github.com/opencart/opencart/assets/5079756/aa34f45b-7b2f-4696-bcb9-3c50e0ebb6a9)

**Comment by danielkerr** [comment] 2024-02-26 22:49
its php writing the code so windows shouldnt change anything.

**Closed** 2024-02-26 22:50 UTC

**Comment by TheCartpenter** [comment] 2024-02-26 23:13
> its php writing the code so windows shouldnt change anything.

https://www.stackoverflow.com/questions/4824621/is-a-new-line-r-or-r-n

**Comment by TheCartpenter** [comment] 2024-02-26 23:15
Windows vs. linux do have their differences with ```\r\n``` and ```\n```.

**Comment by danielkerr** [comment] 2024-02-27 17:34
the code is:

$output .= "\n";

and not \r\n 

trhe file generated is not altered by windows! i dont give a fuck what hes using to open the file. its his file editor that is causing the screw up!~ maybe hes using microst word! either way there is no bug and no need foor u to state something that i have known possibly for longer than u have been alive!

**Comment by TheCartpenter** [comment] 2024-02-27 22:15
> the code is:
> 
> $output .= "\n";
> 
> and not \r\n
> 
> trhe file generated is not altered by windows! i dont give a fuck what hes using to open the file. its his file editor that is causing the screw up!~ maybe hes using microst word! either way there is no bug and no need foor u to state something that i have known possibly for longer than millennials have been alive!

Not talking about the ```$output``` . The first post addresses about the ```$start``` and ```$line```. Whether you give a rat's ass or not, while it's already more than obvious that you don't already, anybody could begin before anyone else while they're at it but what those first starters seem to be missing is that two minutes of their time to make the comparison between different OSes when it comes to line changes, whether it's in or from an output file. By looking at the first posts and the previous replies, I don't see any mention with which tools this file was tested and even less the question that came with it.

Therefore, as a founder of the project, this should of been at least asked to the addresser. Instead, you automatically that a paper clip or Microsoft tool were used rather than gathering the information from the user. Granted, it is not a bug as nowhere on my behalf where it was mentioned that it was. However, Windows does imply ```\r``` as opposed to other OSes to add new lines.

**Comment by briuri** [comment] 2024-02-27 23:19
I stated in my original problem description that there is nothing wrong with Backup.

The issue is that Restore happily tells you "You have successfully imported your database!" even when that is misleading, *and having unexpected linefeeds in the file is a very easy cause of a bad SQL file, regardless of whether OpenCart is to blame*.

So, the most pedantic fix would be to update the Restore process with a correct message, like "This file has nothing to import!" or "You're a huge fool for ending up with Windows linefeeds in your data, how do you even make a living at software?!" 

But it's just as easy to help the poor admin out by making Restore accept Windows linefeeds, hence the patch I suggested.

**Comment by osworx** [comment] 2024-02-28 03:23
> > its php writing the code so windows shouldnt change anything.
> 
> https://www.stackoverflow.com/questions/4824621/is-a-new-line-n-or-r-n

Funny to link to the whole story, but the most important comment is this here: https://stackoverflow.com/a/22623514/3450837
Reading this, **PHP_EOL** depends on which system is used (Windows or Linux) and should therefore not be used.

> PHP also defines a newline character called PHP_EOL. This constant is set to the OS specific newline string for the machine PHP is running on (\r\n for Windows and \n for everything else).

I can fully understand (and agree with) Daniel to say f*** and see really no sense in changing the code (like @mhcwebdesign did).

**Comment by TheCartpenter** [comment] 2024-02-28 11:26
While I do agree that the ```\r``` should not be used as an enforced requirement, why not just move this feature on the OC Marketplace altogether now that OCMod has been re-integrated and that OC v3.x releases still has this engine and that both series can still use the Event Triggers?

This would avoid all starters and all enders to keep bringing in the subject in the future and to help maintain the backup / restore compatibility on the OC Marketplace based on its compatibility aside from the rest of the core since the rest of the core does not encounter this issue anyways.
