### ISSUE TITLE
Opencart 2.0.1.1 SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by bport95** [opencart/opencart#3124] opened 2015-06-22 16:59 UTC
I am trying to change the order history to an order and I keep getting an error that says"SyntaxError: Unexpected end of input OK" 

I have seen a lot of solutions to fix this online, but I can't seem to get it to work. Could anybody provide some assistance?

**Comment by danielkerr** [comment] 2015-06-23 06:46
contact your host and ask them to disable loopback blocking.

**Comment by bport95** [comment] 2015-06-23 14:40
@danielkerr I have contacted my host and they were unable to find or resolve the issue. Any other ideas?

**Comment by danielkerr** [comment] 2015-06-23 14:44
im have fixed the issue in the latest branch. just need to do some more changes and testing.

**Comment by danielkerr** [comment] 2015-06-24 07:44
if your looking for a quick fix try 

http://forum.opencart.com/viewtopic.php?f=2&t=146714&p=567297#p567297

**Comment by dmit-ch** [comment] 2015-06-30 12:02
May be irrelevant now, but I had a similar issue with 2.0.3.1.

The fix was simple:

Add "$json = array();" after public "function api() {" in "upload/admin/controller/sale/order.php" AND make sure that the $json array is encoded before "$this->response->setOutput($json);", as it seems that the $json = curl_exec($curl); is not encoded at the end.

Looking at the 2.0.1.1 tag, the situation is the same.

**Comment by Action-Hank** [comment] 2015-07-03 13:28
@dmit-ch 
Can you tell me what you mean with $json = array(); is encoded before "$this->response->setOutput($json);".

Can you show the editted the code, that would be sweet!

Thanks in advanced

**Comment by dmit-ch** [comment] 2015-07-03 14:04
@Action-Hank What's your OC version, so I can check the function for it?

**Comment by Action-Hank** [comment] 2015-07-03 14:20
My version is 2.0.2.0

thanks!

**Comment by dmit-ch** [comment] 2015-07-03 14:38
Follow the below instructions:

Add:
$json = array();
after: 
public function api() {

Replace:
$json = curl_exec($curl);
With
$json = json_encode(curl_exec($curl));

**Comment by Action-Hank** [comment] 2015-07-03 14:42
@dmit-ch Thanks, will try that! Will let you know if it's fixed!

**Comment by Action-Hank** [comment] 2015-07-03 14:54
@dmit-ch 

You Sir, deserve a raise and praise!
It fixed it! I'm enternally greatful!

Just too add:

In file: upload/admin/controller/sale/order.php

Add:
$json = array();
after: 
public function api() {

Replace all lines of:
$json = curl_exec($curl);
With:
$json = json_encode(curl_exec($curl));

**Comment by dmit-ch** [comment] 2015-07-03 15:30
@Action-Hank You are welcome!

I wanted to prepare some pull requests, but I see that the file has been re-done in the master branch.

**Comment by danielkerr** [comment] 2015-07-07 13:59
this does not fix the loop back issue. only stops the error displaying.

**Comment by Action-Hank** [comment] 2015-07-07 14:08
How do we fix it then? Or is it fixed in later versions?

**Comment by arbelaezjm** [comment] 2015-07-16 19:05
Hello Daniel Kerr 
I guess you're busy solving this problem in the next version but my question is there will patch solution for versions 2.31 and earlier...

**Comment by Frank1279** [comment] 2015-07-21 16:58
I have got the same problem, the error occurs when you don't set any SSL url in the Store Settings (I was working on a multistore website). The code involved with the issue is this:

Opencart version 2.0.3.1
File: admin/controller/sale/order.php  (method api() )
At line line 216:

$store_info = $this->model_setting_store->getStore($store_id);

if ($store_info) {
     $url = $store_info['ssl'];
} else {   
     $url = HTTPS_CATALOG;
}

When  $store_info['ssl'] is empty, javascript returns that error because no url is set. That field should be required in the Setting Page or that "if" statement should be modified to check if the variable $store_info['ssl'] is empty.

**Comment by danielkerr** [comment] 2015-08-03 00:37
fixed in the master branch

**Closed by danielkerr** 2015-08-03 00:37 UTC

**Comment by rckani** [comment] 2015-10-07 17:35
Hi Daniel,

Can you please attach the snippet of code modified to resolve this issue?
Opencart version 2.0.3.1
File: admin/controller/sale/order.php

**Comment by sfaragy** [comment] 2015-11-23 02:18
Here is the real solution. Please visit this link below where you can see the live demo and you can figure it out by yourself. Screenshots also available.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24725

**Comment by stockmaster** [comment] 2015-11-23 02:29
@sfaragy this is not addressing the issue in question here, please dont spam
