### ISSUE TITLE
Bug link rel="prev" on manufacturer page=2

### ISSUE THREAD

**Issue by optimlab** [opencart/opencart#7021] opened 2018-11-09 10:48 UTC
If page=2 then rel="prev" incorrectly displays page number: `?page="`
Must be in the file: [catalog/controller/product/manufacturer.php
](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/product/manufacturer.php)
search:
`'&page='. (($page - 2) ? '&page='. ($page - 1) : '')), 'prev'`

replace:
`(($page - 2) ? '&page='. ($page - 1) : '')), 'prev'`

**Comment by andrei-bogdan** [comment] 2018-11-14 13:11
What is the front-end link for this? How do we replicate?

**Comment by MrPlow254** [comment] 2018-11-16 16:43
@andrei-bogdan Do you live under a rock? I have seen multiple comments from you that make no sense. There is enough information in the initial issue submitted to see the error in the code.

Yes, it is still in latest build, link provided here since you are too lazy to look for yourself. https://github.com/opencart/opencart/blob/master/upload/catalog/controller/product/manufacturer.php

If $page = 2 then it will set the if statement to false and output ''
If $page >= 3 then it will set the if statement to true and output '&page='. ($page - 1) which will duplicate  '&page=' since it is before the if statement.

Only think left to interpret is whether the &page needs to be inside of the if statement or before it. I have not looked into which is the case needed. Regardless there is an issue with &page outputting twice.

**Comment by jamesallsup** [comment] 2018-11-16 17:30
@MrPlow254 - While OC team and I greatly appreciate the community investing their own time putting responses to github issues, please can you keep them without and any personally directed comments (or just anything that someone may consider it to be if there are cross languages etc - I know what meant when you questioned living under a rock and know that the context you implied was not distressing/hurtful). Just a polite request to be clear on the thread history - we see many people re-visit stale topics that contained the answer many months later! Some of those visitors have been pretty important people in the "big" companies looking to partner up.

@andrei-bogdan Please reserve the OpenCart GitHub issue tracker for issues relating to a vanilla (unmodified) version of OpenCart which belongs to the current release branches (currently 3.x). Commenting here is with the purpose to help resolve a core issue, so you must be very clear on your comments so that if another helpful community member decides to create a pull request based on your comments - it is vital they are easy to read and correct!

Thanks for the bug report and again, this is just a polite reminder to keep things friendly :)

J

**Comment by andrei-bogdan** [comment] 2018-11-19 10:58
Hi,

@optimlab as far as I have read here, when posting an issue, the following should be provided:

**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

@MrPlow254 I can't BLINDLY create a pull request to fix an issue, with no clarifying information provided (like screenshots or a forum link).
You MUST at all time test your code before making changes. Therefore, a link with a setup that replicates the pagination issue might come in handy and save precious time, since not all developers might have such a setup.
An error without CONTEXT, might not be an error at all and might be a custom fix for an existing business case (for example).

@jamesallsup for me, what has been written here above was very personal. I have been involved in this projects for many years, with custom modules and even core pull requests (which have been accepted). I know how to post comments, how to make pull requests, how to help both users and developers. I believe I do not need lessons on this process.

I think I just lost my interest and enthusiasm in contributing to this project, if people can just come and denigrate developers that have been working (indirectly) many years to help make the product better.

I am expecting some apologies or for those messages to be deleted.

**Comment by optimlab** [comment] 2018-11-19 15:48
@andrei-bogdan, Sometimes the standards of response contradict common sense. The standards are designed not to waste the time of the main developer and his assistants on fake errors, I understand them. But if it is possible to describe the error more succinctly, why not? But especially for you I have prepared a modifier that will solve the problem that you do not see. Just install it!
https://github.com/optimlab/optimblog/tree/master/canonical-manufacturer.ocmod

**Comment by ADDCreative** [comment] 2020-09-22 14:26
Looks like this issue was duplicated by https://github.com/opencart/opencart/issues/7865. Fixed with https://github.com/opencart/opencart/commit/e337ab755c802859667c0f3552e1fef3177bba26. Therefore needs closing.

**Comment by optimlab** [comment] 2020-09-24 12:44
> 
> 
> Looks like this issue was duplicated by #7865. Fixed with [e337ab7](https://github.com/opencart/opencart/commit/e337ab755c802859667c0f3552e1fef3177bba26). Therefore needs closing.

In which version is this fixed?

**Comment by ADDCreative** [comment] 2020-09-24 13:33
None yet. It's been fixed in both the mater and now 3.0.x.x_Maintenance https://github.com/opencart/opencart/commit/acf3d75e5cdee17f18c2b32534280e8d2c747059, so should make the next release.

**Comment by optimlab** [comment] 2020-09-24 14:14
> so should make the next release.

Do you believe it? Three years have passed since version 3.0.0.0. They are fixing the master, but they don't care about the current versions.

**Comment by WebkulOpencart** [comment] 2020-12-30 05:02
This issue is already fixed

**Closed by WebkulOpencart** 2020-12-30 05:02 UTC
Labels: maintenance-branch 3.0.x.x
