### ISSUE TITLE
Paypal on checkout and view cart

### ISSUE THREAD

**Issue by matthew1531** [opencart/opencart#10370] opened 2022-01-16 20:55 UTC
**What version of OpenCart are you reporting this for?**

 3.0.3.8

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect? 

http://shoppershall.com/

1.
Error when clicked "paypal button"  on view cart
"The value of a field is either too short or too long. Please choose another payment method or <a href="http://shoppershall.com/index.php?route=information/contact" target="_blank">contact us</a>."

2., 
Paypal button is not on check out and does nothing when "click on confirm order"

**To Reproduce**

**Expected behavior**
1.
Go to paypal page

2.
Go to papal page 

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by ADDCreative** [comment] 2022-01-16 22:30
Duplicate of https://github.com/opencart/opencart/issues/10320. See https://github.com/opencart/opencart/issues/10320#issuecomment-1003365577 for probable cause.

**Comment by danielkerr** [comment] 2022-05-23 17:53
please open an issue here:

https://github.com/opencart/opencart-3/issues

**Closed by danielkerr** 2022-05-23 17:53 UTC
Labels: maintenance-branch 3.0.x.x
