### ISSUE TITLE
Please close if i have missed read email error

### ISSUE THREAD

**Issue by gsc1ugs** [opencart/opencart#2854] opened 2015-04-03 11:45 UTC
If this 
 $mail->smtp_hostname = $this->config->get('config_mail_smtp_hostname'); 

is a replacement for this
 $mail->smtp_hostname = $this->config->get('config_mail_smtp_host'); 

in those man y files, it is Still not working or have I missed read it? using the contact form is the only email that comes through, no order confirmations, registration, sending mails in admin. none work

**Comment by gsc1ugs** [comment] 2015-04-03 17:57
I have'nt miss read it, its not working, only thing working is the contact us form

**Comment by vbrunets** [comment] 2015-04-04 12:57
Still the same problem. E-mail don't work to!

**Comment by gsc1ugs** [comment] 2015-04-04 14:20
Anyone got a fix? Which is a stable oc 2.x?

**Comment by milimar** [comment] 2015-04-04 14:49
Last stable release is OC 2.0.2.0 , you can download it from here http://www.opencart.com/index.php?route=download/download and test if your problem really exists in the newest release.

**Comment by stockmaster** [comment] 2015-04-04 15:04
Did you check this commit made for 2.0.2.1?
https://github.com/opencart/opencart/commit/b03149e4802cc4ac7e9f9ec59c7be4759840c98f

**Comment by gsc1ugs** [comment] 2015-04-04 15:07
No mate, will look now but this is the host to hostname ive done it. Im on 2.0.2.0 this is the one with email problem after name change

**Comment by stockmaster** [comment] 2015-04-04 15:08
Like i said this is a commit to 2.0.2.1 (notice the ONE) still not released:

v2.0.2.1 (Pending release)

Bugs fixed

Mail config hostname variable (https://github.com/opencart/opencart/issues/2840)

https://github.com/opencart/opencart/blob/8559919f03f7e5462d1c39c9d801917a08db83c8/changelog.md

Worth keeping an eye if you using a 1 week old release :), which is the case of 2.0.2

**Comment by gsc1ugs** [comment] 2015-04-04 15:27
Its just the email prob, is it just me or is it a prob for all?

**Comment by gsc1ugs** [comment] 2015-04-04 15:29
I can cope with other stuff, just fixed a json undefined variable fix

**Comment by stockmaster** [comment] 2015-04-04 16:15
I believe it was a global thing on 2.0.2 launch, fixed on the commit i showed you above. i am running it without problems - that i can see.

**Comment by gsc1ugs** [comment] 2015-04-04 16:40
What you think mine is? I made the changes dtill no mail, is smtp Hardwired should i try 465?

**Comment by vbrunets** [comment] 2015-04-04 21:07
I have the same problem even after fixing files like in 2.0.2.1 pending release. Nothing changed for me. Still can't send e-mail. 

04 квітня 2015, 19:15:57, від "StockMaster" < notifications@github.com >: 

I believe it was a global thing on 2.0.2 launch, fixed on the commit i showed you above. i am running it without problems - that i can see. —

**Comment by danielkerr** [comment] 2015-04-05 07:56
this is not the place to post for your own personal opencart problems. use the forum! this is not a bug fixing service for you!

**Closed by danielkerr** 2015-04-05 07:56 UTC

**Comment by gsc1ugs** [comment] 2015-04-05 09:07
this is a bug? emails don't work, see vbrunets comments

**Comment by gsc1ugs** [comment] 2015-04-07 14:31
Its not that... JUST FIXED IT

if ($this->protocol == 'mail') { LINE 156 in 
.......................\system\library\mail.php

before its was 

if ($this->protocol == 'Mail') {

... case senstive
