### ISSUE TITLE
G2APAY order status doesnt forward to complete

### ISSUE THREAD

**Issue by sterrek** [opencart/opencart#3353] opened 2015-09-17 11:23 UTC
Hi,

I use opencart 2.0.3.1 with g2apay
But when i get a order it does not forward from pending to complete.
When i go to g2apay merchent page i see there that the order is complete.
i added some pictures of my settings.
![orderstatus](https://cloud.githubusercontent.com/assets/9420026/9932379/bc27e9a0-5d43-11e5-89d2-fef736145908.JPG)

![g2settins](https://cloud.githubusercontent.com/assets/9420026/9931826/3977f7ba-5d3f-11e5-9b0e-f57f85eadabf.JPG)

I hope somebody knows a fix or see what i did wrong.

Kind regards

**Comment by sterrek** [comment] 2015-09-17 12:34
@chris-wm maby you know the answer ?

**Comment by chris-wm** [comment] 2015-09-21 15:06
@sterrek Hi, the order status is updated by the IPN so the most likely cause is that the IPN URL is not set-up correctly in G2A Pay.  You can check that the IPN is going through successfully by enabling debugging in the G2A module and then checking for the debug code "token success" in g2apay.log in the log folder,
regards

**Comment by sterrek** [comment] 2015-09-21 16:41
@chris-wm  i see this: 
2015-09-21 18:37:31 - Origin: ControllerPaymentG2APay::ipn
2015-09-21 18:37:31 - Origin: ControllerPaymentG2APay::ipn
2015-09-21 18:37:31 - ipn
2015-09-21 18:37:31 - ipn
2015-09-21 18:37:31 - Origin: ControllerPaymentG2APay::ipn
2015-09-21 18:37:31 - token success
2015-09-21 18:37:31 - Origin: ControllerPaymentG2APay::ipn
2015-09-21 18:37:31 - token success
2015-09-21 18:37:31 - Origin: ControllerPaymentG2APay::ipn
2015-09-21 18:37:31 - Hashes do not match, possible tampering!
2015-09-21 18:37:31 - Origin: ControllerPaymentG2APay::ipn
2015-09-21 18:37:31 - Hashes do not match, possible tampering!

**Comment by chris-wm** [comment] 2015-09-25 10:45
@sterrek Hi, can you tell me if there is anything in the history for the order, possibly the status has been updated more than once, to completed and back again to pending.  Can you also update the following file catalog\controller\payment\g2apay.php with the one https://drive.google.com/file/d/0B0thHgBjXmj_eU5kZDlzNnIxMDg/view?usp=sharing, try again and tell me what appears in your log,
regards

**Comment by sterrek** [comment] 2015-09-28 18:20
@chris-wm i did what you said. now i still doesnt work.

Log files

)

2015-09-28 20:07:03 - Origin: ControllerPaymentG2APay::ipn
2015-09-28 20:07:03 - ipn
2015-09-28 20:07:03 - Origin: ControllerPaymentG2APay::ipn
2015-09-28 20:07:03 - token success
2015-09-28 20:07:03 - Origin: ControllerPaymentG2APay::ipn
2015-09-28 20:07:03 - Hashes do not match, possible tampering!
2015-09-28 20:07:03 - Origin: ControllerPaymentG2APay::ipn
2015-09-28 20:07:03 - ipn
2015-09-28 20:07:03 - Origin: ControllerPaymentG2APay::ipn
2015-09-28 20:07:03 - token success
2015-09-28 20:07:03 - Origin: ControllerPaymentG2APay::ipn
2015-09-28 20:07:03 - Hashes do not match, possible tampering!

**Comment by chris-wm** [comment] 2015-09-29 16:28
@sterrek were you able to check the order history to see if the status had been changed at any point?
Regards

**Comment by sterrek** [comment] 2015-09-30 11:48
i did not changed anything only to pending

**Comment by chris-wm** [comment] 2015-09-30 14:05
@sterrek I have updated the file with more debug, can you try again and post me the results,
regards

**Comment by sterrek** [comment] 2015-09-30 15:50
@chris-wm  i just get a white page right now. when i want to checkout with g2apay

**Comment by chris-wm** [comment] 2015-09-30 15:59
@sterrek Can you download the file again and upload once more, I have only made changes to the response code so it should not affect the checkout page.  Are there any errors in your log?
Regards

**Comment by sterrek** [comment] 2015-09-30 16:11
@chris-wm i left my api clear only for this page. so that not everybody can see it. but i still not forwarding to complete. btw thank you for helping !
)

2015-09-30 18:07:35 - Origin: ControllerPaymentG2APay::checkout
2015-09-30 18:07:35 - 3.87
2015-09-30 18:07:35 - Origin: ControllerPaymentG2APay::checkout
2015-09-30 18:07:35 - Array
(
    [0] => stdClass Object
        (
            [sku] => shipping
            [name] => Gratis verzending
            [amount] => 0.00
            [qty] => 1
        )

    [1] => stdClass Object
        (
            [sku] => 665
            [name] => HearthStone: Heroes of Warcraft (Deck of Cards DLC)
            [amount] => 3.87
            [qty] => 1
        )

)

2015-09-30 18:07:35 - Origin: ControllerPaymentG2APay::checkout
2015-09-30 18:07:35 - Array
(
    [api_hash] => 
    [hash] => 
    [order_id] => 123347
    [amount] => 3.87
    [currency] => EUR
    [email] => manuel_sterk@hotmail.com
    [url_failure] => https://actiehunt.nl/index.php?route=checkout/failure
    [url_ok] => https://actiehunt.nl/index.php?route=payment/g2apay/success
    [items] => [{"sku":"shipping","name":"Gratis verzending","amount":"0.00","qty":1},{"sku":"665","name":"HearthStone: Heroes of Warcraft (Deck of Cards DLC)","amount":3.87,"qty":"1"}]
)

2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - ipn
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - ipn
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - token success
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - token success
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - 3.87
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - 1233473.87Vz8D1@2rZz#OOHGHMWZXCU&YLJem4-9ZkIml9oNhYF!wW6?sbXAo_767QktUV=+<
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - 3.87
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - dd75105a3b5308def841e3f37b71432d50dbd91bd45fdd9f87c105266fe27aa5
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - 1233473.87Vz8D1@2rZz#OOHGHMWZXCU&YLJem4-9ZkIml9oNhYF!wW6?sbXAo_767QktUV=+<
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - 68667cb226fb8db1f2818dfec44b8cf202b5a1d20c4a0bbc11fe17ec2a0a2e15
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - dd75105a3b5308def841e3f37b71432d50dbd91bd45fdd9f87c105266fe27aa5
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - Hashes do not match, possible tampering!
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - 68667cb226fb8db1f2818dfec44b8cf202b5a1d20c4a0bbc11fe17ec2a0a2e15
2015-09-30 18:08:33 - Origin: ControllerPaymentG2APay::ipn
2015-09-30 18:08:33 - Hashes do not match, possible tampering!

**Comment by chris-wm** [comment] 2015-10-02 13:44
@sterrek Hi, can you ask G2A if they have something different for the string before it is hashed for that specific order number IPN.  The problem is that the hash they send does not match the one calculated by the module for security purposes, the info they might need is
* Order id - 123347
* pre hashed sting - 1233473.87Vz8D1@2rZz#OOHGHMWZXCU&YLJem4-9ZkIml9oNhYF!wW6?sbXAo_767QktUV=+<
* module hash - dd75105a3b5308def841e3f37b71432d50dbd91bd45fdd9f87c105266fe27aa5
* g2a hash - 68667cb226fb8db1f2818dfec44b8cf202b5a1d20c4a0bbc11fe17ec2a0a2e15
They should hopefully be able to shed some light on this,
regards

**Comment by sterrek** [comment] 2015-10-06 19:44
@chris-wm Thank you. i pasted this problem the g2a im still waiting on the answer of G2A IT department. But they are really slow in answering.

**Comment by sterrek** [comment] 2015-10-08 15:46
@chris-wm  Hi, this was there response today.

We are still waiting for respond from IT team, please check if you calculate hash from those variablles:

{transactionId}{userOrderId}{amount}{ApiSecret}
ApisSecret- you can find it at yor g2a pay account

**Comment by sterrek** [comment] 2015-10-21 22:21
@chris-wm hi they told me this. Could you may look at this: strange, i dont know if this is new/ updated by g2a or what but it seems like the required fields id, url and price for the products are missing in the call.

Iv'e edited:

    foreach ($ordered_products as $product) {


        $item = new stdClass();
        $item->sku = $product['product_id'];
        $item->name = $product['name'];
        $item->amount = $product['price'] * $product['quantity'];
        $item->qty = $product['quantity'];
        $items[] = $item;
    }

From the controller an changed it to:

    foreach ($ordered_products as $product) {


        $item = new stdClass();
        $item->sku = $product['product_id'];
        $item->name = $product['name'];
        $item->amount = $product['price'] * $product['quantity'];
        $item->price = number_format($product['price'], 2);
        $item->id = $product['model'];
        $item->url = "http://utcoinbets.co.uk/index.php?route=product/product&product_id=".$product['product_id'];
        $item->qty = $product['quantity'];
        $items[] = $item;
    }

Seemes to get rid of the error anyway, someone feel free to tell me if im wrong. Thanks

**Comment by chris-wm** [comment] 2015-10-22 09:41
@sterrek Hi, we actually received an email yesterday from G2A telling us that they wished to update their OpenCart gateway, it appears that they have updated their payment system so that the current OpenCart implementation is incompatible.  They sent me a patch that looks similar to yours but with a few extra bits, I cannot vouch for it's quality but we will be releasing a bug fix version of OpenCart with the official release at some point soon.  You can find the patch they sent me here https://drive.google.com/file/d/0B0thHgBjXmj_cUZSeGU1VU9JRHM/view?usp=sharing,
regards

**Comment by craigbaines** [comment] 2015-10-23 18:24
Hey, ive set up a store using the g2a for the first time a few days ago, im getting a few orders that are set to order status 0 (doesnt exist in my db), and will not show up in my order search, not even under missing orders,,, 

Any idea ? 

I just replaced the code with the patch you posted, hoping its solved in there but i dont know?

**Comment by craigbaines** [comment] 2015-10-25 11:58
was there any update on this?

I have the latest code you posted but the status is still not getting updated correctly.

**Comment by sterrek** [comment] 2015-10-25 12:07
@craigbaines hi,

I just got a messages from g2a. 
That they are testing the new plug in,
When i have it. i will send it here.

Kind regards.

**Comment by craigbaines** [comment] 2015-10-27 14:43
Ok thanks, still have issues here so that would be appreciated.

**Comment by danielkerr** [comment] 2016-01-19 12:56
sorry guys, G2APAY has changed their api without telling anyone.

we are in discussion to get them to cover the costs to update the api.

anyone want to jump in a create a new one for them?

**Comment by chris-wm** [comment] 2016-01-19 13:10
The patch for the updated G2A API was added in the following commit #8131e2fe53ab4731106aa96a4101149f6d2cae24 and will be included in the next release of OpenCart

**Closed** 2016-01-19 13:11 UTC
