### ISSUE TITLE
Important Issue - Can not get right unit price for different customer groups in "Edit Order" function at Admin Platform

### ISSUE THREAD

**Issue by CodyZhou** [opencart/opencart#6688] opened 2018-06-21 20:34 UTC
**Issue Description:**
    When i edit the order information for my customer in "Edit Order" function of page "Sales"->"Orders" at Admin Platform, i always get the original unit price for each product in the "products" tab and the "Totals" tab, although i set up the different discount price for different customer groups. BUT, the unit price in "View" function is correct, it is the discount price for different customer groups. 

**Issue Path:**
    In the page "Sales"->"Orders", click "Edit" button, then in the tab "Products" and tab "Totals".

**Issue Analysis:**
    In the file "admin/view/template/sale/order_form.tpl", it is use ajax to request the products data through the api - index.php?route=api/cart/products - which is in the catalog platform. BUT, this operation does not send the customer id  or something like this to identify the customer information or the order data. It gets the product data from the shopping cart , and gets the customer id by the way "$this->customer->getId()", and gets the default customer group id by the way "$this->config->get('config_customer_group_id')". So, if you have some different customer groups or you do not login by using the correct customer information, you can not get the correct unit price for each product.  You only can get the original unit price. If you do not need to edit the order, everything looks fine. BUT, if you have to edit any information of the order, the all prices will be changed to the original price in this order and you do not have any other way to change the price back. 

**Issue Version:**
    I am using the opencart V2.3 right now, but i confirm that this issue existed in the opencart version 3.0 and 3.0+.

**Comment by danielkerr** [comment] 2018-06-22 07:27
it sends the customer group that you define on the customer order edit part.

i will look into it.

**Comment by straightlight** [comment] 2018-06-22 17:55
It is indeed a bit puzzling on this one. In admin/view/template/sale/order_form.twig file, the store_id key and selected value is being passed in the URL of the api/cart/products . Although, when visiting the catalog/controller/api/cart.php file, there are no store_id key being found within the GET / POST super global.

In addition, in the admin/controller/sale/order.php file, in the getForm() method, the:

if (!empty($order_info)) {

statement is being validated versus the ELSE statement. However, the Ajax request in the order_form.twig file can already process what's been selected by the merchant when creating the order which means, unless missing something during the analysis, the current customer group ID is not mandatory to be used by default but rather add the customer_group_id along with the store_id in the Ajax URL of the api/cart/products request. Then, in the catalog/controller/api/cart.php file, to add the selected store_id and the selected customer_group_id into the order accordingly.

**Comment by CodyZhou** [comment] 2018-06-22 21:59
I am a little bit confuse about this. 

Right now, i have two customer groups in my OC system, but i just set up one store which is named default. In your mean, i should assign a store for each customer group, and assign a default customer group for each store, is that right? Is this the main reason that some of my orders got the wrong unit price, because these orders belong to another customer group?

**Comment by straightlight** [comment] 2018-06-22 23:11
`i should assign a store for each customer group, and assign a default customer group for each store`

Nowhere to be said but rather the other way and switched around. Although, as explained on the above, it is an odd issue since the Ajax request is sending the store_id but not the customer_group_id along with it and that the api/cart/products is neither validating those two variables which is rather the main reason that some orders might output wrong results.

**Comment by danijelGombac** [comment] 2018-06-23 05:42
@CodyZhou 

Can you check if your problem is related to this:

[OC 3.0.2.0 order doesn't handle customer group right](https://forum.opencart.com/viewtopic.php?f=201&t=201760)

**Comment by straightlight** [comment] 2018-06-23 11:59
The addressed issue is not about receiving a popup jQuery message indicating a custom field issue. This user is indicating that the selected store, compared with the customer groups, is not outputting the right store results when either creating / editing an order.

**Comment by danijelGombac** [comment] 2018-06-23 12:05
The posted link has nothing to with custom fields.

**Comment by CodyZhou** [comment] 2018-06-25 18:19
@danielkerr 
Thank you give me the link, the question in that link maybe the same but different. That link is talking about the customer group, but my question is talking about the product's unit price. Please let me show you my researching.

1. In the file admin/view/template/sale/order_form.twig, (about line 2311)
`
// Add all products to the cart using the api
$('#button-refresh').on('click', function() {
	$.ajax({
		url: '{{ catalog }}index.php?route=api/cart/products&api_token={{ api_token }}&store_id=' + $('select[name=\'store_id\'] option:selected').val(),
		dataType: 'json',
		crossDomain: true,
`
It gets the products information of the order by ajax through api/cart/products.

2. In the file: catalog/controller/api/cart.php about line 143:
`
// Get producs
$products = $this->cart->getProducts();
`
It gets the information by the function getProducts() of the cart class, which is the file system/library/cart/cart.php;

3. In the file: system/library/cart/cart.php about line 36 and line 177:
`
// line 36: get cart information by api_id, customer_id, session_id
$cart_query = $this->db->query("SELECT * FROM " . DB_PREFIX . "cart WHERE api_id = '" . (isset($this->session->data['api_id']) ? (int)$this->session->data['api_id'] : 0) . "' AND customer_id = '" . (int)$this->customer->getId() . "' AND session_id = '" . $this->db->escape($this->session->getId()) . "'");
`
At here, it get customer id by $this->customer->getId();
`
// line 177: get product discount information
$product_discount_query = $this->db->query("SELECT price FROM " . DB_PREFIX . "product_discount WHERE product_id = '" . (int)$cart['product_id'] . "' AND customer_group_id = '" . (int)$this->config->get('config_customer_group_id') . "' AND quantity <= '" . (int)$discount_quantity . "' AND ((date_start = '0000-00-00' OR date_start < NOW()) AND (date_end = '0000-00-00' OR date_end > NOW())) ORDER BY quantity DESC, priority ASC, price ASC LIMIT 1");
`
**At here, it get product discount information by $this->config->get('config_customer_group_id'), which is default customer group, not the customer group id in the order.**

I think the step 3 above is the main reason why i can not get the correct product unit price in the function "Edit Order";

**Comment by danijelGombac** [comment] 2018-06-25 19:07
@CodyZhou 

The customer_group_id is set in the tab customer:

upload/catalog/controller/api/customer.php

https://github.com/opencart/opencart/blob/0fdfc437c9be81a712e8cd6358612c3bb7f0c356/upload/catalog/controller/api/customer.php#L80,L88

is saved in session and is used to set  customer_group_id  in all next ajax call:

upload/catalog/controller/startup/startup.php.

https://github.com/opencart/opencart/blob/0fdfc437c9be81a712e8cd6358612c3bb7f0c356/upload/catalog/controller/startup/startup.php#L151,L159

The problem is here:

https://github.com/opencart/opencart/blob/0fdfc437c9be81a712e8cd6358612c3bb7f0c356/upload/catalog/controller/api/customer.php#L58,L62

you need to select (config_customer_group_display) customer group in settings page for used it in order edit page. If customer group is not selected then the system ignore the selection in order edit page and use the default config_customer_group_id.

**Comment by CodyZhou** [comment] 2018-06-25 20:40
@danijelGombac 
Thank you very much, this answer is very useful. I think i figure out the reason. For the business reason, we do not want the special customer group displayed in the register page, so we do not select the special  customer group in the store setting page. Right now, i know how to resolve this issue.

**Comment by straightlight** [comment] 2018-06-25 21:46
It still doesn't explain why the order_form TWIG file has the store_id with the api/cart/products route since that API file doesn't have any store ID in it. As for checking the array solution, there are also controller files that might need to add the 'is_array' as well before checking the actual array - such as processing status and complete status. I will add these files on a new topic shortly.

**Comment by SFSF99** [comment] 2019-01-29 17:47
This bug have not been solved. 
A customer may not choose a customer group at registration (in our case), so I don't check customer groups in settings to solve this problem. 
The problem is in this bug that catalog/controller/startup/startup.php not have been called, so $this->config->get('config_customer_group_id') have not been set to the right customer group to retrieve prices in a product for a customer group!

**Comment by danielkerr** [comment] 2020-10-18 17:25
i think fixed in master branch

**Comment by WebkulOpencart** [comment] 2020-12-29 06:15
I have added the default customer group so closing the same.

**Closed by WebkulOpencart** 2020-12-29 06:15 UTC
Labels: maintenance-branch 3.0.x.x
