### ISSUE TITLE
Error opencart Log Errors

### ISSUE THREAD

**Issue by bpshbp** [opencart/opencart#5103] opened 2016-12-27 06:54 UTC
Below are opencart Log Errors im unable to fix can you help please
I'll not be able to share client url
[img]http://bpshbp.ipage.com/wp-content/uploads/2016/12/Capture.jpg[/img]

**Comment by arnisjuraga** [comment] 2016-12-27 08:34
1. fix image url - github 
~~~
![image](http://bpshbp.ipage.com/wp-content/uploads/2016/12/Capture.jpg)
~~~
 
2. your log file does not show error message, just "line where it appears". But as far as I can see - this is not a problem of Opencart, but most probably - you do not have translations or some php variables, as these are not "errors" but "notices". And it seems the problem is in Theme "Journal2", not Opencart.

![image](https://cloud.githubusercontent.com/assets/2185289/21495446/19ae33a8-cc20-11e6-89b9-df8996ff415a.png)

**Comment by bpshbp** [comment] 2017-01-20 15:36
ty

**Comment by arnisjuraga** [comment] 2017-01-23 10:07
Please, close the issue then.

**Closed** 2017-02-15 11:19 UTC
