### ISSUE TITLE
Session logout and admin page login loop after changing System > Local settings.

### ISSUE THREAD

**Issue by garygan89** [opencart/opencart#9667] opened 2021-05-19 03:32 UTC
**What version of OpenCart are you reporting this for?**
opencart-3.0.3.7

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Admin store login loop after changing any settings under `Settings > Store` such as time zone, and saved settings. Other section such as General, Store, Image, Mail and Server are fine. I had to reinstall everything to make it work again. Checked the apache virtual host log and error log but nothing significant is shown. 

I suspect it could be related to session cookies settings.

**To Reproduce**
1. Go to Admin store page.
2. Click on 'System'
3. Click on 'Local' tab.
4. Make any changes such as time zone, and save
5. Click any other options and the session will be logout
6. Login using the correct admin username and password again
7. The page will just redirect to the same login screen without any warning.

**Expected behavior**

The store settings should be saved and the session shouldn't be logout ('kicked') after saving the [Local] settings and clicking other option. 

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

![image](https://user-images.githubusercontent.com/2649703/118752307-d536a000-b830-11eb-949b-1076e0eceb2e.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Deployed on Dedicated Server hosted on cloud
 - Operating system: Ubuntu 18.04
 - PHP version 7.3 (with Zend OPcache v7.3.28-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies)
 - Apache version: Apache/2.4.29 (Ubuntu)
 - Browser(s) tested with [e.g. chrome, safari - if applicable]: Firefox, Chrome, Edge

**Additional context**

**Comment by WebkulOpencart** [comment] 2021-05-20 04:09
@garygan89 please follow this comment [https://github.com/opencart/opencart/issues/6996#issuecomment-440163494](https://github.com/opencart/opencart/issues/6996#issuecomment-440163494)

And your issue will be resolved.

**Comment by ADDCreative** [comment] 2021-05-20 08:51
Seems like a duplicate of https://github.com/opencart/opencart/issues/9237.

**Comment by ADDCreative** [comment] 2021-05-20 08:59
> @garygan89 please follow this comment [#6996 (comment)](https://github.com/opencart/opencart/issues/6996#issuecomment-440163494)
> 
> And your issue will be resolved.

@WebkulOpencart The advice at that link would be pointless as the default time zone gets set back to UTC at startup.

https://github.com/opencart/opencart/blob/2a5b358003d1e9e4af964eda2ffcb79abe8229ce/upload/system/startup.php#L11

**Comment by WebkulOpencart** [comment] 2021-05-21 03:40
@garygan89 Please also try this solution
[https://github.com/opencart/opencart/issues/7622#issuecomment-534916483](https://github.com/opencart/opencart/issues/7622#issuecomment-534916483)

**Closed by WebkulOpencart** 2021-05-21 03:40 UTC
Labels: maintenance-branch 3.0.x.x

**Comment by zawarnac** [comment] 2022-03-16 07:11
> @garygan89 Please also try this solution [#7622 (comment)](https://github.com/opencart/opencart/issues/7622#issuecomment-534916483)

It works for me. (y)
