### ISSUE TITLE
Installation Error:Undefined index: db_hostname, etc database info 

### ISSUE THREAD

**Issue by sooglejay** [opencart/opencart#5120] opened 2017-01-04 16:14 UTC
I cannot install opencart successfully in that some error occur at database info configuration, however,  my local database which is easy to access ,  and I can also login in and handle the local database through phpMyAdmin. Thanks for your attension.

![98a62422-5515-444a-9713-a2934bb913e9](https://cloud.githubusercontent.com/assets/6687300/21649031/37bb379e-d2db-11e6-90c5-e8a90ea71445.png)

![869a6621-c68b-45a2-ab09-3e2ba657b7c5](https://cloud.githubusercontent.com/assets/6687300/21648992/094aff84-d2db-11e6-920f-a4d671519741.png)

**Comment by arnisjuraga** [comment] 2017-01-04 16:48
This is something really strange. Have no idea! :)

I doubt, it's  a bug in Opencart, because I have never seen anything like this.
At the same time - it seems has nothing to do with a database. 

1. Which OC version?
2. Linux or Windows?
3. Can you monitor WEB browser Debug Console log? You may have some plugins or extensions blocking installation/posting process (although, I cannot reproduce it)?
4. Look for web hosting `error log` and `system/storage/logs/error.txt`. Any additional entries?

**Comment by Icebox-Studio** [comment] 2017-01-05 00:41
Shouldn't it be localhost/oc/install (and not localhost/oc/upload/install)? Maybe you didn't dump the contents of the install folder correctly?

**Comment by arnisjuraga** [comment] 2017-01-05 08:03
I did a test exactly with a "upload" folder. It should still work correctly, it does not matter, I have used sites with example.com/subfloder/ .... as OC store, it should work. I believe, there is something else. 
And error messages are not from file config, but from `$this->request->get['']` array index.

**Comment by sooglejay** [comment] 2017-01-06 05:36
since I am instant to code my project, I fix this error by reinstalling mysql and some of my php modules. I will review this and try to find solution when I am free. Thanks for your favor.

**Comment by arnisjuraga** [comment] 2017-01-06 12:52
You could close it for now then, as it's not a usual issue, and reopen or just comment, when you will return.

**Closed** 2017-01-10 06:50 UTC
