### ISSUE TITLE
Problem with db settings and library

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#3772] opened 2016-01-04 13:55 UTC
In the new OC system it's imposible to use db settings in the autoload libraries __construct functions, because all settings from db is defined in action.pre_action after 'library.autoload'.

Do i need to create a pre action for specific library or is there another way to get db config settings in the library?

**Comment by danielkerr** [comment] 2016-01-04 14:54
I will add the functionality to do this. unless you want to do the commit? i can make any changes later

**Comment by GomDani** [comment] 2016-01-04 23:25
I try to fix this and i change config.php in:

```
<?php
class Config {
	private $registry;
	private $data = array();

	public function __construct($registry) {
		$this->registry = $registry;
	}

	public function get($key) {
		return (isset($this->data[$key]) ? $this->data[$key] : null);
	}

	public function set($key, $value) {
		$this->data[$key] = $value;
	}

	public function has($key) {
		return isset($this->data[$key]);
	}

	public function load($filename) {
		$file = DIR_CONFIG . $filename . '.php';

		if (file_exists($file)) {
			$_ = array();

			require($file);

			$this->data = array_merge($this->data, $_);
		} else {
			trigger_error('Error: Could not load config ' . $filename . '!');
			exit();
		}
	}

	public function setting($application) {
		$this->db = $this->registry->get('db');

		$sql = "SELECT * FROM `" . DB_PREFIX . "setting` WHERE `store_id` = '0'";

		if ($application = 'catalog') {
			if ($_SERVER['HTTPS']) {
				$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "store` WHERE REPLACE(`ssl`, 'www.', '') = '" . $this->db->escape('https://' . str_replace('www.', '', $_SERVER['HTTP_HOST']) . rtrim(dirname($_SERVER['PHP_SELF']), '/.\\') . '/') . "'");
			} else {
				$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "store` WHERE REPLACE(`url`, 'www.', '') = '" . $this->db->escape('http://' . str_replace('www.', '', $_SERVER['HTTP_HOST']) . rtrim(dirname($_SERVER['PHP_SELF']), '/.\\') . '/') . "'");
			}

			if ($query->num_rows) {
				$this->set('site.base', substr($query->row['config_url'], 7));
				$this->set('site.ssl', substr($query->row['config_ssl'], 8));
				$this->set('config_store_id', $query->row['store_id']);

				$sql .= " OR `store_id` = '" . (int)$query->row['store_id'] . "' ORDER BY `store_id` ASC";
			} else {
				$this->set('config_url', HTTP_SERVER);
				$this->set('config_ssl', HTTPS_SERVER);
				$this->set('config_store_id', 0);
			}
		}

		$query = $this->db->query($sql);

		foreach ($query->rows as $setting) {
			if (!$setting['serialized']) {
				$this->set($setting['key'], $setting['value']);
			} else {
				$this->set($setting['key'], json_decode($setting['value'], true));
			}
		}
	}
}
```

and add in application:

```
$config = new Config($registry);
```

instead

```
$config = new Config();
```

and after

```
// Database
if ($config->get('db.autostart')) {
	$registry->set('db', new DB($config->get('db.type'), $config->get('db.hostname'), $config->get('db.username'), $config->get('db.password'), $config->get('db.database'), $config->get('db.port')));
}
```

```
// Config settings
$config->setting($application_config);
```

And remove startup settings files and pre_actions. It is seems to work. Can you take a look.

**Comment by danielkerr** [comment] 2016-01-05 07:52
what about 

$_['db.autostart']         = false;

**Comment by danielkerr** [comment] 2016-01-05 07:55
ok 1 sec

**Comment by GomDani** [comment] 2016-01-05 08:05
You can move $config->setting($application_config); into if ($config->get('db.autostart')) {}, but then you can't use db settings in autoload libraries and how libraries with db needs are working if there is no db.

**Comment by danielkerr** [comment] 2016-01-05 08:08
if you look under 

system/application.php

you see

// Database
if ($config->get('db.autostart')) {
	$registry->set('db', new DB($config->get('db.type'), $config->get('db.hostname'), $config->get('db.username'), $config->get('db.password'), $config->get('db.database'), $config->get('db.port')));
}

the autoload will add the registry into the loaded class.

it could be chenged though to 

$autoload[] = (
 'name' => 'db'
'config' => 'dbconfig'
)

whats the class you are trying to autoload?

**Comment by GomDani** [comment] 2016-01-05 08:16
The tax library does not working because there is need for:
```
$this->setShippingAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
$this->setPaymentAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
$this->setStoreAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
```

**Comment by danielkerr** [comment] 2016-01-05 09:15
im still nto sure what you mean.

autoloading libraies are set here:

// Autoload Libraries
$_['library.autoload'] = array(
	'cart/customer',
	'cart/affiliate',
	'cart/currency',
	'cart/tax',
	'cart/weight',
	'cart/length',
	'cart/cart',
	'openbay'
);

all have the registry passed to them.

In the system/config/catalog.php

// Database
$_['db.autostart']         = true;

Db is set to auto start and is called before any libraries are auto loaded.

I will check the taxes now.

**Comment by danielkerr** [comment] 2016-01-05 09:17
ok i see the issue now.

**Comment by danielkerr** [comment] 2016-01-05 09:22
the issue is the settings not loaded into the config value before autoload.

**Comment by GomDani** [comment] 2016-01-05 09:23
My class for seo is depend of if ($this->config->get('config_seo_url')) {] and without db config is not working. Now i must write a pre_action or set seo_url enabled in config catalog file. But i think the best way is to get db settings in autoload libraries.

**Comment by GomDani** [comment] 2016-01-05 09:27
And 

```
$response->setCompression($config->get('config_compression'));
```

is also set in db config.

**Comment by danielkerr** [comment] 2016-01-05 09:43
any classes that need to be configured before they are used site wide should be done in a controller  startup action.

**Comment by GomDani** [comment] 2016-01-05 09:59
I think you need to also add length and weight to startup, because of config_language_id.

**Comment by eka7a** [comment] 2016-01-13 12:48
@danielkerr 

```php
$data['test'] = $this->weight->getUnit(1);
```
or

add weight library and run function

```php
public function test() {
     return $this->weights;
}
```
result empty array

**Comment by danielkerr** [comment] 2016-01-16 06:24
should be fixed in latest commit

**Closed by danielkerr** 2016-01-16 06:24 UTC
