### ISSUE TITLE
Fatal error: Call to undefined method Language::all()

### ISSUE THREAD

**Issue by waxedperfection** [opencart/opencart#5387] opened 2017-04-20 10:23 UTC
Opencart 2.3.0.3_rc - Default theme - not using openbay.

in the admin page in a customer order i get the following - just below order history

Fatal error: Call to undefined method Language::all() in 

/vqmod/vqcache/vq2-admin_controller_extension_openbay.php on line 477

had a good look around google, but sadly found nothing.

**Comment by ADDCreative** [comment] 2017-04-20 11:07
Probably due to the vQmod extensions you are using. Best ask in the forums.

**Comment by jamesallsup** [comment] 2017-04-20 11:29
Yeah it was caused by the method being removed from that OC version - the 5153 issue has a work around for older versions but will be patched on the next one once OBP updates are merged.

https://github.com/opencart/opencart/issues/5153

I'm closing this as it is a duplicate but the other issue remains open.

**Closed by jamesallsup** 2017-04-20 11:29 UTC

**Comment by waxedperfection** [comment] 2017-04-20 11:51
Thank you, James. as you say the 5153 has a work around for old versions, do you / anyone have a work around for current versions? 2.3.0.3_rc as i tried that and i didn't work sadly.

**Comment by jamesallsup** [comment] 2017-04-20 11:53
which version are you using?

**Comment by waxedperfection** [comment] 2017-04-20 11:55
Version 2.3.0.3_rc

**Comment by jamesallsup** [comment] 2017-04-20 12:07
Not a problem :)

You would need to clear the vqmod cache after updating the language.php file - it might get cached by other modules using it. Try that first but if not you could also try:

CHANGE THIS:
```
		$this->load->language('extension/openbay');

		$data = $this->language->all();
```
TO THIS:
```
		$data = $this->load->language('extension/openbay');
```
(i.e. remove the second line and move the $data var). The other option is better though as it would ensure it works if used elsewhere too. Hope it helps. J

**Comment by waxedperfection** [comment] 2017-04-20 12:38
OK after each change i cleared the vqmod cache, but sadly im still getting the error, maybe in doing something wrong, i feel that im doing ok. but if you would like to take a look im all for supporting opencart to get this working not just for me but others on 2.3.0.3. (of course i can supply ftp and admin) if you would like to take a closer look. 

one crazy thing did happen when i edited the language file was it but the store in maintenance mode. 

:)

**Comment by waxedperfection** [comment] 2017-04-20 15:03
@jamesallsup 

Thank you, the error has now gone in 2.3.0.3_rc, i didnt see there was more than one occurrence of : 

$this->load->language('extension/openbay');

		$data = $this->language->all();

within admin/controller/extension/openbay.php

This worked >> $data = $this->load->language('extension/openbay');

Thank you again, if your in Nott's any time soon, you have a beer waiting. 

Ste

**Comment by howdu** [comment] 2017-05-12 11:05
If you don't use openbay and causes errors it's better to remove it from the order info, otherwise it makes unnecessary ajax requests each time you view an order. 

```xml
<?xml version="1.0" encoding="utf-8"?>
<modification>
  <name>Remove Openbay</name>
  <code>remove_openbay</code>
  <version>1.0</version>
  <author>Howdu</author>
  <file path="admin/view/template/sale/order_info.tpl">
    <operation info="Remove openbay unnecessary ajax requests">
      <search index="0"><![CDATA[function changeStatus(){]]></search>
      <add position="replace" offset="31"></add>
    </operation>
  </file>
</modification>

```
