### ISSUE TITLE
Loader bug

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#5338] opened 2017-04-06 23:03 UTC
Controller return instanceof Exception.

`exception 'Exception' with message 'Error: Could not call extension/fraud/ip/order!' in C:\wamp\www\ThisShop\system\engine\action.php:53 Stack trace: #0 C:\wamp\www\ThisShop\system\engine\loader.php(22): Action->execute(Object(Registry), Array) #1 C:\wamp\www\ThisShop\admin\controller\sale\order.php(1069): Loader->controller('extension/fraud...') #2 [internal function]: ControllerSaleOrder->info() #3 C:\wamp\www\ThisShop\system\engine\action.php(51): call_user_func_array(Array, Array) #4 C:\wamp\www\ThisShop\admin\controller\startup\router.php(22): Action->execute(Object(Registry), Array) #5 [internal function]: ControllerStartupRouter->index() #6 C:\wamp\www\ThisShop\system\engine\action.php(51): call_user_func_array(Array, Array) #7 C:\wamp\www\ThisShop\system\engine\router.php(34): Action->execute(Object(Registry)) #8 C:\wamp\www\ThisShop\system\engine\router.php(29): Router->execute(Object(Action)) #9 C:\wamp\www\ThisShop\system\framework.php(178): Router->dispatch(Object(Action), Object(Action)) #10 C:\wamp\www\ThisShop\system\startup.php(68): require_once('C:\\wamp\\www\\Thi...') #11 C:\wamp\www\ThisShop\admin\index.php(12): start('admin') #12 {main}`

**Comment by mhcwebdesign** [comment] 2017-04-07 21:32
Unable to reproduce this. You don't mention enough details to reproduce this error. What is your OC version?

**Comment by danijelGombac** [comment] 2017-04-07 22:27
Download dev. Install and add customer. Install and enable fraud IP. Add order and then go to view. There is tab  Anti-Fraud IP  and when open it the error is there.

**Comment by danijelGombac** [comment] 2017-04-07 22:32
In the loader is:

```
if ($result != null && !$result instanceof Exception) {
	$output = $result;
} else {
	$action = new Action($route);
	$output = $action->execute($this->registry, array(&$data));			
}
```

if you add before the last return:

```
if ($output instanceof Exception) {
	return false;
}
```

the error is gone.

**Comment by danielkerr** [comment] 2017-04-09 11:14
should be fixed in the last commit

**Comment by danijelGombac** [comment] 2017-04-09 13:07
Download dev branch and try again, the error is not fixed.

**Comment by danielkerr** [comment] 2017-04-10 09:47
fixed this time

**Closed by danielkerr** 2017-04-10 09:47 UTC
