### ISSUE TITLE
2.3.0.2 Printing invoice overlaps with header

### ISSUE THREAD

**Issue by dabishan** [opencart/opencart#4931] opened 2016-10-04 22:50 UTC
If you are printing more than one order, an unnecessary order table header overlaps with the next invoice head. 
<img width="1100" alt="screen shot 2016-10-04 at 3 49 24 pm" src="https://cloud.githubusercontent.com/assets/4493447/19095481/a50fa6ce-8a4a-11e6-9ead-b644d3ded1a0.png">

**Comment by schiggi** [comment] 2016-10-10 15:35
I can confirm that. The same happens in 2.1.0.2.

**Comment by RichardThomas1** [comment] 2016-10-21 22:17
I also found that it started doing this - duplicating the table headings at the top of the invoice on pages 2 onwards (but not page 1) all of a sudden a few weeks ago on Chrome (but not other browsers).

For the last week however it suddenly stopped doing this but instead the text is now extremely small and formatting is lost so can no longer use Chrome for printing invoices at all. Formatting is fine on screen but does not print the same (Chrome Version 54.0.2840.71 m).

In Explorer however it always prints an additional blank page (one invoice or multiple there is always an additional page). (Explorer 11.321.14393.9).

OC 2.3.0.2

**Comment by tyler-x** [comment] 2016-10-24 17:16
I have the same issue, temp fixed by removing all the thead and tfoot tags.

**Comment by schiggi** [comment] 2016-10-27 08:19
Same issue....seems to be a bug in Chrome.

**Comment by danielkerr** [comment] 2017-06-09 06:46
just tested its working fine in the dev branch. i added enough products until the product list went to the 2nd page and it pushed the next order to the next sheet of paper.

**Closed by danielkerr** 2017-06-09 06:46 UTC
