### ISSUE TITLE
edit image does not work in admin panel

### ISSUE THREAD

**Issue by asmaDur-01** [opencart/opencart#8987] opened 2020-12-19 17:51 UTC
I am using opencart version 3.0.2

I can't upload or edit images in admin panel, I have tried replacing admin folder but also doesn't work

**Comment by WebkulOpencart** [comment] 2020-12-20 12:37
Can you please share the screenshot of the issue which you are facing so that we can look in to the same.

**Comment by mhcwebdesign** [comment] 2020-12-20 12:44
@asmaDur-01: The image editor works just fine on an OpenCart 3.0.2.0. This is not an OpenCart bug for that version. Please repost it on the OpenCart forum, with more details. Your issue is most likely caused by dodgy 3rd party extensions.

**Comment by asmaDur-01** [comment] 2020-12-20 14:00
> Can you please share the screenshot of the issue which you are facing so that we can look in to the same.

![image](https://user-images.githubusercontent.com/74511966/102715060-c67ca900-42e3-11eb-8288-458a0549e79a.png)

 when I click on edit pencil, it doesn't open image manager

**Comment by asmaDur-01** [comment] 2020-12-20 14:02
> @asmaDur-01: The image editor works just fine on an OpenCart 3.0.2.0. This is not an OpenCart bug for that version. Please repost it on the OpenCart forum, with more details. Your issue is most likely caused by dodgy 3rd party extensions.

Actually it worked fine, but now I don't know why it doesn't work

**Comment by WebkulOpencart** [comment] 2020-12-20 14:09
@asmaDur-01 Please check the console for the error. Maybe your any of the third-party extension causing the issue. 
Also, please report the same on the Opencart forum. 
As you are reported the older version issue so closing this issue.

**Closed by WebkulOpencart** 2020-12-20 14:09 UTC
Labels: 3.0.x.x Maintenance
