### ISSUE TITLE
Back-end order creation taxes - 2.2.0

### ISSUE THREAD

**Issue by tentoseven** [opencart/opencart#4887] opened 2016-09-15 14:21 UTC
Seems that when creating an order in the back-end - which uses the user API - the tax class applied is based on the front-end logged-in customer, not the customer that you're adding an order for.

So where a customer is potentially in a customer group with a zero tax rate, they actually end up having tax applied based on the customer group of the logged-in customer.

Not got a workaround for this yet but am stepping through the process.

**Comment by danielkerr** [comment] 2016-09-16 03:53
completly sperate session for storgin the tax rates!

maybe your not using the latest version or you have taxes messed up

**Comment by tabarjack** [comment] 2016-09-30 22:44
No, I have the same issue. Some people can't load session data before checking if the session data exists. But hey, it's free, can't expect it all to work without patching it yourself.
You can hack patch it by adding :

`		if (isset($this->session->data['shipping_address'])) {
			$this->tax->setShippingAddress($this->session->data['shipping_address']['country_id'], $this->session->data['shipping_address']['zone_id']);
		} elseif ($this->config->get('config_tax_default') == 'shipping') {
			$this->tax->setShippingAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
		}

		if (isset($this->session->data['payment_address'])) {
			$this->tax->setPaymentAddress($this->session->data['payment_address']['country_id'], $this->session->data['payment_address']['zone_id']);
		} elseif ($this->config->get('config_tax_default') == 'payment') {
			$this->tax->setPaymentAddress($this->config->get('config_country_id'), $this->config->get('config_zone_id'));
		}
            `

In /controller/api/cart at the very beginning of the products function.

**Comment by tentoseven** [comment] 2016-10-01 01:28
Funny that it works when you log in as the relevant customer before placing
the order in the back end.

Which negates your theory. The session must be the same.

I've diffed the latest version and stand by my bug report.

I'm also not an amateur - the tax rates are correct. It's a session issue
and a back-end issue.

**Comment by danielkerr** [comment] 2017-06-07 10:46
this is fixed on the dev since it creates taxes on a separate session

**Comment by danielkerr** [comment] 2017-06-07 10:47
im not fixing issues from older version just ones with the current dev.

**Closed by danielkerr** 2017-06-07 10:46 UTC

**Comment by danielkerr** [comment] 2017-06-07 10:49
if the issue is still in the current version open another ticket with better explanation of the issue and how to fix.
