### ISSUE TITLE
re #4514 : bug in new event system in OC 2.2.0.0

### ISSUE THREAD

**Issue by igorokb** [opencart/opencart#4518] opened 2016-06-16 11:55 UTC
The following error message was caught (please see the ticket #4514 for more information, since it was immediately closed)

> Exception: Error: Could not load model ! in /var/www/devhost.sergey/html/system/storage/modification/system/engine/loader.php on line 146

The issue appears on PHP 5.3, meanwhile on PHP 5.4+ it is ok.
Please see the code snippet which is a short reflection of the event system process (you can try it in sandbox http://sandbox.onlinephpfunctions.com/code/19beca3ff08d457b5ef4df82c1fa424bb088a936):

```
$route = 'route';
$c = array(&$route);

function eventHandler($param) {
    $param = 'new value';
}

var_dump($c);
call_user_func_array('eventHandler', $c);
var_dump($c);

```

This will give you different results in PHP 5.3 and PHP 5.4

For PHP 5.3 it will be:

```
array(1) {
  [0]=>
  &string(5) "route"
}
array(1) {
  [0]=>
  &string(9) "new value"
}
```

For PHP 5.4 it will be:

```
array(1) {
  [0]=>
  &string(5) "route"
}
array(1) {
  [0]=>
  &string(5) "route"
}

```

Hope it is enough to see the problem

**Comment by wellic** [comment] 2016-06-16 12:07
It may be relative to Notes to the function: http://php.net/manual/en/function.call-user-func-array.php

The php 5.4+ has different behaviour than php 5.3
Thus developers should be careful when use construnction in php 5.3 as call_user_func_array(callback, array(&$var)).

**Comment by danielkerr** [comment] 2016-06-16 12:33
>  since it was immediately closed)

you posted 22 hours ago, i look at it and closed it 10 hours later after you provide no important information!

you need to be careful how you word things!

**Comment by danielkerr** [comment] 2016-06-16 12:41
I'm assuming this is some custom coding your trying to implement?

**Comment by danielkerr** [comment] 2016-06-16 12:47
if your posting this issue because you got stuck buildign an extension then your wasting my time!

as long as the shop works without any mods or changes on php 5.3 then your wasting my time.

because im now tryign to install a version of php5.3 just to test. 

so be very clear why have you posted this issue?

**Comment by igorokb** [comment] 2016-06-16 12:47
Actually yes. It was noticed while resolving compatibility issues in some of our modules with the new OC version. Since we now aware of this behavior, we handled such situation in our module. However the issue clearly can affect on any module, which uses the new event system and runs OC on PHP 5.3.

**Comment by danielkerr** [comment] 2016-06-16 12:50
I dont give a f**k about 3rd party modules! i have been working since 9am this morning and its now 9pm. 

im not here to fix problems you are having with your extensions! use the forum next time!

there is no bug!

**Closed by danielkerr** 2016-06-16 12:50 UTC

**Comment by igorokb** [comment] 2016-06-16 12:52
ok, got it. Have now questions. And won't have in future be sure of that

**Comment by andreymishenin** [comment] 2016-06-16 13:01
Daniel, seems like you're missing the point. It's not about any third party extension. You don't take into account specific features (bugs) of PHP 5.3 vs. PHP 5.4

**Comment by danielkerr** [comment] 2016-06-16 13:26
@andreymishenin  i did take into account the php 5.4 issue when i wrote the event system. 

the issue is 3rd party devs are not taking into account the php situation when they are creating extensions!

**Comment by andreymishenin** [comment] 2016-06-16 13:28
So, I guess it means there is no official support for PHP 5.3 in the latest OC version?

**Comment by danielkerr** [comment] 2016-06-16 15:27
@andreymishenin  what are you talking about!!!

use your brain! magic methods will not pass vars by reference unless they are in an array. this is the issue with 5.4! 

order totals work this way!

its a PHP issue not opencarts! there is no fix for passing by reference in php 5.4. 

nothing needs to be changed for php 5.3as it works both ways.

**Comment by andreymishenin** [comment] 2016-06-16 15:38
PHP issues should be taken into account by programmers and properly handled in code. That's why their list these issues on their site. But taking into account the tone of your messages it makes no sense to continue. I believe people here wanted to help to fix a problem in the implementation but your reaction is weird.

Cheers!

**Comment by danielkerr** [comment] 2016-06-16 15:45
by people you mean just 2. there is no fix for magic methods and passing by reference.

**Comment by danielkerr** [comment] 2016-06-17 03:52
@andreymishenin

your taking out of your ass!
