### ISSUE TITLE
[3.0.x.x] Error A Shipping Mehtod Is Required

### ISSUE THREAD

**Issue by WebSpectrum** [opencart/opencart#13740] opened 2024-02-28 02:51 UTC
**What version of OpenCart are you reporting this for?**
3.0.x.x (28th Feb 2024)
**Describe the bug**
Checkout area, when flat rate shipping is the only shipping method an error prevents checkout 'A Shipping Mehtod Is Required'

**To Reproduce**
1. Clean version of 3.0.x.x
2. Do a test checkout with only flat rate shipping enabled as the shippig method
3. When you get to delivery method stagem flat rate shipping is selected by default, click he continue button
4. Error ' 'A Shipping Mehtod Is Required' and you are unable to continue

**Expected behavior**
should be able to proceed to payment

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Live server
 - Cloud linux
 - PHP 8.2
 - Apache version
 - Chrome/FF
 - Latest versions of browsers

**Additional context**

**Comment by osworx** [comment] 2024-02-28 03:45
Testing the (pre) 3.0.4.0 version and see no problem when there is only flat rate as single shipping method.

**Comment by WebSpectrum** [comment] 2024-02-28 05:00
Weird, I tested on FF/Chrome and the same on fresh install of 3.0.x.x : https://ibb.co/0JbjT2x

**Comment by osworx** [comment] 2024-02-28 06:58
Okay, justed tested it out ot curiosity also with Chrome (latest version) - done it before with FF.
Same result: no errors or anything else.
Don't know what you are doing, have also php 8.2.x (local as XAMPP and live) - must be something wrong at your site ..

**Comment by mhcwebdesign** [comment] 2024-02-28 12:03
Perhaps give us your website URL, so someone can test it, because nobody is able to reproduce it on their own servers.

**Comment by mhcwebdesign** [comment] 2024-03-02 12:17
Since nobody else can reproduce this issue, and with the lack of further details, we'll close this issue for now.

**Closed by mhcwebdesign** 2024-03-02 12:17 UTC
Labels: 3.0.x.x
