### ISSUE TITLE
Issue at Installation Step 3

### ISSUE THREAD

**Issue by krishna-7** [opencart/opencart#9785] opened 2021-07-22 19:00 UTC
**What version of OpenCart are you reporting this for?**
OC : 3.0.3.7

**Describe the bug**
During step3 of installation it is throwing Internal Server Error, DB tables are created but a blank screen is displayed and checked installation but its not proper.

**To Reproduce**
1. Deploy Latest code to a linux web server
2. Run Installation
3. During Step 3 (DB setup), screen freezes
4. See error Internal Server Error

**Expected behavior**
After Installation user must be redirected to Step 4 page.

**Screenshots / Screen recordings**
![InternalServerError](https://user-images.githubusercontent.com/10972564/126693805-14ba1c8e-3fed-4fd3-848d-a98c461e4bc4.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? : Deployed to a web server
 - Operating system : Ubuntu 20.04
 - PHP version : 8.0.8
 - Apache version : Apache/2.4.41 
 - Browser(s) tested with : Firefox, Chrome
 - Version {90.0.4, 91.0.4472.164 }

**Additional Comments**
Code from OC git was working fine till last week. Today I cloned the latest files and this issue happened.

**Comment by mhcwebdesign** [comment] 2021-07-23 10:37
Your error report will be pretty useless, unless you can also provide the details from your Apache server's error log which is usually located at **/var/log/apache2/error.log**. This will tell you about the nature of your Internal Error 500.

**Comment by WebkulOpencart** [comment] 2021-07-23 11:18
@krishna-7 Please enable the error reporting.
I just checked by installing the same but didn't found any such issue.

**Comment by krishna-7** [comment] 2021-07-24 08:17
I still had the same error, I have tried multiple times. 

[Sat Jul 24 12:19:37.459747 2021] [php:error] [pid 196808] [client 103.66.79.201:43965] PHP Fatal error:  Uncaught Excepti
on: Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'<br />Error No: 1231<br />SET @@session.sql_mode = 'M
YSQL40' in /var/www/html/system/library/db/mysqli.php:41\nStack trace:\n#0 /var/www/html/system/library/db.php(45): DB\\My
SQLi->query()\n#1 /var/www/html/install/model/install/install.php(35): DB->query()\n#2 /var/www/html/system/engine/loader.
php(248): ModelInstallInstall->database()\n#3 /var/www/html/system/engine/proxy.php(47): Loader->{closure}()\n#4 /var/www/
html/install/controller/install/step_3.php(11): Proxy->__call()\n#5 /var/www/html/system/engine/action.php(79): Controller
InstallStep3->index()\n#6 /var/www/html/system/engine/router.php(67): Action->execute()\n#7 /var/www/html/system/engine/ro
uter.php(56): Router->execute()\n#8 /var/www/html/system/framework.php(169): Router->dispatch()\n#9 /var/www/html/system/s
tartup.php(104): require_once('...')\n#10 /var/www/html/install/index.php(37): start()\n#11 {main}\n  thrown in /var/www/h
tml/system/library/db/mysqli.php on line 41, referer: http://mymunchbox.in/install/index.php?route=install/step_3

[Sat Jul 24 12:36:15.091403 2021] [php:warn] [pid 196808] [client 103.66.79.201:44870] PHP Warning:  fopen(/var/www/html/s
ystem/storage/logs/error.log): Failed to open stream: Permission denied in /var/www/html/system/library/log.php on line 22

[Sat Jul 24 12:36:15.125825 2021] [php:error] [pid 196808] [client 103.66.79.201:44870] PHP Fatal error:  Uncaught TypeErr
or: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /var/www/html/system/library/log.php:31\nStack
trace:\n#0 /var/www/html/system/library/log.php(31): fwrite()\n#1 /var/www/html/system/framework.php(46): Log->write()\n#
2 [internal function]: {closure}()\n#3 /var/www/html/system/storage/vendor/twig/twig/src/Cache/FilesystemCache.php(54): mk
dir()\n#4 /var/www/html/system/storage/vendor/twig/twig/src/Environment.php(409): Twig\\Cache\\FilesystemCache->write()\n#
5 /var/www/html/system/storage/vendor/twig/twig/src/Environment.php(381): Twig\\Environment->loadClass()\n#6 /var/www/html
/system/storage/vendor/twig/twig/src/Environment.php(359): Twig\\Environment->loadTemplate()\n#7 /var/www/html/system/stor
age/vendor/twig/twig/src/Environment.php(318): Twig\\Environment->load()\n#8 /var/www/html/system/library/template/twig.ph

**Comment by krishna-7** [comment] 2021-07-24 08:18
> 
> 
> Your error report will be pretty useless, unless you can also provide the details from your Apache server's error log which is usually located at **/var/log/apache2/error.log**. This will tell you about the nature of your Internal Error 500.

I still had the same error, I have tried multiple times.

[Sat Jul 24 12:19:37.459747 2021] [php:error] [pid 196808] [client 103.66.79.201:43965] PHP Fatal error: Uncaught Excepti
on: Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'
Error No: 1231
SET @@session.sql_mode = 'M
YSQL40' in /var/www/html/system/library/db/mysqli.php:41\nStack trace:\n#0 /var/www/html/system/library/db.php(45): DB\My
SQLi->query()\n#1 /var/www/html/install/model/install/install.php(35): DB->query()\n#2 /var/www/html/system/engine/loader.
php(248): ModelInstallInstall->database()\n#3 /var/www/html/system/engine/proxy.php(47): Loader->{closure}()\n#4 /var/www/
html/install/controller/install/step_3.php(11): Proxy->__call()\n#5 /var/www/html/system/engine/action.php(79): Controller
InstallStep3->index()\n#6 /var/www/html/system/engine/router.php(67): Action->execute()\n#7 /var/www/html/system/engine/ro
uter.php(56): Router->execute()\n#8 /var/www/html/system/framework.php(169): Router->dispatch()\n#9 /var/www/html/system/s
tartup.php(104): require_once('...')\n#10 /var/www/html/install/index.php(37): start()\n#11 {main}\n thrown in /var/www/h
tml/system/library/db/mysqli.php on line 41, referer: http://mymunchbox.in/install/index.php?route=install/step_3

[Sat Jul 24 12:36:15.091403 2021] [php:warn] [pid 196808] [client 103.66.79.201:44870] PHP Warning: fopen(/var/www/html/s
ystem/storage/logs/error.log): Failed to open stream: Permission denied in /var/www/html/system/library/log.php on line 22

[Sat Jul 24 12:36:15.125825 2021] [php:error] [pid 196808] [client 103.66.79.201:44870] PHP Fatal error: Uncaught TypeErr
or: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /var/www/html/system/library/log.php:31\nStack
trace:\n#0 /var/www/html/system/library/log.php(31): fwrite()\n#1 /var/www/html/system/framework.php(46): Log->write()\n#
2 [internal function]: {closure}()\n#3 /var/www/html/system/storage/vendor/twig/twig/src/Cache/FilesystemCache.php(54): mk
dir()\n#4 /var/www/html/system/storage/vendor/twig/twig/src/Environment.php(409): Twig\Cache\FilesystemCache->write()\n#
5 /var/www/html/system/storage/vendor/twig/twig/src/Environment.php(381): Twig\Environment->loadClass()\n#6 /var/www/html
/system/storage/vendor/twig/twig/src/Environment.php(359): Twig\Environment->loadTemplate()\n#7 /var/www/html/system/stor
age/vendor/twig/twig/src/Environment.php(318): Twig\Environment->load()\n#8 /var/www/html/system/library/template/twig.ph

**Comment by krishna-7** [comment] 2021-07-24 08:19
> 
> 
> @krishna-7 Please enable the error reporting.
> I just checked by installing the same but didn't found any such issue.

I am able to install the master branch of opencart (4.0.0.0_b). But 3.0.3.7 and 3.0.3.6 are still having issues. At #3 the screen freezes but table entries are made.

**Comment by ADDCreative** [comment] 2021-07-24 12:37
Duplicate of https://github.com/opencart/opencart/issues/9118.

Fix https://github.com/opencart/opencart/commit/e3d13e21eadc4ac9d267eeca541948e084127b4e#diff-b64b964b8ba09dc74740246b28ea63ab9790fef80340b34d4297a1e7e2f935bc.

**Comment by mhcwebdesign** [comment] 2021-07-24 13:58
Use the fixed version of the mysqli.php from https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/library/db/mysqli.php .

**Closed by mhcwebdesign** 2021-07-24 13:58 UTC

**Comment by krishna-7** [comment] 2021-07-24 14:17
> Use the fixed version of the mysqli.php from https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/library/db/mysqli.php .

Hi 

I have tried using the maintenance branch, that then it gives me the following error : 

[Sat Jul 24 19:43:59.905109 2021] [php:error] [pid 802] [client 103.66.79.201:41145] PHP Fatal error:  Uncaught Error: Fai
led opening required '/var/www/html/system/storage/vendor/composer/../react/promise/src/functions_include.php' (include_pa
th='.:/usr/share/php') in /var/www/html/system/storage/vendor/composer/autoload_real.php:69\nStack trace:\n#0 /var/www/htm
l/system/storage/vendor/composer/autoload_real.php(59): composerRequirea8cb75283b86ff94542c6f1327c4ce59()\n#1 /var/www/htm
l/system/storage/vendor/autoload.php(7): ComposerAutoloaderInita8cb75283b86ff94542c6f1327c4ce59::getLoader()\n#2 /var/www/
html/system/startup.php(71): require_once('...')\n#3 /var/www/html/install/index.php(35): require_once('...')\n#4 {main}\n
  thrown in /var/www/html/system/storage/vendor/composer/autoload_real.php on line 69

**Comment by krishna-7** [comment] 2021-07-24 15:02
I used the maintenance branch and as @thewhiterabbit said in #9118, I commented out 
line 35 in opencart/install/model/install/install.php
line 213 in opencart/install/cli_install.php

Then it got installed!
