### ISSUE TITLE
OC4 module install function is never executed

### ISSUE THREAD

**Issue by juliocesar757** [opencart/opencart#9491] opened 2021-03-31 14:22 UTC
I am creating a module that modifies, by event, the html of the product page. The problem is that the OpenCart installer never executes the install function that is inside the module's controller. The install function is important for register the event.
To simulate the problem, create a basic module with an install function that is not inside the '/extension/opencart' folder (here is the problem, everything works if it is a native module inside the opencart folder, if it is another folder, the translation and the install function do not work). Note that the translation file is not loaded in the list of modules until it is installed.

**Comment by exelaguilar** [comment] 2021-04-08 00:44
I can confirm this is an issue. I've worked around it by manually calling the install function using |install, however I think I also know why it's doing it. 

By default, the Opencart folder extensions are already added to the database under the extension table.

OC 4 doesn't have a way for custom extensions to be added into the db while they're being uploaded and installed, only when you run the install from the modules section. 

In the Extension class in the admin/controller/startup/extension.php

It calls 

`$results = $this->model_setting_extension->getExtensions();`

And if you do  print_r($results); it only shows Opencart namespaces

Then in the Opencart\Application\Model\Setting for Extension class getExtensions()

`$query = $this->db->query("SELECT DISTINCT `extension` FROM `" . DB_PREFIX . "extension`");
`

A temp fix is in admin/controller/marketplace/installer.php

Line 395, under add:

`$this->model_setting_extension->install('extension', $extension_install_info['code'], $extension_install_info['code']);`

The problem with this is that the first parameter, I hard-coded to say 'extension', typically it is: 

$type, $extension_name, $extension_code

But there is no way to get the type unless you explode the path of the file, etc. and I don't think this is the correct way to fix this moving forward because once you actually install the extension it will create a duplicate entry.

**Comment by stalker780** [comment] 2021-04-08 07:24
Oh! Really?

https://github.com/opencart/opencart/issues/9069

**Comment by mhcwebdesign** [comment] 2021-04-08 21:13
This is part of a bigger problem. The whole of the OC4 extension namespace is wrong, the language won't load for extension modules, even the standard OC4 extension have bugs. I'll open a separate issue on this.

**Comment by chongshengdz** [comment] 2021-04-13 18:47
You are very very wrong.
If a 3rd party extension were to introduce a new extension package named 'foo' with a module named 'bar' (using file upload/extension/foo/admin/controller/module/bar.php in its ocmod.zip archive) then its namespace should be:

it should be

namespace Opencart\Admin\Controller\Extension\Foo\Module;
class Bar extends \Opencart\System\Engine\Controller {

and it should be foo.ocmod.zip

just tested the master version and found it still not stable, cannot save data in the Admin.
below is a sample extension, you can download and test it.
https://www.ectransistors.com/groupfolder.ocmod.zip

**Comment by juliocesar757** [comment] 2021-04-15 12:49
> You are very very wrong.
> If a 3rd party extension were to introduce a new extension package named 'foo' with a module named 'bar' (using file upload/extension/foo/admin/controller/module/bar.php in its ocmod.zip archive) then its namespace should be:
> 
> it should be
> 
> namespace Opencart\Admin\Controller\Extension\Foo\Module;
> class Bar extends \Opencart\System\Engine\Controller {
> 
> and it should be foo.ocmod.zip
> 
> just tested the master version and found it still not stable, cannot save data in the Admin.
> below is a sample extension, you can download and test it.
> https://www.ectransistors.com/groupfolder.ocmod.zip

Please do not take the focus off the real discussion here which is about the problem of executing the install function and the translation.

**Comment by nmpetkov** [comment] 2022-04-21 09:29
I can confirm that the problem exists at the moment. The module is installed, after installation and activation the index method is executed, but at the time of installation the install method is not executed.

I also want to note that when uninstalling, all files saved in the extension_path table are deleted as they should be. There is a problem, if for some reason another file is saved in the directory of the module, then when deleting it remains in the appropriate directory, and the uninstall procedure issues an error when trying to delete the directory because it is not empty.

I can suggest that to solve this problem, instead of deleting the files according to the entries in the extension_path table, delete the entire module directory with a recursive function, as is common practice when deleting directories.

**Comment by danielkerr** [comment] 2022-04-22 15:58
no longer use upload/ folder its just straght to the catalog/, admin/, etc..

**Comment by danielkerr** [comment] 2022-04-22 16:02
can test the install for extension/fraud IP it use the install function and creates and db table soo it is working.

**Comment by nmpetkov** [comment] 2022-04-23 07:36
The problem is that the loading of roads and namespaces in OpenCart Default Extensions and 3-th party Extensions is not the same. This can be seen by the following sample:
1. Completely uninstall OpenCart Default Extensions via Extensions, Installer (without deleting it).
2. Go to Extensions, Extensions, Modules and debug by printing:
file: ```system / library / language.php```
function: ```load```
debug: ```$this->path```
3. The result is:
```Array
(
    [extension/opencart] => /home/cmstory1/octest40.cmstory.com/extension/opencart/admin/language/
)```

I.e. the OpenCart Default Extensions path is loaded even when they are not installed at all. This helps them to load language files and controllers successfully during the installation of the individual modules.
Conversely, with 3-th party Extensions before they are installed, respective path is not loaded, and this is the reason why language files and their controllers are not loaded. However, once installed, they are now available.

**Comment by danielkerr** [comment] 2022-04-23 16:47
Do u have example code?

**Comment by nmpetkov** [comment] 2022-04-23 16:58
Thank you for your attention! I will prepare a sample module for installation and send it.

**Comment by nmpetkov** [comment] 2022-04-23 19:24
Test module is ready. Download link:
https://we.tl/t-kNiEeGFPVJ 

Please note:
1. After uploading the file, and after pressing the "+" button, a message appears in the progress bar:
```Warning: You don't have permission to modify extensions!```
which is not fatal, but it is strange once you are an administrator.
2. Go to Extensions, Extensions, Modules, and the new extension is in the table, but the language file is not loaded and the title is unreadable.
3. Press the install button and the extension is installed, but the install method does not run.
4. After installation, the language file is loaded, and in the table the header is readable, and the module is functionsl (install method is not yet started).

**Comment by danijelGombac** [comment] 2022-04-23 20:18
Can you try:

1. Create file extension.php in admin/controller/event/ dir with:

```
<?php
namespace Opencart\Admin\Controller\Event;
class Extension extends \Opencart\System\Engine\Controller {
	// controller/extension/*|install/before'
	public function index(string &$route, array &$args): void {
		$part = explode('/', $route);

		if (isset($part[1])) {
			$extension = str_replace(['_', '/'], ['', '\\'], ucwords($part[1], '_/'));

			// Register controllers, models and system extension folders
			$this->autoloader->register('Opencart\Admin\Controller\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/admin/controller/');
			$this->autoloader->register('Opencart\Admin\Model\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/admin/model/');
			$this->autoloader->register('Opencart\System\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/system/');

			// Template directory
			$this->template->addPath('extension/' . $result['extension'], DIR_EXTENSION . $result['extension'] . '/admin/view/template/');

			// Language directory
			$this->language->addPath('extension/' . $result['extension'], DIR_EXTENSION . $result['extension'] . '/admin/language/');

			// Config directory
			$this->config->addPath('extension/' . $result['extension'], DIR_EXTENSION . $result['extension'] . '/system/config/');
		}			
	}
}
```

2. and then add in the system/config/admin.php

```
'controller/extension/*|install/before' => [
	0 => 'event/extension'
],
```

**Comment by nmpetkov** [comment] 2022-05-02 10:34
[como_test.ocmod.zip](https://github.com/opencart/opencart/files/8602303/como_test.ocmod.zip)
I am attaching a test module file again, as the link above has expired.

**Comment by nmpetkov** [comment] 2022-05-02 10:39
I don't know if I should open a separate issue, but I would like to know where to put the admin javascript and css files in the zip file?

**Comment by danielkerr** [comment] 2022-05-03 09:55
in extension/youcode/catalog/view/javascript/

**Comment by danielkerr** [comment] 2022-05-03 09:59
the system should set namespaces automatically if extension is installed. its already done for you in start up.

admin/controller/startup

<?php
namespace Opencart\Admin\Controller\Startup;
class Extension extends \Opencart\System\Engine\Controller {
	public function index(): void {
		// Add extension paths from the DB
		$this->load->model('setting/extension');

		$results = $this->model_setting_extension->getExtensions();

		foreach ($results as $result) {
			$extension = str_replace(['_', '/'], ['', '\\'], ucwords($result['extension'], '_/'));

			// Register controllers, models and system extension folders
			$this->autoloader->register('Opencart\Admin\Controller\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/admin/controller/');
			$this->autoloader->register('Opencart\Admin\Model\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/admin/model/');
			$this->autoloader->register('Opencart\System\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/system/');

			// Template directory
			$this->template->addPath('extension/' . $result['extension'], DIR_EXTENSION . $result['extension'] . '/admin/view/template/');

			// Language directory
			$this->language->addPath('extension/' . $result['extension'], DIR_EXTENSION . $result['extension'] . '/admin/language/');

			// Config directory
			$this->config->addPath('extension/' . $result['extension'], DIR_EXTENSION . $result['extension'] . '/system/config/');
		}
	}
}

**Comment by danielkerr** [comment] 2022-05-03 10:22
i know the issue. will fix.

**Comment by danielkerr** [comment] 2022-05-04 10:41
i thin fixed now

**Comment by juliocesar757** [comment] 2022-05-04 12:29
@danielkerr, there are errors with the extensions system after this update. 
I did tests using my modules for OC4 and also the file sent by @nmpetkov 

1) Clicking the install button after uploading

![1-install_msg_error](https://user-images.githubusercontent.com/49540652/166680217-ce7038e2-3c0f-4300-a14c-d5bd65b74779.jpg)

2) Despite the error message, the module is shown as installed after refreshing the page

![2-refresh_page_install](https://user-images.githubusercontent.com/49540652/166680233-d21bd173-172f-4b40-8ab0-5f6ce0f09ec8.jpg)

3) Translation file still not loading in module listing

![3-language-error](https://user-images.githubusercontent.com/49540652/166680244-760c0743-32de-44fa-89c9-c35a6f7e506b.jpg)

4) The module cannot be installed

![4-install-error](https://user-images.githubusercontent.com/49540652/166680250-2e170ee0-6ff5-4f0c-a65b-e7093db50a92.jpg)

**Comment by nmpetkov** [comment] 2022-05-04 12:33
@juliocesar757 I can confirm above errors. In addition now is not possible to install not only my test extenmsion, but also native opencart extensins. Just try to uninstall and then install one of them.

**Comment by danijelGombac** [comment] 2022-05-04 12:51
@danielkerr in startup/extension.php there is
`
$extension = str_replace(['_', '/'], ['', '\\'], ucwords($result['extension'], '_/'));
`
and then register controllers, models and system extension folders ...

in you latest update of extensions install this line missing. Is that's ok?

**Comment by danielkerr** [comment] 2022-05-04 13:56
> @danielkerr in startup/extension.php there is `$extension = str_replace(['_', '/'], ['', '\\'], ucwords($result['extension'], '_/'));` and then register controllers, models and system extension folders ...
> 
> in you latest update of extensions install this line missing. Is that's ok?

good point

**Comment by danielkerr** [comment] 2022-05-04 14:08
ok try now

**Comment by danielkerr** [comment] 2022-05-04 14:54
ok losing my mind. 

commited another fix

**Comment by stalker780** [comment] 2022-05-04 15:08
@danielkerr 
https://github.com/opencart/opencart/blob/0cb5001d2bcedcc2409193ec0aabaf14936045ed/upload/admin/controller/startup/extension.php#L8

This line is wrong. Language files for module are never loaded until any oc_extension.extension from oc_extension_install.code is installed. It is quite simple. You need to use oc_extension_install table for codes in startup. Not oc_extension table.

**Comment by nmpetkov** [comment] 2022-05-04 15:57
[como_test.ocmod.zip](https://github.com/opencart/opencart/files/8622059/como_test.ocmod.zip)
I am attaching a test module file again, to be able to test. It is cleaned from some code.

**Comment by danielkerr** [comment] 2022-05-04 16:00
@[stalker780](https://github.com/stalker780)

its not getInstalls that would mess it up.

**Comment by nmpetkov** [comment] 2022-05-04 16:18
`Please check this pr
82abe9d`
This loads in proper way language and namespace, But still cannot instal because of this error:
![image](https://user-images.githubusercontent.com/628801/166725400-4b11ca21-fdfa-4ab7-b960-2501429d79a2.png)
In fact, this error occurred during one of the last changes here.

**Comment by cgcmart** [comment] 2022-05-04 16:49
because admin/controller/startup/extension.php only loads and registers opencart extensions. It doesn't write to load and register any else extensions.

**Comment by danielkerr** [comment] 2022-05-04 16:50
@[stalker780](https://github.com/stalker780) maybe your right

**Comment by danielkerr** [comment] 2022-05-05 09:02
just done another commit. it should be fixed now

**Comment by danielkerr** [comment] 2022-05-05 09:03
also lets not do anything that messes with the core files. i noticed como_test.ocmod createss files in the admin folder

**Comment by nmpetkov** [comment] 2022-05-05 10:19
Yes, sure! I never create files there. In test it is possibly because
wonder where to please css and js files.

**Comment by danielkerr** [comment] 2022-05-05 11:54
put it under 

extension/yourcode/catalog/view/stylesheet/
extension/yourcode/catalog/view/javascript/

**Comment by juliocesar757** [comment] 2022-05-05 12:04
I confirm that everything is OK now.

**Comment by chongshengdz** [comment] 2022-05-05 12:12
> put it under
> 
> extension/yourcode/catalog/view/stylesheet/ extension/yourcode/catalog/view/javascript/

next, please fix this bug.
https://github.com/opencart/opencart/issues/10503

**Closed** 2022-05-05 12:43 UTC
Labels: master-branch

**Comment by nmpetkov** [comment] 2022-05-05 19:30
@danielkerr I also confirm all is Ok now.


---
About:
> i noticed como_test.ocmod createss files in the admin folder

It was just to test if install function is executed
`file_put_contents('info_data$install.txt', print_r('--', true));`
