### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by battlebooks** [opencart/opencart#3103] opened 2015-06-12 05:37 UTC
Hi,

I created a test order (using version 2.0.3.1 of OC).and wanted to change the order status from Pending to Processed, but i get this error when i try an look at the order.

![capture](https://cloud.githubusercontent.com/assets/12855881/8124075/80c1ea2a-1129-11e5-9316-ab5d27489d1b.PNG)

**Comment by mrnfrancesco** [comment] 2015-06-12 10:12
I cannot reproduce it, but you're right! The sale order controller is bugged and could not set the `$json` variable properly.

The problem is with line 2175:
```
if (isset($this->session->data['cookie']) && isset($this->request->get['api'])) {
```

Now, `api` seems to be always hard-coded in javascript functions.
Could you have some problem with cookies?

If you explain me *step-by-step* what you did to reproduce the error, I could try to solve your problem.

**Comment by milimar** [comment] 2015-06-12 20:25
@battlebooks , you don't say which version of OC you are using. I have installed 2.0.3.1 and no problems with changing order statuses.

Greetings

**Comment by mhcwebdesign** [comment] 2015-06-12 21:32
Could it be related to the known issues of using CURL HTTP loopback for the API access?

**Comment by battlebooks** [comment] 2015-06-13 23:27
Hi again, thanks for your replies. I can explain what i am doing. I login as a customer, and place an order. payment method does not seem to matter (as i tried credit card with DPS extension and also bank transfer). Then i go to another PC and log in to Opencard admin, i see i have a new order so go to it, i can view it and the status is pending, but when i try to edit it to change status to processed i get that error.

**Comment by danielkerr** [comment] 2015-06-14 05:02
Closing this as its related to the curl loopback issue

**Comment by danielkerr** [comment] 2015-06-14 05:02
Closing this as its related to the curl loopback issue

**Closed by danielkerr** 2015-06-14 05:02 UTC

**Comment by battlebooks** [comment] 2015-06-14 05:14
Hi Daniel,
Sorry I don't know what this issue is, is it a known fault. Is there a fix / process i should follow to resolve the issue ?
thxdave

**Comment by luv777** [comment] 2015-10-05 08:45
Where is the solution?

**Comment by luv777** [comment] 2015-10-05 08:46
i need the solution about this error when import/export extention  installed in opencart 2.0.3.1 display syntax error and unexpected token....i want solution ASAP

**Comment by satishkumar84310** [comment] 2018-02-12 17:32
Hi All,
Could your please help for this issue.
Login in opencart with Admin user
Go to Sales->orders-> Edit any order
here trying to edit order if click on continue button then getting

"SyntaxError : Unexpected token < in JSON at postion0


![json error](https://user-images.githubusercontent.com/36369983/36110521-d7cdd826-1048-11e8-9773-21a973e54580.jpg)
