### ISSUE TITLE
[3.0.3.1] Unnecessary variable (%s) in customer account (wishlist)-Not fixed

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7130] opened 2019-01-07 09:26 UTC
Still show ugly **Wishlist (%s)** in Customers account.

https://github.com/opencart/opencart/issues/6721

**Comment by danielkerr** [comment] 2019-01-07 11:35
its fixed in the master branch

**Comment by danielkerr** [comment] 2019-01-07 11:36
also this looks like a language file issue.

**Closed by danielkerr** 2019-01-07 11:36 UTC

**Comment by condor2** [comment] 2019-01-07 11:55
Yes, I know.

But why relased 3.0.3.1 as "bugs fixed 3.0.2.0" ?

**Comment by danielkerr** [comment] 2019-01-07 11:56
it does not have all bug fixes but enough to make the system still compatible with the last version.

**Comment by condor2** [comment] 2019-01-07 11:59
Then on Released notes should write something like this.

"Not all bugs was fixed"
"May contain bugs"

That people know if made upgrade to 3.0.3.1 or keep 3.0.2.0 :)

**Comment by stanislavdavid** [comment] 2019-02-18 00:47
looks like duplicate of #6068
