### ISSUE TITLE
Filemanager pagination broken

### ISSUE THREAD

**Issue by beinoriusju** [opencart/opencart#6563] opened 2018-04-05 18:30 UTC
My client is using filemanager to upload product photos.

Creating a blank directory and uploading exactly 17 images does not show pagination.  This happens because of usage of `array_splice ` witch modifies `$directories` array and `$files` array.

Pagination needs correct, but gets wrong total:

`$pagination->total = count(array_merge((array)$directories, (array)$files));`

MY VERSION 3.0.2.0

**Comment by miklcct** [comment] 2018-04-09 04:29
@beinoriusju,

I cannot reproduce it on my own machine. Could you please send a ticket to support@opencart.com to see if there is some misconfiguration instead?

**Comment by beinoriusju** [comment] 2018-04-09 05:31
@miklcct 

Maybe I'm looking the wrong way... There are variations of filemanager.php.

Master fails

https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/filemanager.php

Dev works

https://github.com/opencart/opencart/blob/dev/upload/admin/controller/common/filemanager.php

Notice how they calculate Pagination totals differently. Can you try once more replacing your filemanager.php with a copy from master branch? Or is it considered outdated?

**Comment by miklcct** [comment] 2018-04-09 06:07
I cannot reproduce the bug on plain Opencart 3.0.2.0 without any modification installed

**Comment by beinoriusju** [comment] 2018-04-09 06:13
You're right. Please close this branch.

**Comment by danielkerr** [comment] 2018-04-09 14:38
even if there is an issue its fixed in the master.

**Closed by danielkerr** 2018-04-09 14:38 UTC
