### ISSUE TITLE
System Time Zone Change Kicks Out Admin

### ISSUE THREAD

**Issue by djdj23** [opencart/opencart#12195] opened 2023-03-02 04:04 UTC
**What version of OpenCart are you reporting this for?**
3.0.3.8
**Describe the bug**
When you change the timezone in SYSTEM\SETTINGS\LOCAL (in my case changed to America-New York), when you save the setting, it kicks the user(administrator), and locks them from logging back into the admin panel.  When you try to log back in, the screen refreshes as if you never clicked 'login'.

What section does it affect?
It locks the user/admin out.  I have not tried this with multiple users.

**To Reproduce**
1. Go to SYSTEM\SETTINGS\LOCAL
2. Change the Time Zone from UTC (+00:00) to America/New_York(-5:00)
3. Click Save and wait a moment
4. User is logged out
5. Try to log back in.

I saw a opencart forum article about the file to modify to change the time zone back to UTC that would supposedly remedy the issue. https://forum.opencart.com/viewtopic.php?f=201&t=222369#p813699

**Expected behavior**
When the time zone is changes in the settings, the time should update to the appropriately selected time zone and allow the user to save the functions without being logged out.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Hosted Web Server
 - Operating system : Windows, I think
 - PHP version : 7.4.33
 - Apache version 2.4.55
 - Browser(s) tested with [e.g. chrome, safari - if applicable]: Chrome
 - Version [e.g. 22] : Chrome Version 110.0.5481.178 (Official Build) (64-bit)

**Additional context**

**Comment by danielkerr** [comment] 2023-03-02 09:52
im closing this

**Closed by danielkerr** 2023-03-02 09:52 UTC

**Comment by mhcwebdesign** [comment] 2023-03-02 12:17
Try the 3.0.x.x_Maintenance branch, to see whether this is still an issue or not.

**Comment by ADDCreative** [comment] 2023-03-02 14:26
Looks like a duplicate of https://github.com/opencart/opencart/issues/9237.

@mhcwebdesign I don't believe this is fixed in he 3.0.x.x_Maintenance branch. A partial fix would be https://github.com/opencart/opencart/pull/9633, which looks like it has only been applied to the master.

However, that is only a partial fix as you will still have issue with the API when the time zone is change to a negative one.
https://github.com/opencart/opencart/issues/9492
