### ISSUE TITLE
V 4.0.1.1 Can't close any popup message both frontend and backend

### ISSUE THREAD

**Issue by amdev** [opencart/opencart#11607] opened 2022-08-30 03:04 UTC
Opencart v 4.0.1.1 freshy install
Admin step:
1.Login to admin and click developer settings
2.Click any refresh button and popup show
3.Click close popup but not working

Frontend step:
1.Click add to cart and popup show
3.Click close popup but not working

Thanks

**Comment by mhcwebdesign** [comment] 2022-08-30 08:57
Try the master branch, as far as I know Daniel has already fixed it in there.

**Comment by danielkerr** [comment] 2022-08-30 11:06
browser?? because this is not happening to me or any other people

**Comment by azn1viet** [comment] 2022-09-01 05:06
I can confirm I get the same issue:

I'm on the latest Chrome 104... and got the same issue. I tried on Bootstrap document guide, it's working fine, but when I copy their code to add manually, it won't work on OpenCart 4.

![Screenshot 2022-09-01 120251](https://user-images.githubusercontent.com/769104/187835402-15a59f52-9a9f-4444-9c5e-1751d97e75cd.png)

**Comment by amdev** [comment] 2022-09-01 06:18
> browser?? because this is not happening to me or any other people

Windows 10 64bits with chrome Version 104.0.5112.102

**Comment by kb-git** [comment] 2022-09-02 13:29
I have exactly the same issue. 
Windows 11
Chrome version 105.0.5195.54 (Official Build) (64-bit)

![cannot-close](https://user-images.githubusercontent.com/37004034/188156322-05b9f578-9d94-4599-b9b1-2c0f6072dfa8.jpg)

**Comment by mhcwebdesign** [comment] 2022-09-02 13:38
Guys, this has been fixed in the master branch!

The only difference with these alert boxes on the frontend, as compared to the backend, is that they don't automatically time out, the user has to manually click on the close icon ('x').

**Comment by kb-git** [comment] 2022-09-02 13:48
Close button (x) and links in the messages are not clickable. 
Try: https://www.atol-nabytek.cz/2022/

**Comment by chulcha** [comment] 2022-09-02 14:00
```
.toast-container {
	width: max-content;
	max-width: 100%;
	/* pointer-events: none; */
}
```

**Comment by kb-git** [comment] 2022-09-02 14:09
Yes, that fixed it! Thank you.

**Comment by mhcwebdesign** [comment] 2022-09-02 14:57
> Close button (x) and links in the messages are not clickable. Try: https://www.atol-nabytek.cz/2022/

Yes, they are when using the master branch!

**Comment by amdev** [comment] 2022-09-03 01:32
#alert {
  z-index: 9999;
  pointer-events: all;/*frome master branch add this line*/
}

Just check from msater branch added pointer-events: all; in #alert {} but v4011 don't have it

Closed issue

**Comment by FelipoAntonoff** [comment] 2022-09-08 14:32
Hello, actually in 4.0.1.1 there is no fix, I was about to open an Issue until I saw it.

It would also be good after a while to close the notice.

**Comment by amdev** [comment] 2022-09-12 01:09
> refresh ur css

Hi Dan in v.4.0.1.1 still dont have point-events in stylesheet.css

Please check

[stylesheet.css](https://github.com/opencart/opencart/blob/4.0.1.1/upload/catalog/view/stylesheet/stylesheet.css)

![4011-still-bug](https://user-images.githubusercontent.com/433184/189557796-ba6bdd39-45ae-46dd-adb5-7cb97b95d014.png)

**Comment by mhcwebdesign** [comment] 2022-09-12 07:47
Is nobody reading the posts here? 

Please try the current master branch, it is fixed, alerts can be closed.

**Closed** 2022-09-12 09:15 UTC

**Comment by danielkerr** [comment] 2022-09-12 09:55
@amdev already fixed! stop bothering me u clown! sort it ur self. delete the css cache
