### ISSUE TITLE
Opencart Order edit from admin shows product in cart in front end.

### ISSUE THREAD

**Issue by sureshmg23** [opencart/opencart#4246] opened 2016-04-14 16:29 UTC
What if the admin just wants to edit the order status from pending to "Completed" ? In this situation also the product shown in customer cart? how to stop this when editing an order from admin? what is the use of this functionality, when the customer has already made the purchase? 
Customers are calling me, and asking me to stop this, what should i do to stop this activity to the customer cart?

**Comment by hutbert** [comment] 2016-04-14 16:36
We are seeing the same issue. We have a temporary fix by commenting out line 19 in system/library/cart.php. When an admin edits an order - additional rows are added to the cart table for that customer. When the customer returns to the site - the items in the temporary cart from the admin edit get pulled into the current customer session and end up in their cart.  Removing line 19 will cause items in the customers cart to drop off if the customer returns in a future session but we've decided that is probably better than having unwanted items show up in their cart.

**Comment by OpenCartAddons** [comment] 2016-04-14 16:47
@sureshmg23 This won't resolve your issue regarding editing the customer's phone number, but when updating the order status you should always VIEW the order and add a new order history.  This allows you to keep a history of the order statuses and you can also choose to notify the customer of the order status update.

Cheers,
Joel.

**Comment by sureshmg23** [comment] 2016-04-14 16:49
@OpenCartAddons  Thanks for the quick reply. Then how can i edit the phone number alone for that order without adding the product to the cart?

**Comment by OpenCartAddons** [comment] 2016-04-14 16:51
@sureshmg23 I haven't looked into the code to see exactly what it's doing, but you could try @hutbert solution.

**Comment by sureshmg23** [comment] 2016-04-14 16:52
@hutbert  Thank you. Removing line 19 from system/library/cart.php shows "Undefined variable: cart_query..". Am i commenting the correct line?

**Comment by sureshmg23** [comment] 2016-04-14 16:54
Below code comes between line 16 to 29:
if ($this->customer->getId()) {
			// We want to change the session ID on all the old items in the customers cart
			$this->db->query("UPDATE " . DB_PREFIX . "cart SET session_id = '" . $this->db->escape($this->session->getId()) . "' WHERE customer_id = '" . (int)$this->customer->getId() . "'");

			// Once the customer is logged in we want to update the customer ID on all items he has
			$cart_query = $this->db->query("SELECT * FROM " . DB_PREFIX . "cart WHERE customer_id = '0' AND session_id = '" . $this->db->escape($this->session->getId()) . "'");

			foreach ($cart_query->rows as $cart) {
				$this->db->query("DELETE FROM " . DB_PREFIX . "cart WHERE cart_id = '" . (int)$cart['cart_id'] . "'");

				// The advantage of using $this->add is that it will check if the products already exist and increaser the quantity if necessary.
				$this->add($cart['product_id'], $cart['quantity'], json_decode($cart['option']), $cart['recurring_id']);
			}
		}

**Comment by hutbert** [comment] 2016-04-14 17:44
Ahh - might be line 18 in your version - the first $this->db->query("UPDATE... line should be commented out. That line moves all cart items into the current cart - even it those items were added via the admin dashboard.

**Comment by sureshmg23** [comment] 2016-04-15 05:11
@hutbert Thank you for the reply. Commenting line 18 works with my test store in local server (Version 2.1.0.1) but same thing is not working in live site(Version 2.1.0.1) same version ad demo.

**Comment by sureshmg23** [comment] 2016-04-15 06:19
@hutbert  Thanks for the solution, i have system/library/cart.php in system/modifications also, so commenting line 18 in both files works now. Works fine now, without populating the products in customer cart :)

**Comment by sureshmg23** [comment] 2016-04-15 13:37
@hutbert  Now, i cannot add the product to cart from front end(store). Please help me out of this.

**Comment by hutbert** [comment] 2016-04-18 16:14
@sureshmg23  I'm not sure what else would have been modified in your system/modifications. I'd recomment switching it back and seeing if you can come up with another solution for stopping the cart class from capturing all of the items in the cart table for a customer.

**Comment by danielkerr** [comment] 2016-05-07 04:13
I dont see the issue. you just remove the items. or course your accessing the customers cart to edit a customers order!

**Comment by hutbert** [comment] 2016-05-09 20:14
Here's the issue we had. 

- the customer placed and order and received the confirmation
- the admin made a change to the order 
- the customer returned later to place a new order and found that the items from the order the admin had edited had re-appeared in the cart. 

Customer was confused as to why items would show up in the cart when they had not added them and had no knowledge of the admin editing an order. 

Sure - the customer could just remove the items from the cart and continue on their way but the unexpected items in the cart created a poor user experience.

**Comment by danielkerr** [comment] 2016-06-16 04:20
@sureshmg23 

> What if the admin just wants to edit the order status from pending to "Completed" ? In this situation also the product shown in customer cart?

you use the order info page for updating the order status! never use the edit order to change the status!

**Comment by danielkerr** [comment] 2016-06-17 10:11
adding a store ID field should help

**Comment by pnair39** [comment] 2016-06-17 13:37
@danielkerr next release will it work upgrading from 2.1.0.2? Since none of was were able to complete the upgrade on any backup production sites.

**Comment by CoverUp** [comment] 2016-06-17 15:42
never use edit order to edit an order xD
How can you change the order status from pending to shipped, or add a order history like "delayed shipping" without put products on customer cart and without wasting time with continue buttons on order edit?
Easy, just add an other action button on the order list called "add order history", just next to "view".

**Comment by danielkerr** [comment] 2016-06-21 06:50
@pnair39 rally? because no one has posted the errors that are blocking you upgrading.

i suggest you open an issue with the errrors. make sure they are not 3rd party extensions.

**Comment by pnair39** [comment] 2016-06-23 02:35
@danielkerr https://github.com/opencart/opencart/issues/4055

disabled all extensions and cleared modifications folder, still receiving upgrade error posted above issue.

**Comment by danielkerr** [comment] 2016-06-26 06:03
you mean people need to clear their modification directory before upgrade.

**Comment by danielkerr** [comment] 2016-06-26 13:04
what i can do is at the beginning of the upgrade script is to clear the mods directory

**Comment by danielkerr** [comment] 2016-06-26 13:05
I know what the issue is.

**Comment by danielkerr** [comment] 2016-06-27 04:16
@pnair39 your upgrade issue should be fixed with the latest commit

**Closed** 2016-06-27 08:33 UTC
Labels: Confirmed, In Progress
