### ISSUE TITLE
Checkout issue

### ISSUE THREAD

**Issue by garychew** [opencart/opencart#11397] opened 2022-06-28 01:55 UTC
**What version of OpenCart are you reporting this for?**
4.0.0

**Describe the bug**
In the Checkout page, after entering address, choosing shipping and payment, the "Confirm Order" button is disabled. Thus, failed to complete the checkout process.

**To Reproduce**
1. After added product into the cart, go to Checkout page.
2. Enter address.
3. Choose shipping and payment.
4. See error - the "Confirm Order" button is disabled.

**Expected behavior**
The "Confirm Order" button is enabled and able to perform checkout for the order.

**Screenshots / Screen recordings**
https://snipboard.io/8YxzO0.jpg

**Server / Test environment (please complete the following information):**
 - Local development
 - Operating system: Windows
 - PHP version: 8.1
 - Apache version: 2.4
 - Browser(s) tested with: Firefox
 - Version: 101.0.1

**Comment by garychew** [comment] 2022-06-28 08:33
Nope, I am using COD as you can see from the screenshot.

**Comment by viper-00** [comment] 2022-07-04 03:06
> Nope, I am using COD as you can see from the screenshot.

Hello, I encountered the same problem, Did you solve it？

**Comment by pemaier** [comment] 2022-07-05 16:41
It's the same as in #11355 
You have to configure in the settings checkout terms. If - Checkout Terms = None is provoking this behavior.
![image](https://user-images.githubusercontent.com/10166095/177375838-1e2a1753-e0bb-4fda-b449-f082d3b7f4ba.png)

**Comment by viper-00** [comment] 2022-07-09 05:59
> 

Ok,  I got it. Thanks for your help.

**Comment by viper-00** [comment] 2022-07-09 05:59
> It's the same as in #11355 You have to configure in the settings checkout terms. If - Checkout Terms = None is provoking this behavior. ![image](https://user-images.githubusercontent.com/10166095/177375838-1e2a1753-e0bb-4fda-b449-f082d3b7f4ba.png)

Ok, I got it. Thanks for your help.

**Comment by mhcwebdesign** [comment] 2022-07-09 20:44
I can confirm this bug. Even with checkout terms correctly enabled, it's still the same issue.
See attached screenshot.
![Screenshot_2022-07-09_21-32-37](https://user-images.githubusercontent.com/2989557/178122006-44f8e995-8d40-4822-b0e5-60a74e71ce29.png)

**Comment by danielkerr** [comment] 2022-07-10 09:12
it works fine for me

**Comment by danielkerr** [comment] 2022-07-10 09:13
$this->model_checkout_order->addHistory($this->session->data['order_id'], $this->config->get('payment_cod_order_status_id'))

is it because its sending an email out

**Comment by pemaier** [comment] 2022-07-10 09:25
it works also fine for me - except it should also work with checkout term setting NONE

**Comment by danielkerr** [comment] 2022-07-10 10:11
it works fine with and without terms

**Comment by pemaier** [comment] 2022-07-10 10:28
No it's not!
![image](https://user-images.githubusercontent.com/10166095/178141055-ef808ab3-7f49-4cc3-8a5b-b1b3cf1e5d29.png)
![image](https://user-images.githubusercontent.com/10166095/178141081-9b970f8f-2dcd-44f3-8a43-82b2ab40ed47.png)

**Comment by pemaier** [comment] 2022-07-10 10:30
here is the difference
![image](https://user-images.githubusercontent.com/10166095/178141125-1e0fca85-f9e1-4c4d-bb65-a9f25427bf47.png)
![image](https://user-images.githubusercontent.com/10166095/178141136-f8efdf08-1e34-4899-9115-25337497c7f2.png)

**Comment by pemaier** [comment] 2022-07-10 10:44
Now I have set the checkout terms again on NONE ... now it's working. I have now explanation what happens during that steps.
I was even testing 1 time more with deleting cache before ... and it's working. So for me that happens after an inital install.

**Comment by danielkerr** [comment] 2022-07-10 11:24
@[mhcwebdesign](https://github.com/mhcwebdesign)i can not replicate the long execution time. it must be because its sending an email out and something on your end is blocking it.

**Comment by danielkerr** [comment] 2022-07-10 11:31
maybe the session

**Comment by mhcwebdesign** [comment] 2022-07-10 13:32
@danielkerr: I am looking into it right now. I just tested it with the Mail Alerts for Orders switched off, still no difference. Hopefully I'll narrow it down soon and let you what I find.

**Comment by mhcwebdesign** [comment] 2022-07-10 14:08
This is really weird: The **extension/opencart/catalog/controller/payment/cod.php**, in function **confirm**, does this call, as expected: `$this->model_checkout_order->addHistory($this->session->data['order_id'], $this->config->get('payment_cod_order_status_id'));` 

But then it takes more than a minute before it actually reaches the target function **addHistory** in file **catalog/model/checkout/order.php** . I have never seen such a strange behavior.

**Comment by mhcwebdesign** [comment] 2022-07-10 17:25
OK, a couple of hours later, I narrowed it down to the event handler with trigger **catalog/model/checkout/order/addHistory/before** and action **mail/order**. So yes, Daniel, you were right!

@garychew: Is yours now working, too? Have you checked your mail settings?

**Comment by danielkerr** [comment] 2022-07-10 17:43
@[pemaier](https://github.com/pemaier) post a link to the web site. i want to see this myself

**Comment by pemaier** [comment] 2022-07-10 19:27
Here is the link: https://nettwork.ru/opencart/master.demo/ 
It is a brand new install at commit #13006
The only change is the deleting of he install folder from outside of the administration.
If you need more pls. let me know.

**Comment by danielkerr** [comment] 2022-07-11 08:11
@[pemaier](https://github.com/pemaier) i dojntknow what u have doone to ur site but mine works fine./

**Comment by mhcwebdesign** [comment] 2022-07-11 08:54
@pemaier: It looks like you haven't enabled the shipping method, just tested yours for a guest checkout with a UK-based address.

**Comment by pemaier** [comment] 2022-07-11 09:02
@mhcwebdesign As I said it is a purly new install without any change. The shipping methode flatrate is active by default.

**Comment by danielkerr** [comment] 2022-07-11 09:34
these are all the if statements blocking the button
		
// Validate customer data is set
if (!isset($this->session->data['customer'])) {
			$status = false;
		}

		// Validate cart has products and has stock.
		if ((!$this->cart->hasProducts() && empty($this->session->data['vouchers'])) || (!$this->cart->hasStock() && !$this->config->get('config_stock_checkout'))) {
			$status = false;
		}

		// Validate minimum quantity requirements.
		$products = $this->model_checkout_cart->getProducts();

		foreach ($products as $product) {
			if (!$product['minimum']) {
				$status = false;

				break;
			}
		}


		// Validate if payment address has been set.
		if ($this->config->get('config_checkout_address') && !isset($this->session->data['payment_address'])) {
			$status = false;
		}

		// Shipping
		if ($this->cart->hasShipping()) {
			// Validate shipping address
			if (!isset($this->session->data['shipping_address'])) {
				$status = false;
			}

			// Validate shipping method
			if (isset($this->session->data['shipping_method']) && isset($this->session->data['shipping_methods'])) {
				$shipping = explode('.', $this->session->data['shipping_method']);

				if (!isset($shipping[0]) || !isset($shipping[1]) || !isset($this->session->data['shipping_methods'][$shipping[0]]['quote'][$shipping[1]])) {
					$status = false;
				}
			} else {
				$status = false;
			}
		} else {
			unset($this->session->data['shipping_address']);
			unset($this->session->data['shipping_method']);
			unset($this->session->data['shipping_methods']);
		}

		// Validate checkout terms
		if ($this->config->get('config_checkout_id') && !isset($this->session->data['agree'])) {
			$status = false;
		}

**Comment by danielkerr** [comment] 2022-07-11 09:36
@[pemaier](https://github.com/pemaier)

i think u have done something on purpose. u have posted numerous issue all none issues that was only affecting your site. i think ur purposely wasting my time anhd the communities!

**Comment by pemaier** [comment] 2022-07-11 10:32
i think u have done something on purpose.  ... serious. 
For sure it must be my daily fun to install OpenCart 2-3 times a day and spend my time for testing and write error reports.

All the time I invest here spare my (and others) time with customer problems I thought. Thanks for honoring my time!

**Comment by danielkerr** [comment] 2022-07-11 10:49
its working n your site now.

**Comment by danielkerr** [comment] 2022-07-11 10:51
you error log page is not woorking.

**Comment by danielkerr** [comment] 2022-07-11 10:53
![image](https://user-images.githubusercontent.com/5079756/178249095-d4430a92-c19b-41da-8eb1-1148fa8ea61c.png)

**Comment by danielkerr** [comment] 2022-07-11 10:55
i need to close this

**Closed by danielkerr** 2022-07-11 10:55 UTC

**Comment by pemaier** [comment] 2022-07-11 11:53
Closing is OK. 
I can confirm that after a NEW install it is required to open settings and save. Then the problem is solved.

**Comment by danielkerr** [comment] 2022-07-11 12:51
FFS wasting a day on this
