### ISSUE TITLE
When 15+ items in cart and register during checkout the register/save updates the cart but then the next ajax call tries to do the same thing and we end up with dups

### ISSUE THREAD

**Issue by weismannweb** [opencart/opencart#7375] opened 2019-04-21 02:23 UTC
**What version of OpenCart are you reporting this for?**
3.0.2.0 possible current version unless there's a fix already I cant find
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
It affects stores where customer checkout with larger carts.
It affects the cart items upon checkout when they register.  If you have 15+ items in the cart (maybe less I have not checked) when you successfully get past the register step in the checkout the register/save ajax call is made which logs in the user and updates their cart by basically deleting their cart items and re-adding them with their customer id.  The problem is with enough items in the cart and a fast enough server and ajax calls the subsequent ajax calls try to do the same thing which effectively duplicates all items in the cart.  Most items have quant of 2 now if they were one.  Only the items already finished on the first ajax call are unaffected.

**To Reproduce**
add 15+ items to cart
checkout and choose to register
open the cart in a new tab in your browser so we can check it right after the registration step is done
finish the registration step and don't do anything else
then go to that other tab you have the cart open and refresh and most of your items are duplicated

**Expected behavior**
items are not duplicated and the cart is exactly the same before they did the registration step

**Screenshots / Screen recordings**
https://drive.google.com/file/d/1NQthNqMDSssAlGgRbgy-lQtxUrPgB7C9/view

**Comment by danielkerr** [comment] 2019-04-29 09:29
one of opencart features is cart is saved in the customers account, so when u login it adds your old basket to the new one. its a feature, i could remove it but then i will get complaints or lack a feature other carts have.

**Comment by danielkerr** [comment] 2019-04-29 09:33
anyway even with the video its hard to understand what you mean,.

**Comment by danielkerr** [comment] 2019-04-29 09:33
ill look into this a bit more.

**Comment by weismannweb** [comment] 2019-05-03 14:47
no i know that the cart is saved to the logged in customers session, the problem is that the ajax calls after the initial ajax call that registers the customer are doing the same delete and readd cart items code even after the first ajax call to register has started it, that ends up casing items to be duplicated

**Comment by grazcata** [comment] 2019-07-23 21:07
> 
> 
> no i know that the cart is saved to the logged in customers session...the problem is that happens and the items duplicate, this is NOT the duplication that happens when the logged out cart combines with a previous logged in cart, the problem is that the ajax calls after the initial ajax call that registers the customer are doing the same delete and readd cart items code even after the first ajax call to register has started it, that ends up casing items to be duplicated, this is because it is in the constructor of the cart class system/library/cart/cart.php which runs on every ajax call (actually every page load) that happens when the cart registration step is submitted, therefore that constructor code is run again and again however many page loads happen before the first page load is finish updating the cart
> 
> i created a refresh cart method in that same cart class and called it from the customer class login function and the problem went away, which was a pain because the cart class is initialized AFTER the customer class in catalog/controller/startup/startup.php anyway here is my forum post on the issue, so maybe you'll have a better solution based on your desired way of fixing it https://forum.opencart.com/viewtopic.php?t=211273

Can you provide the issue fix ?

**Comment by ADDCreative** [comment] 2020-01-10 17:37
The first issue about 2 minutes into the video, where a new tab shows nothing in the cart until the page is refreshed, could be a cache control issue. See https://github.com/opencart/opencart/issues/7008.

**Comment by EthanDunfordAspect** [comment] 2020-08-17 13:08
This is happening in 3.0.3.2

``` one of opencart features is cart is saved in the customers account, so when u login it adds your old basket to the new one. its a feature, i could remove it but then i will get complaints or lack a feature other carts have. ```

I don't know why a shop would double the customer's order this is definitely a bug and not a  feature.

**Comment by street454** [comment] 2020-09-08 23:52
I use 3.0.3.2 also - have SAME problem only doesn't require 15 products....
I tell customers to create the account before adding items to cart - seems to fix the issue but I still have customers who don't read... Boy are they PO'd when they get double their order - and we don't refund for customer apparel.

**Comment by grazcata** [comment] 2020-09-09 08:56
> 
> 
> I use 3.0.3.2 also - have SAME problem only doesn't require 15 products....
> I tell customers to create the account before adding items to cart - seems to fix the issue but I still have customers who don't read... Boy are they PO'd when they get double their order - and we don't refund for custom apparel.

It can be fixed with these modifications https://forum.opencart.com/viewtopic.php?t=211273

**Comment by DanDvoracek** [comment] 2020-09-11 09:27
This fix didn't do it for me.. It seems that the mess happens when users have to confirm their order. Any hints? I posted about my issue here:

https://github.com/opencart/opencart/issues/8297

**Comment by danielkerr** [comment] 2020-12-23 13:58
tested many times and can not reproduce. 

its called saved cart. maybe carts have this feature. very easy for customer to check orders.

**Closed by danielkerr** 2020-12-23 13:58 UTC
Labels: 3.0.x.x Maintenance, master-branch

**Comment by ADDCreative** [comment] 2021-01-10 17:58
@WebkulOpencart This may not affect the master as that now chains AJAX calls, but it still affect the 3.0.x.x_Maintenance branch.

I've never failed to recreate it in 3.0.x. It does depends on server load. Sometimes it happens with just 2 products in the cart and sometimes you need 50+.

**Comment by simulant-systems** [comment] 2023-09-04 10:55
This bug is a huge problem.

If there was a button for a customer to "save their cart" and then when they log it in resumed and made it clear and obvious that is what was going on, then fine - great feature.

But how it works currently, is a customer visits the website without logging in first (after all, who would if you just want to buy something, you'd expect to be prompted to login later if needed) - then they add some items to the cart, they're then prompted to login and then the cart duplicates items and merges without showing the customer.

The customer pays thinking they're just buying the items they added and instead they end up received duplicate products and have to then submit return requests.

I'm getting customer complaints daily about this.

I've applied the fixes here: https://github.com/ADDCreative/opencart/commit/a8de6f3b6b8ba85771eb6738d37cba7b357a7ce2

and those don't help. The problem still occurs.

Can someone please help with a way to fix this so baskets aren't saved (or duplicated) and instead the customer just buys what they intended to please? Fair enough the basket should be saved from guest through to logging in for that session, but there's no need for extra items then to be added to the cart without the customer being made aware.

**Comment by ADDCreative** [comment] 2023-09-04 21:16
@simulant-systems What you describe is different to this issue, which only affects customers who register at checkout.

The merging of the current cart contents with the saved cart contents at login is by design. I would search on https://forum.opencart.com/ and in the marketplace. There may be a extension that changes this behavior.
