### ISSUE TITLE
"Moved Permanently" error on admin extension pages

### ISSUE THREAD

**Issue by interbiznw** [opencart/opencart#7269] opened 2019-03-14 04:42 UTC
**What version of OpenCart are you reporting this for?**

Version 3.0.3.1

**Describe the bug**
every extension page has "Moved Permanently" error on them due to the opencart url in admin config.php being http instead of https

Fix here https://github.com/opencart/opencart/pull/7268

**Comment by interbiznw** [comment] 2019-03-14 04:50
Also causes the marketplace to not display at all in the admin>extensions>marketplace page

**Comment by danielkerr** [comment] 2019-03-30 09:11
that's noting to do with with that!

OPENCART_SERVER', 'https://www.opencart.com/');

it is ssl

the issue is fixed on the opencart server

**Closed by danielkerr** 2019-03-30 09:11 UTC

**Comment by interbiznw** [comment] 2019-03-31 04:34
Nothing to do with it, then how did it fix that issue?

**Comment by danielkerr** [comment] 2019-03-31 09:58
editr your config.php file for the front and admin and make sure that HTTP_SERVER and HTTPS_SERVER both have the https in the url

**Comment by interbiznw** [comment] 2019-03-31 10:07
Yeah I did that but this is what introduced that error in the first place, the upgrade script has http not https

![image](https://user-images.githubusercontent.com/16450422/55287765-107c6900-5362-11e9-8a35-0a92a7ef42b9.png)
