### ISSUE TITLE
Issues with Opencast Dashboard Please Help!

### ISSUE THREAD

**Issue by jakeadamsmina** [opencart/opencart#2549] opened 2015-01-09 19:21 UTC
Hi, I'm having issues with my opencart dashboard, just uploaded it today and got everything sorted with the configuration and this is what my dashboard has looked like on every computer i have logged into on. Is there anyway of getting this back to normal? and if so how? i'm not very technical and would really appreciate the help!!
Thank you - Jake Adams. 
![screen shot 2015-01-09 at 19 17 14](https://cloud.githubusercontent.com/assets/10468008/5685684/9b6b0672-9834-11e4-9217-ecfcd73b4b7d.png)

**Comment by CoverUp** [comment] 2015-01-09 19:57
seems that your style is not loading due https or www. issue, please close and use community forums instead. Good luck

**Comment by jakeadamsmina** [comment] 2015-01-09 20:15
Hi, Thank you for a prompt response. I'm not 100% sure what you're saying?

**Comment by DS-Matt** [comment] 2015-01-09 20:36
@jakeadamsmina -

This is a bug tracker (not a support forum) and your issue is not a bug - but a configuration issue.   @CoverUp is asking you to close this issue (since it's not a real bug) and look for help on the community forums (forum.opencart.com).  He is suggesting that the reason your css style sheet is not being loaded maybe because of the https connection or a www/non www domain redirect.  Either way, it's not a bug in the core of the opencart code...

Other possibilities are that you've modified the header.tpl file for the admin side and are not loading an external stylesheet.

You're best to hire a developer if you are unfamiliar  with writing software (and since you just joined github yesterday, I'm betting you are).

Best of luck!

DS-MATT

**Comment by danielkerr** [comment] 2015-01-10 10:04
reupload

**Closed by danielkerr** 2015-01-10 10:04 UTC

**Comment by jamesallsup** [comment] 2015-02-09 15:20
@DS-Matt Are you still active on OpenCart? Could you shoot me a quick message on the forums or Skype?
