### ISSUE TITLE
[Master branch] wrong usage of api/order.load

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#12057] opened 2022-11-29 11:46 UTC
The **api/order.load** (in file **catalog/controller/api/order.php**, function **load**) is buggy.

It is supposed to load an existing order from the OpenCart database (oc_order,  oc_order_product, etc) to the cart, for subsequent viewing or modification by e.g. the **admin/controller/sale/order.php** in function **info**. 

However, it uses this line for loading the order products into cart:

`$this->cart->add($product['product_id'], $product['quantity'], $option_data);`

This is wrong, because this call will take the current prices, discounts, specials, etc from the 'oc_product' table, not from the 'oc_order_product', in a subsequent call to:

`$products = $this->model_checkout_cart->getProducts();`

Thus, if after an order the product price is changed, the admin sales order info will show a wrong (e.g. current instead of the historic order) price.

I think we should not use the 'api/order.load' and 'api/sale/cart' at all in the admin/controller/sale/order.php for function info! Rather, the 'oc_order', 'oc_order_product' etc DB tables should be accessed directly via a suitable model.

**Comment by TheCartpenter** [comment] 2022-11-29 15:09
https://github.com/opencart/opencart/issues/11863

**Comment by mhcwebdesign** [comment] 2023-03-05 16:12
I just looked at the latest master branch code, and I don't think it's fixed.

The catalog/controller/api/sale/order.php, in function load, still uses this call:

`$this->cart->add($product['product_id'], $product['quantity'], $option_data);`

This will not load the order with the correct historic order info.

Are you sure it's fixed?

**Comment by danielkerr** [comment] 2023-03-05 17:31
I'll check

**Comment by mhcwebdesign** [comment] 2023-03-05 17:39
> I'll check

OK, thanks. I'll also test it tomorrow, too.

**Comment by mhcwebdesign** [comment] 2023-03-07 15:17
Update: I tried to test it, but I am unable even to do a simple checkout, see https://github.com/opencart/opencart/issues/12202 .

I'll wait till the checkout issues have been ironed out first.

**Comment by mhcwebdesign** [comment] 2023-04-19 13:30
As an update: I just tested OpenCart 4.0.2.1, created an order, then changed the item price, and the order history now keeps the old item price as expected, so far, so good now!

However, any attempt to edit any small details of the order corrupts the order history, see e.g.
https://github.com/opencart/opencart/issues/12276 or https://github.com/opencart/opencart/issues/12275

In general, no frontend API should be used for the admin backed order editor!

**Comment by ClearThinking** [comment] 2023-05-12 13:22
I can confirm this bug in 4.0.2.1. Editing other things on the order messes up the product data, which means you basically can't edit anything else on the order unless you want to re-edit the product prices after doing so. Hopefully this will be fixed in 4.0.2.2.

**Comment by danielkerr** [comment] 2023-05-12 21:07
fixed by loading the data from the ordert table. it still adds stuff everything back to the cart but of course if u change the product price then try to add the order than of course the price will change. better to void the order and create a new one.

**Comment by TheCartpenter** [comment] 2023-05-12 22:25
Yes, correct. Better to void it, in this case.

**Comment by ClearThinking** [comment] 2023-05-12 22:40
I disagree. This means you cannot edit anything on an order if the product prices have changed since the order was placed. 

For example, say you have an order with a product that has a Special price that ended yesterday, and you want to adjust the customer's name on their address. Since you can't edit anything on the order without the product price changing, it means you have to void the **entire** order for a tiny change like that. However, there's also no way to edit product prices when creating a new order, so you effectively **cannot** recreate the order that was placed the day before. 

I'm working on some edits right now, so I will post them here when they're ready. Please consider implementing them, Daniel.  Assuming I can figure it out, it would be to everyone's benefit to have this bug solved.

**Comment by TheCartpenter** [comment] 2023-05-12 23:00
If the order was placed the day before, then it is not a new order.

**Comment by ClearThinking** [comment] 2023-05-12 23:52
OK, I've been working on this for almost 3 hours. After trying edits that involved a bunch of admin and front-end files, I eventually found a solution that only involves editing one file. Here is the fix, which will load product prices from the current order data if it's being edited from the admin panel:


```
IN:
/system/library/cart/cart.php

BEFORE:
return $this->data;

ADD:
if (isset($this->session->data['api_id']) && isset($this->session->data['order_id'])) {
	$order_product_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "order_product` WHERE `order_id` = '" . (int)$this->session->data['order_id'] . "' ORDER BY `order_product_id` ASC");
	$order_products = $order_product_query->rows;
	
	$index = 0;
	foreach ($this->data as $cart_id => $product) {
		if (isset($order_products[$index])) {
			$this->data[$cart_id]['price'] = $order_products[$index]['price'];
			$this->data[$cart_id]['total'] = $order_products[$index]['price'] * $product['quantity'];
		}
		$index++;
	}
}
```

This works in all my tests, and doesn't seem to interfere with the front-end. It would be good if others tested this edit to make sure it doesn't cause any problems, but based on my testing, it seems like the most elegant fix to this problem. 

Lastly, to ensure the order products are always loaded in the same order, this would probably be a good idea as well:


```
IN:
/catalog/model/checkout/order.php

REPLACE:
$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "order_product` WHERE `order_id` = '" . (int)$order_id . "'");

WITH:
$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "order_product` WHERE `order_id` = '" . (int)$order_id . "' ORDER BY `order_product_id` ASC");
```

**Comment by TheCartpenter** [comment] 2023-05-13 01:43
The API ID cannot seriously get into libraries. The catalog/model/catalog/product.php file is also called by cart/cart.php file since OC v4.x releases. As for the ```order_product``` table, ```$this->cart``` has no distinction with the orders before the checkout/confirm controller and the api/sale/order controller pulls the object. Therefore, there are other ways to achieve this.

**Comment by ClearThinking** [comment] 2023-05-13 01:58
Sounds good, please detail them so we can get this fixed!

**Comment by danielkerr** [comment] 2023-05-13 11:59
ok ium going to add a price arg to the cart

**Comment by TheCartpenter** [comment] 2023-05-13 12:03
Should only be done if subscriptions prices are not involved.

**Comment by danielkerr** [comment] 2023-05-13 13:40
> Should only be done if subscriptions prices are not involved.

sounds like the wrong advice!

**Comment by ClearThinking** [comment] 2023-05-13 14:04
Thanks, even if it's only used for this particular function, that should hopefully solve the problem.

**Comment by TheCartpenter** [comment] 2023-05-13 17:36
> > Should only be done if subscriptions prices are not involved.
> 
> sounds like the wrong advice!

We'll see once the production days arises!

**Closed** 2023-06-05 13:37 UTC
