### ISSUE TITLE
authorize.net AIM 

### ISSUE THREAD

**Issue by abdallahmaali** [opencart/opencart#5067] opened 2016-12-06 21:41 UTC
i activate AIM and the settings as the following 

Transaction Server:live
Transaction Mode :live
Transaction Method :capture
Total
Order Status :processing 
Geo Zone all
Status :enable
Sort Order :3

but when i submit the payment form even if its empty its redirect me to my account with this message "your order has been placed "
and if i put any visa card information it's give me success message with out validate the payment
information 

any body could me in this problem ,it's driving me crazy

**Comment by arnisjuraga** [comment] 2016-12-06 22:52
Hi, @abdallahmaali 
just for the support, you should better ask in the forum: https://forum.opencart.com 
or search for similar issue. 

I doubt, this is a bug in a module, but if you still think so, just post more debug info.

Unfortunately, I have no experience with `authorize.net` plugin, but there is a plenty entries in Forum..

Anyway - if you find a solution, post it here.

**Comment by abdallahmaali** [comment] 2016-12-07 07:52
i posted it in form too ,i don't know where is the problem i don't thing this problem from settings 
at least should return response from authorize.net

**Comment by bzark** [comment] 2016-12-07 15:15
Check your authorize.net account and make sure it isn't in Test mode.  It is under Account -> Settings, then click "Test Mode".  That should be set to Live.

**Comment by abdallahmaali** [comment] 2016-12-07 15:30
yes i'm  sure its not Test Mode

**Comment by bzark** [comment] 2016-12-07 15:39
Your sure?  I think you should check.  By default all new Authorize.Net accounts are in Test Mode.

**Comment by abdallahmaali** [comment] 2016-12-07 15:41
yes i checked it now ,i don't no where is the problem  , my opencart Version 2.2.0.0 
any way to install a new extension for it ?

**Comment by bzark** [comment] 2016-12-07 15:51
I run AIM in 2.1.0.2 with no issues.  You may want to call Authorize.Net.  Sounds like an account setting issue and not a bug in the payment extension.  Check your error.log and if nothing there put a log write for the curl_exec() response.

**Comment by abdallahmaali** [comment] 2016-12-07 16:00
ok could you provide your settings options in opencart that you used and for Authorize.Net ?

**Comment by bzark** [comment] 2016-12-07 16:05
They are identical to yours.  Also to clarify, when you said you checked for "Test Mode", I don't mean in the payment extension settings in OpenCart.  I mean you have to login to your https://account.authorize.net/ account and check that it isn't in "Test Mode" there.

**Comment by abdallahmaali** [comment] 2016-12-07 16:11
yes i know i checked in both opencart and authorize.net

**Comment by bzark** [comment] 2016-12-07 16:14
Well go and write the response to the error.log and see what is up.  We can't help you without debugging info.  Without that you are just looking at the problem blindly.

**Comment by abdallahmaali** [comment] 2016-12-08 10:18
it's always return 1 and after it it's redirect to success page ,i note's in my account in authorize.net 
type is  **CARD PRESENT**
but in opoencard form in this form
[https://forum.opencart.com/viewtopic.php?t=43137](url)
my account should be  **CARD NOT PRESENT**

 _this is authorize.net response_ 
> array(27) {
  [1]=>
  string(3) "1.0"
  [2]=>
  string(1) "3"
  [3]=>
  string(2) "87"
  [4]=>
  string(68) "Transactions of this market type cannot be processed on this system."
  [5]=>
  string(0) ""
  [6]=>
  string(1) "P"
  [7]=>
  string(0) ""
  [8]=>
  string(1) "0"
  [9]=>
  string(32) "748048DB88F470E1A96A4A488836BCF6"
  [10]=>
  string(0) ""
  [11]=>
  string(0) ""
  [12]=>
  string(0) ""
  [13]=>
  string(0) ""
  [14]=>
  string(0) ""
  [15]=>
  string(0) ""
  [16]=>
  string(0) ""
  [17]=>
  string(0) ""
  [18]=>
  string(0) ""
  [19]=>
  string(0) ""
  [20]=>
  string(0) ""
  [21]=>
  string(0) ""
  [22]=>
  string(0) ""
  [23]=>
  string(0) ""
  [24]=>
  string(0) ""
  [25]=>
  string(0) ""
  [26]=>
  string(0) ""
  [27]=>
  string(0) ""
}
string(3) "1.0"
{"redirect":"https:\/\/www.naturalisintl.com\/index.php?route=checkout\/success"}

**Comment by bzark** [comment] 2016-12-08 14:35
Error 87 - Transactions of this market type cannot be processed on this system

https://support.authorize.net/authkb/index?page=content&id=A597

As we told you this is an issue with your Authorize.Net configuration, not the payment extension.  Review the link above to figure out your issue.

@danielkerr you can close this non-issue.

@abdallahmaali this is a bug tracker, for additional help with your issue use the community forum, NOT the bug tracker.

**Closed** 2016-12-08 14:41 UTC
