### ISSUE TITLE
the modules:  pay by amazon    is wrong ?

### ISSUE THREAD

**Issue by ooshipin** [opencart/opencart#6489] opened 2018-03-26 13:06 UTC
When i try to change the module "pay by amazon " from disable to enable, is shows as below

-------------------------------------

Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model marketplace/event!' in D:\phpStudy\WWW\o1\system\engine\loader.php:89 Stack trace: #0 D:\phpStudy\WWW\o1\admin\controller\extension\module\amazon_pay.php(105): Loader->model('marketplace/eve...') #1 [internal function]: ControllerExtensionModuleAmazonPay->uninstall(Array) #2 D:\phpStudy\WWW\o1\system\engine\action.php(79): call_user_func_array(Array, Array) #3 D:\phpStudy\WWW\o1\system\engine\loader.php(48): Action->execute(Object(Registry), Array) #4 D:\phpStudy\WWW\o1\admin\controller\extension\extension\module.php(54): Loader->controller('extension/modul...') #5 [internal function]: ControllerExtensionExtensionModule->uninstall() #6 D:\phpStudy\WWW\o1\system\engine\action.php(79): call_user_func_array(Array, Array) #7 D:\phpStudy\WWW\o1\admin\controller\startup\router.php(26): Action->execute(Object(Registry), Array) #8 [internal function]: ControllerStartupRouter->index() #9 D:\phpStudy\WWW\o1\system\engine\action.php(79): call_user_ in D:\phpStudy\WWW\o1\system\engine\loader.php on line 89

**Comment by ooshipin** [comment] 2018-03-26 13:07
the php version is 7.0
the opencart version is 3.0.2.0

**Comment by straightlight** [comment] 2018-03-26 22:49
This is a confirmed bug but already resolved since quite sometime on the forum: https://forum.opencart.com/viewtopic.php?f=201&t=191657&p=712843#p712843

**Comment by ooshipin** [comment] 2018-03-27 02:53
tks, it has been soloved with your help

but when i set the " extensions --->payment--->Amazon Pay", input the amazon information(seller id, client id and so ).... and i click the "save", it's wrong again ...

Notice: Undefined offset: 1 in D:\phpStudy\WWW\o1\admin\model\extension\payment\amazon_login_pay.php on line 368Notice: Undefined offset: 2 in D:\phpStudy\WWW\o1\admin\model\extension\payment\amazon_login_pay.php on line 371Notice: Undefined offset: 1 in D:\phpStudy\WWW\o1\admin\model\extension\payment\amazon_login_pay.php on line 371
Fatal error: Call to a member function registerXPathNamespace() on boolean in D:\phpStudy\WWW\o1\admin\model\extension\payment\amazon_login_pay.php on line 332

**Comment by danielkerr** [comment] 2018-03-27 04:28
It s fixed in the master

**Closed by danielkerr** 2018-03-27 04:28 UTC
