### ISSUE TITLE
Categories & Products Duplicating with a single entry

### ISSUE THREAD

**Issue by tobycim** [opencart/opencart#7483] opened 2019-06-17 03:08 UTC
Version 3.0.3.2

After adding a single new product & a single new category, a duplicate is created. Im working on the original opencart , no template.

My Issue: I entered 53 products into opencart , but theres already 71  (plus the duplicate ones I have already deleted)

**Comment by straightlight** [comment] 2019-06-18 15:29
`Im working on the original opencart , no template.`

No template but what about other extensions you may of had installed prior? Can you also specify the route names of the locations where this reported issue has been discovered? Also, were you able to notice the same thing on the Master Branch version?

**Comment by Shabbirpadela1** [comment] 2019-07-10 10:59
I installed opencart recently when i add new product, Auto generate duplicate product when i enter single product
i never use any other extension
please any  one can help

**Comment by lahmacun** [comment] 2019-07-11 12:59
I'm having the same issue. I installed Opencart and didn't do anything else. Ne extra extensions, no template. Is there anybody that solved this problem?

**Comment by mehdiRma10** [comment] 2019-07-12 15:09
it's caused by the old way of submitting form for IE ,since google chrome last update we'vw been experiencing this issue.

**Comment by mehdiRma10** [comment] 2019-07-12 15:13
it's caused by the old way of submitting form for IE ,since google chrome last update we've been experiencing this issue. you can solve it by commenting this lines :
```
//Form Submit for IE Browser
$('button[type='submit']').on('click', function() {
$("form[id*='form-']").submit();
});
```
in the admin/view/javascript/common.js file

**Comment by straightlight** [comment] 2019-07-12 15:23
The browser should be validated in the code so not to create additional problems when other browsers are being used, in this case.

**Comment by jeffreyeng-opencart** [comment] 2019-11-13 07:54
Going to close this and focus on one issue.

**Closed by jeffreyeng-opencart** 2019-11-13 07:54 UTC

**Comment by xakou** [comment] 2019-11-19 18:17
This not working with Chrome 78.0.3904.108 and OC 3.0.3.2

**Comment by redochka** [comment] 2020-03-25 14:51
Once you did the JS fix listed above, you may encounter the problem again but for different reason.

You have to add the `auto_increment` by running this:

```
ALTER TABLE oc_product_advertise_google MODIFY COLUMN product_advertise_google_id int(11) unsigned auto_increment NOT NULL;
```
