### ISSUE TITLE
Opencart fails to install.

### ISSUE THREAD

**Issue by steowens** [opencart/opencart#7746] opened 2019-12-08 20:21 UTC
**What version of OpenCart are you reporting this for?**

Tried latest version on master branch as well as downloading: opencart-3.0.3.2.zip from the opencart site and get same results.

**Describe the bug**
A clear and concise description of what the bug is\

Following the instructions in the install.txt to the letter gets a blank page and no content on completion.  Looks like both config-dist.php and admin/config-dist.php are empty files so that might have something to do with it.

What section does it affect?  All of it

**To Reproduce**
1. Download or clone open cart.
2. Execute all instructions on the install.txt page.
3. Visit the url of your open cart page
4. See absolutely nothing.

**Expected behavior**
Expected to be taken to some kind of an install page.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?   deployed to robothut.store
 - Operating system  Debian 10.
 - PHP version  7.3-fpm
 - Nginx version: nginx/1.17.6
 - Browser(s) tested with [e.g. chrome, safari - if applicable] chromim
 - Version [e.g. 22]  Version 78.0.3904.108 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Additional context**

**Comment by jeffreyeng-opencart** [comment] 2019-12-09 02:12
@steowens: 

1. Have you renamed the config files from config-dist.php to config.php on both the root and admin folder?
2. Make sure .htacess file rename from .htaccess.txt to .htaccess.
3. Have you created the database before doing the installation.

**Comment by steowens** [comment] 2019-12-09 04:41
Here is everything I did after downloading the maintenance zip from this github:

``root@localhost:~/opencart# cd opencart-3.0.x.x_Maintenance/
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance# ls
build.xml  CHANGELOG_AUTO.md  CHANGELOG.md  composer.json  composer.lock  install.txt  license.txt  README.md  upgrade.txt  upload
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance# rm -rf /var/www/robothut.store/*
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance# rm -rf /var/www/robothut.store/.*
rm: refusing to remove '.' or '..' directory: skipping '/var/www/robothut.store/.'
rm: refusing to remove '.' or '..' directory: skipping '/var/www/robothut.store/..'
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance# cp -r upload/* /var/www/robothut.store/
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance# mv /var/www/robothut.store/config-dist.php /var/www/robothut.store/config.php
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance# mv  /var/www/robothut.store/admin/config-dist.php  /var/www/robothut.store/admin/config.php
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance# ls -al
total 468
drwxr-xr-x 3 root root   4096 Nov  6 10:48 .
drwxr-xr-x 3 root root   4096 Dec  9 04:37 ..
-rw-r--r-- 1 root root   2106 Nov  6 10:48 build.xml
-rw-r--r-- 1 root root 327817 Nov  6 10:48 CHANGELOG_AUTO.md
-rw-r--r-- 1 root root  33574 Nov  6 10:48 CHANGELOG.md
-rw-r--r-- 1 root root    605 Nov  6 10:48 composer.json
-rw-r--r-- 1 root root  30911 Nov  6 10:48 composer.lock
-rw-r--r-- 1 root root   3709 Nov  6 10:48 install.txt
-rw-r--r-- 1 root root  34529 Nov  6 10:48 license.txt
-rw-r--r-- 1 root root   5021 Nov  6 10:48 README.md
-rw-r--r-- 1 root root   5995 Nov  6 10:48 upgrade.txt
drwxr-xr-x 7 root root   4096 Nov  6 10:48 upload
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance# cd  upload/
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance/upload# ls -al
total 40
drwxr-xr-x 7 root root 4096 Nov  6 10:48 .
drwxr-xr-x 3 root root 4096 Nov  6 10:48 ..
drwxr-xr-x 6 root root 4096 Nov  6 10:48 admin
drwxr-xr-x 6 root root 4096 Nov  6 10:48 catalog
-rw-r--r-- 1 root root    0 Nov  6 10:48 config-dist.php
-rw-r--r-- 1 root root 2436 Nov  6 10:48 .htaccess.txt
drwxr-xr-x 5 root root 4096 Nov  6 10:48 image
-rw-r--r-- 1 root root  293 Nov  6 10:48 index.php
drwxr-xr-x 6 root root 4096 Nov  6 10:48 install
-rw-r--r-- 1 root root  418 Nov  6 10:48 php.ini
drwxr-xr-x 7 root root 4096 Nov  6 10:48 system
root@localhost:~/opencart/opencart-3.0.x.x_Maintenance/upload# mv .htaccess.txt /var/www/robothut.store/.htaccess
``

**Comment by jeffreyeng-opencart** [comment] 2019-12-09 04:52
@steowens: I would strongly suggest to contact our support team (opencart@zendesk.com) to assist you. I'm seeing it is not a bug.

**Comment by steowens** [comment] 2019-12-09 04:55
I don't get it, if you follow the install instructions as indicated in the install.txt file, and do everyting you said above, then shouldn't the page load something?  Go check it out for your self it doesn't. Nothing at all no content whatsoever is that what the software is supposed to do?

**Comment by jeffreyeng-opencart** [comment] 2019-12-09 05:47
Is your php.ini set up to display PHP error? If not, could you change your php.ini setting to display PHP error?

**Comment by steowens** [comment] 2019-12-09 06:38
I think I figured it out and youre right not a bug.  It was a config issue in the php.ini. Needed to set  "cgi.fix_pathinfo = 0;" in php.ini

**Comment by jeffreyeng-opencart** [comment] 2019-12-09 06:40
Great! Glad it works now. I'm going ahead and close this issue.

**Closed by jeffreyeng-opencart** 2019-12-09 06:40 UTC
