### ISSUE TITLE
Extension Installer not working - version 3.0.3.2

### ISSUE THREAD

**Issue by newbie7777** [opencart/opencart#7729] opened 2019-12-02 15:57 UTC
Version 3.0.3.2

I will obviously stay on version 2.3 anyway.

Today I install the latest version of opencart, upload ocmod, go to refresh, nothing. I didn't seem to upload ocmod. The other thing I noticed is that progress bar come to 70%.
![Заснемане](https://user-images.githubusercontent.com/21267551/69973968-0c29d080-152d-11ea-817d-c5c8cf178414.PNG)
![1](https://user-images.githubusercontent.com/21267551/69974009-1e0b7380-152d-11ea-8420-546072cb6a32.PNG)

Please, help.

**Comment by jeffreyeng-opencart** [comment] 2019-12-03 03:51
@newbie7777: Please check your htaccess file. If the file is ".htaccess.txt", just remove ".txt" extension.

**Comment by jeffreyeng-opencart** [comment] 2019-12-05 04:22
Since I don't hear for you. I'm going to close this issue.

**Closed by jeffreyeng-opencart** 2019-12-05 04:22 UTC

**Comment by condor2** [comment] 2019-12-23 10:33
Is not Opencart 3.0.3.2......it is Master Branch.
3.0.3.2 doesn't have Cron

I can confirm the bug.

- zip extension is installed on php
- tested with Seo URLs enabled and disabled.
