### ISSUE TITLE
mixup of  $seo_url_info['keyword'] and  $seo_url_info['key']

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#7998] opened 2020-06-13 15:15 UTC
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre 
**Describe the bug**
getting `Undefined index: key in admin/controller/catalog/product.php on line 1204`
when trying to save a product

log gives
```
`[13-Jun-2020 14:34:23 UTC] $seo_url_info:<pre>Array
    [0] => Array
        (
            [seo_url_id] => 844
            [store_id] => 0
            [language_id] => 1
            [query] => product_id=43
            [keyword] => macbook
        )
`
```
so: `key <-> keyword, and $seo_url_info['value'] is not available`
same 4 files involved as with #7996

**Comment by straightlight** [comment] 2020-06-13 18:26
Confirmed. That is due to missing key field in the seo_url database table in the core-pre since the master branch now uses it. It will be fixed soon in the upgrade model. Thanks for posting this.

**Closed by straightlight** 2020-06-13 18:26 UTC
