### ISSUE TITLE
Something went wrong with the PDO Connection and Escape string

### ISSUE THREAD

**Issue by anytizer** [opencart/opencart#10303] opened 2021-12-13 06:45 UTC
Please look at the two files: [admin/model/catalog/product.php#L1086](https://github.com/opencart/opencart/blob/72b46cac9b45dd63a8fb32e19ffef2b51eb9ebf6/upload/admin/model/catalog/product.php#L1086) and [db/pdo.php#L53](https://github.com/opencart/opencart/blob/72b46cac9b45dd63a8fb32e19ffef2b51eb9ebf6/upload/system/library/db/pdo.php#L53) of OC Master branch.

It ends in a wrong query for the use in PDO in a fresh setup with MariaDB 10.
When you go to admin > catalog > products page, the page stops with a white screen:

```
Exception: Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 Error Code : 42000
SELECT COUNT(DISTINCT p.`product_id`) AS `total` FROM `oc1_product` p LEFT JOIN `oc1_product_description` pd ON (p.`product_id` = pd.`product_id`) WHERE pd.`language_id` = '1' AND p.`price` LIKE ':0%' in ___\upload\system\library\db\pdo.php
```

I found that the SQL contains: **p.price LIKE ':0%'** which is probably wrong for PDO (at least for this error message).
Is this issue mentioned somewhere?

**Comment by AhmedDaou** [comment] 2022-02-22 16:09
@anytizer 
I have the same issue, I will be interested to know what is the cause and solution.
I commented out the where clause for this query, it let me get over this error, but I think it causes more problems so its not a fix

Did you find a solution?

**Comment by danielkerr** [comment] 2022-05-21 14:11
ok moved all % within db->escape and not on the outside as its causing issue.

**Closed by danielkerr** 2022-05-21 14:11 UTC
Labels: master-branch
