### ISSUE TITLE
[SAGEPAY SERVER] Status=INVALID StatusDetail= Cannot match the MD5 Hash. Order might be tampered with

### ISSUE THREAD

**Issue by GeonetScott** [opencart/opencart#4859] opened 2016-09-02 11:13 UTC
We're using Opencart v2.0.1.1, we can make payments via Sagepay Server (selecting Paypal option).

The payments work successfully, but we get this error:

`Response received: HttpResponse{body='Status=INVALID StatusDetail= Cannot match the MD5 Hash. Order might be tampered with. RedirectURL=http://mysportswear.co.uk/index.php?route=payment/sagepay_server/failure ', statusCode=200, statusMessage='OK'}`

This gives us the class 5006 error: Unable to redirect to the Vendor's web site. The vendor failed to provide a RedirectionURL.

The route of this error seems to occurr at like 346 in catalog/controller/payment/sagepay_server.php:

if ($str_my_signature != $str_vps_signature) {
            $this->model_payment_sagepay_server->deleteOrder($order_id);

```
        echo "Status=INVALID" . $end_ln;
        echo "StatusDetail= Cannot match the MD5 Hash. Order might be tampered with." . $end_ln;
        echo "RedirectURL=" . $error_page . $end_ln;

        $this->model_payment_sagepay_server->logger('StatusDetail= Cannot match the MD5 Hash. Order might be tampered with.');

        return;
    }
```

Has anybody encountered this problem before?

**Comment by jtaylor69** [comment] 2017-06-06 11:46
Please check your database to see if multiple order IDs are present within the same timeframe.
A customer of ours had the same issue where there would be mismatch of signatures, which was caused by the database trying to pick from the same order ID, with a different SecurityKey.
I have opened a PR #5481 which should resolve this

**Comment by danielkerr** [comment] 2017-07-15 12:04
i think this is fixed with this commit 

https://github.com/opencart/opencart/pull/5481

**Closed by danielkerr** 2017-07-15 12:04 UTC
Labels: Needs testing
